#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 154
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 63
#define ALIAS_COUNT 0
#define TOKEN_COUNT 17
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 8
#define MAX_ALIAS_SEQUENCE_LENGTH 9
#define PRODUCTION_ID_COUNT 9

enum ts_symbol_identifiers {
  sym_comment = 1,
  anon_sym_component = 2,
  anon_sym_LPAREN = 3,
  anon_sym_RPAREN = 4,
  anon_sym_EQ_GT = 5,
  anon_sym_end = 6,
  anon_sym_signal = 7,
  anon_sym_LT_EQ = 8,
  anon_sym_COMMA = 9,
  anon_sym_DOT = 10,
  anon_sym_not = 11,
  anon_sym_and = 12,
  anon_sym_or = 13,
  anon_sym_COLON = 14,
  sym_identifier = 15,
  sym_number = 16,
  sym_source_file = 17,
  aux_sym__source_block = 18,
  sym__comments = 19,
  sym__statements = 20,
  sym__statement = 21,
  sym_component = 22,
  sym_component_inputs = 23,
  sym_component_outputs = 24,
  sym_component_body = 25,
  sym_declaration = 26,
  sym__declaration_left = 27,
  sym__declaration_right = 28,
  sym_declaration_left_list = 29,
  sym_declaration_right_list = 30,
  sym__declarator = 31,
  sym_assignment = 32,
  sym__assignment_left = 33,
  sym__assignment_right = 34,
  sym_assignment_left_list = 35,
  sym_assignment_right_list = 36,
  sym__expression = 37,
  sym__expression_primary = 38,
  sym__signal_reference = 39,
  sym_reference = 40,
  sym_expression_component = 41,
  sym__expression_component_reference = 42,
  sym_component_reference = 43,
  sym__expression_component_input = 44,
  sym_expression_component_input_list = 45,
  sym_expression_unary = 46,
  sym_expression_binary = 47,
  sym_declarator_subscript = 48,
  sym__subscript = 49,
  sym__index = 50,
  sym__range = 51,
  sym_range_closed = 52,
  sym_range_open_left = 53,
  sym_range_open_right = 54,
  sym__atomic = 55,
  sym__identifiers = 56,
  aux_sym__comments_repeat1 = 57,
  aux_sym__statements_repeat1 = 58,
  aux_sym_declaration_left_list_repeat1 = 59,
  aux_sym_declaration_right_list_repeat1 = 60,
  aux_sym_assignment_left_list_repeat1 = 61,
  aux_sym_component_reference_repeat1 = 62,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_comment] = "comment",
  [anon_sym_component] = "component",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_EQ_GT] = "=>",
  [anon_sym_end] = "end",
  [anon_sym_signal] = "signal",
  [anon_sym_LT_EQ] = "<=",
  [anon_sym_COMMA] = ",",
  [anon_sym_DOT] = ".",
  [anon_sym_not] = "not",
  [anon_sym_and] = "and",
  [anon_sym_or] = "or",
  [anon_sym_COLON] = ":",
  [sym_identifier] = "identifier",
  [sym_number] = "number",
  [sym_source_file] = "source_file",
  [aux_sym__source_block] = "_source_block",
  [sym__comments] = "_comments",
  [sym__statements] = "_statements",
  [sym__statement] = "_statement",
  [sym_component] = "component",
  [sym_component_inputs] = "component_inputs",
  [sym_component_outputs] = "component_outputs",
  [sym_component_body] = "component_body",
  [sym_declaration] = "declaration",
  [sym__declaration_left] = "_declaration_left",
  [sym__declaration_right] = "_declaration_right",
  [sym_declaration_left_list] = "declaration_left_list",
  [sym_declaration_right_list] = "declaration_right_list",
  [sym__declarator] = "_declarator",
  [sym_assignment] = "assignment",
  [sym__assignment_left] = "_assignment_left",
  [sym__assignment_right] = "_assignment_right",
  [sym_assignment_left_list] = "assignment_left_list",
  [sym_assignment_right_list] = "assignment_right_list",
  [sym__expression] = "_expression",
  [sym__expression_primary] = "_expression_primary",
  [sym__signal_reference] = "_signal_reference",
  [sym_reference] = "reference",
  [sym_expression_component] = "expression_component",
  [sym__expression_component_reference] = "_expression_component_reference",
  [sym_component_reference] = "component_reference",
  [sym__expression_component_input] = "_expression_component_input",
  [sym_expression_component_input_list] = "expression_component_input_list",
  [sym_expression_unary] = "expression_unary",
  [sym_expression_binary] = "expression_binary",
  [sym_declarator_subscript] = "declarator_subscript",
  [sym__subscript] = "_subscript",
  [sym__index] = "_index",
  [sym__range] = "_range",
  [sym_range_closed] = "range_closed",
  [sym_range_open_left] = "range_open_left",
  [sym_range_open_right] = "range_open_right",
  [sym__atomic] = "_atomic",
  [sym__identifiers] = "_identifiers",
  [aux_sym__comments_repeat1] = "_comments_repeat1",
  [aux_sym__statements_repeat1] = "_statements_repeat1",
  [aux_sym_declaration_left_list_repeat1] = "declaration_left_list_repeat1",
  [aux_sym_declaration_right_list_repeat1] = "declaration_right_list_repeat1",
  [aux_sym_assignment_left_list_repeat1] = "assignment_left_list_repeat1",
  [aux_sym_component_reference_repeat1] = "component_reference_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_comment] = sym_comment,
  [anon_sym_component] = anon_sym_component,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_EQ_GT] = anon_sym_EQ_GT,
  [anon_sym_end] = anon_sym_end,
  [anon_sym_signal] = anon_sym_signal,
  [anon_sym_LT_EQ] = anon_sym_LT_EQ,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_DOT] = anon_sym_DOT,
  [anon_sym_not] = anon_sym_not,
  [anon_sym_and] = anon_sym_and,
  [anon_sym_or] = anon_sym_or,
  [anon_sym_COLON] = anon_sym_COLON,
  [sym_identifier] = sym_identifier,
  [sym_number] = sym_number,
  [sym_source_file] = sym_source_file,
  [aux_sym__source_block] = aux_sym__source_block,
  [sym__comments] = sym__comments,
  [sym__statements] = sym__statements,
  [sym__statement] = sym__statement,
  [sym_component] = sym_component,
  [sym_component_inputs] = sym_component_inputs,
  [sym_component_outputs] = sym_component_outputs,
  [sym_component_body] = sym_component_body,
  [sym_declaration] = sym_declaration,
  [sym__declaration_left] = sym__declaration_left,
  [sym__declaration_right] = sym__declaration_right,
  [sym_declaration_left_list] = sym_declaration_left_list,
  [sym_declaration_right_list] = sym_declaration_right_list,
  [sym__declarator] = sym__declarator,
  [sym_assignment] = sym_assignment,
  [sym__assignment_left] = sym__assignment_left,
  [sym__assignment_right] = sym__assignment_right,
  [sym_assignment_left_list] = sym_assignment_left_list,
  [sym_assignment_right_list] = sym_assignment_right_list,
  [sym__expression] = sym__expression,
  [sym__expression_primary] = sym__expression_primary,
  [sym__signal_reference] = sym__signal_reference,
  [sym_reference] = sym_reference,
  [sym_expression_component] = sym_expression_component,
  [sym__expression_component_reference] = sym__expression_component_reference,
  [sym_component_reference] = sym_component_reference,
  [sym__expression_component_input] = sym__expression_component_input,
  [sym_expression_component_input_list] = sym_expression_component_input_list,
  [sym_expression_unary] = sym_expression_unary,
  [sym_expression_binary] = sym_expression_binary,
  [sym_declarator_subscript] = sym_declarator_subscript,
  [sym__subscript] = sym__subscript,
  [sym__index] = sym__index,
  [sym__range] = sym__range,
  [sym_range_closed] = sym_range_closed,
  [sym_range_open_left] = sym_range_open_left,
  [sym_range_open_right] = sym_range_open_right,
  [sym__atomic] = sym__atomic,
  [sym__identifiers] = sym__identifiers,
  [aux_sym__comments_repeat1] = aux_sym__comments_repeat1,
  [aux_sym__statements_repeat1] = aux_sym__statements_repeat1,
  [aux_sym_declaration_left_list_repeat1] = aux_sym_declaration_left_list_repeat1,
  [aux_sym_declaration_right_list_repeat1] = aux_sym_declaration_right_list_repeat1,
  [aux_sym_assignment_left_list_repeat1] = aux_sym_assignment_left_list_repeat1,
  [aux_sym_component_reference_repeat1] = aux_sym_component_reference_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_component] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_end] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_signal] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_not] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_and] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_or] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [aux_sym__source_block] = {
    .visible = false,
    .named = false,
  },
  [sym__comments] = {
    .visible = false,
    .named = true,
  },
  [sym__statements] = {
    .visible = false,
    .named = true,
  },
  [sym__statement] = {
    .visible = false,
    .named = true,
  },
  [sym_component] = {
    .visible = true,
    .named = true,
  },
  [sym_component_inputs] = {
    .visible = true,
    .named = true,
  },
  [sym_component_outputs] = {
    .visible = true,
    .named = true,
  },
  [sym_component_body] = {
    .visible = true,
    .named = true,
  },
  [sym_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym__declaration_left] = {
    .visible = false,
    .named = true,
  },
  [sym__declaration_right] = {
    .visible = false,
    .named = true,
  },
  [sym_declaration_left_list] = {
    .visible = true,
    .named = true,
  },
  [sym_declaration_right_list] = {
    .visible = true,
    .named = true,
  },
  [sym__declarator] = {
    .visible = false,
    .named = true,
  },
  [sym_assignment] = {
    .visible = true,
    .named = true,
  },
  [sym__assignment_left] = {
    .visible = false,
    .named = true,
  },
  [sym__assignment_right] = {
    .visible = false,
    .named = true,
  },
  [sym_assignment_left_list] = {
    .visible = true,
    .named = true,
  },
  [sym_assignment_right_list] = {
    .visible = true,
    .named = true,
  },
  [sym__expression] = {
    .visible = false,
    .named = true,
  },
  [sym__expression_primary] = {
    .visible = false,
    .named = true,
  },
  [sym__signal_reference] = {
    .visible = false,
    .named = true,
  },
  [sym_reference] = {
    .visible = true,
    .named = true,
  },
  [sym_expression_component] = {
    .visible = true,
    .named = true,
  },
  [sym__expression_component_reference] = {
    .visible = false,
    .named = true,
  },
  [sym_component_reference] = {
    .visible = true,
    .named = true,
  },
  [sym__expression_component_input] = {
    .visible = false,
    .named = true,
  },
  [sym_expression_component_input_list] = {
    .visible = true,
    .named = true,
  },
  [sym_expression_unary] = {
    .visible = true,
    .named = true,
  },
  [sym_expression_binary] = {
    .visible = true,
    .named = true,
  },
  [sym_declarator_subscript] = {
    .visible = true,
    .named = true,
  },
  [sym__subscript] = {
    .visible = false,
    .named = true,
  },
  [sym__index] = {
    .visible = false,
    .named = true,
  },
  [sym__range] = {
    .visible = false,
    .named = true,
  },
  [sym_range_closed] = {
    .visible = true,
    .named = true,
  },
  [sym_range_open_left] = {
    .visible = true,
    .named = true,
  },
  [sym_range_open_right] = {
    .visible = true,
    .named = true,
  },
  [sym__atomic] = {
    .visible = false,
    .named = true,
  },
  [sym__identifiers] = {
    .visible = false,
    .named = true,
  },
  [aux_sym__comments_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__statements_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_declaration_left_list_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_declaration_right_list_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_assignment_left_list_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_component_reference_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_body = 1,
  field_inputs = 2,
  field_left = 3,
  field_name = 4,
  field_operand = 5,
  field_outputs = 6,
  field_right = 7,
  field_width = 8,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_body] = "body",
  [field_inputs] = "inputs",
  [field_left] = "left",
  [field_name] = "name",
  [field_operand] = "operand",
  [field_outputs] = "outputs",
  [field_right] = "right",
  [field_width] = "width",
};

static const TSFieldMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 2},
  [3] = {.index = 3, .length = 1},
  [4] = {.index = 4, .length = 2},
  [5] = {.index = 6, .length = 1},
  [6] = {.index = 7, .length = 2},
  [7] = {.index = 9, .length = 3},
  [8] = {.index = 12, .length = 4},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_left, 1},
  [1] =
    {field_left, 0},
    {field_right, 2},
  [3] =
    {field_width, 2},
  [4] =
    {field_left, 1},
    {field_right, 3},
  [6] =
    {field_operand, 1},
  [7] =
    {field_inputs, 2},
    {field_name, 0},
  [9] =
    {field_inputs, 3},
    {field_name, 1},
    {field_outputs, 6},
  [12] =
    {field_body, 7},
    {field_inputs, 3},
    {field_name, 1},
    {field_outputs, 6},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 2,
  [4] = 4,
  [5] = 5,
  [6] = 5,
  [7] = 5,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 4,
  [13] = 11,
  [14] = 8,
  [15] = 15,
  [16] = 15,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 17,
  [21] = 19,
  [22] = 17,
  [23] = 15,
  [24] = 18,
  [25] = 18,
  [26] = 19,
  [27] = 27,
  [28] = 27,
  [29] = 29,
  [30] = 29,
  [31] = 31,
  [32] = 31,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 33,
  [37] = 37,
  [38] = 38,
  [39] = 35,
  [40] = 34,
  [41] = 38,
  [42] = 37,
  [43] = 35,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 53,
  [57] = 48,
  [58] = 58,
  [59] = 52,
  [60] = 58,
  [61] = 51,
  [62] = 62,
  [63] = 63,
  [64] = 63,
  [65] = 47,
  [66] = 54,
  [67] = 67,
  [68] = 55,
  [69] = 45,
  [70] = 67,
  [71] = 62,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 74,
  [77] = 77,
  [78] = 72,
  [79] = 73,
  [80] = 77,
  [81] = 31,
  [82] = 75,
  [83] = 83,
  [84] = 84,
  [85] = 85,
  [86] = 85,
  [87] = 83,
  [88] = 84,
  [89] = 89,
  [90] = 33,
  [91] = 91,
  [92] = 92,
  [93] = 93,
  [94] = 94,
  [95] = 91,
  [96] = 96,
  [97] = 97,
  [98] = 96,
  [99] = 89,
  [100] = 92,
  [101] = 37,
  [102] = 94,
  [103] = 58,
  [104] = 52,
  [105] = 47,
  [106] = 53,
  [107] = 55,
  [108] = 62,
  [109] = 45,
  [110] = 48,
  [111] = 111,
  [112] = 112,
  [113] = 113,
  [114] = 73,
  [115] = 115,
  [116] = 116,
  [117] = 117,
  [118] = 118,
  [119] = 115,
  [120] = 117,
  [121] = 121,
  [122] = 122,
  [123] = 115,
  [124] = 122,
  [125] = 113,
  [126] = 126,
  [127] = 127,
  [128] = 128,
  [129] = 129,
  [130] = 128,
  [131] = 131,
  [132] = 132,
  [133] = 128,
  [134] = 134,
  [135] = 134,
  [136] = 136,
  [137] = 137,
  [138] = 138,
  [139] = 127,
  [140] = 129,
  [141] = 141,
  [142] = 141,
  [143] = 143,
  [144] = 144,
  [145] = 145,
  [146] = 146,
  [147] = 137,
  [148] = 132,
  [149] = 137,
  [150] = 144,
  [151] = 127,
  [152] = 136,
  [153] = 146,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(15);
      ADVANCE_MAP(
        '#', 16,
        '(', 18,
        ')', 19,
        ',', 25,
        '.', 26,
        ':', 32,
        '<', 6,
        '=', 7,
        'a', 41,
        'c', 46,
        'e', 44,
        'n', 47,
        'o', 50,
        's', 38,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(54);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(53);
      END_STATE();
    case 1:
      ADVANCE_MAP(
        '#', 16,
        '(', 18,
        ',', 25,
        '.', 26,
        ':', 32,
        'a', 41,
        'c', 46,
        'e', 44,
        'o', 50,
        's', 38,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(54);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(53);
      END_STATE();
    case 2:
      ADVANCE_MAP(
        '#', 16,
        ')', 19,
        ',', 25,
        ':', 32,
        '<', 6,
        'c', 46,
        'e', 44,
        's', 38,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(2);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(53);
      END_STATE();
    case 3:
      ADVANCE_MAP(
        '(', 18,
        ')', 19,
        ',', 25,
        '.', 26,
        ':', 32,
        'a', 10,
        'e', 11,
        'o', 12,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(3);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(54);
      END_STATE();
    case 4:
      if (lookahead == '(') ADVANCE(18);
      if (lookahead == 'n') ADVANCE(47);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(4);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(54);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(53);
      END_STATE();
    case 5:
      if (lookahead == ':') ADVANCE(32);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(5);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(54);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(53);
      END_STATE();
    case 6:
      if (lookahead == '=') ADVANCE(24);
      END_STATE();
    case 7:
      if (lookahead == '>') ADVANCE(20);
      END_STATE();
    case 8:
      if (lookahead == 'd') ADVANCE(28);
      END_STATE();
    case 9:
      if (lookahead == 'd') ADVANCE(21);
      END_STATE();
    case 10:
      if (lookahead == 'n') ADVANCE(8);
      END_STATE();
    case 11:
      if (lookahead == 'n') ADVANCE(9);
      END_STATE();
    case 12:
      if (lookahead == 'r') ADVANCE(30);
      END_STATE();
    case 13:
      if (eof) ADVANCE(15);
      ADVANCE_MAP(
        '#', 16,
        '(', 18,
        ',', 25,
        '.', 26,
        ':', 32,
        'a', 41,
        'c', 46,
        'o', 50,
        's', 38,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(13);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(54);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(53);
      END_STATE();
    case 14:
      if (eof) ADVANCE(15);
      if (lookahead == '#') ADVANCE(16);
      if (lookahead == ',') ADVANCE(25);
      if (lookahead == ':') ADVANCE(32);
      if (lookahead == '<') ADVANCE(6);
      if (lookahead == 'c') ADVANCE(46);
      if (lookahead == 's') ADVANCE(38);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(14);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(53);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(16);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_component);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(53);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_EQ_GT);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_end);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_end);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(53);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_signal);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(53);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_LT_EQ);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_not);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(53);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_and);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_and);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(53);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_or);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_or);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(53);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'a') ADVANCE(39);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(53);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'd') ADVANCE(29);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(53);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'd') ADVANCE(22);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(53);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(45);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(53);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'g') ADVANCE(42);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(53);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'i') ADVANCE(37);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(53);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'l') ADVANCE(23);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(53);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'm') ADVANCE(49);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(53);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'n') ADVANCE(34);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(53);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'n') ADVANCE(33);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(53);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'n') ADVANCE(36);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(53);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'n') ADVANCE(35);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(53);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'n') ADVANCE(52);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(53);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'o') ADVANCE(40);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(53);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'o') ADVANCE(51);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(53);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'o') ADVANCE(43);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(53);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'p') ADVANCE(48);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(53);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'r') ADVANCE(31);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(53);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 't') ADVANCE(27);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(53);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 't') ADVANCE(17);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(53);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(53);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(54);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 14},
  [2] = {.lex_state = 2},
  [3] = {.lex_state = 2},
  [4] = {.lex_state = 14},
  [5] = {.lex_state = 4},
  [6] = {.lex_state = 4},
  [7] = {.lex_state = 4},
  [8] = {.lex_state = 4},
  [9] = {.lex_state = 14},
  [10] = {.lex_state = 2},
  [11] = {.lex_state = 4},
  [12] = {.lex_state = 2},
  [13] = {.lex_state = 4},
  [14] = {.lex_state = 4},
  [15] = {.lex_state = 4},
  [16] = {.lex_state = 4},
  [17] = {.lex_state = 4},
  [18] = {.lex_state = 4},
  [19] = {.lex_state = 4},
  [20] = {.lex_state = 4},
  [21] = {.lex_state = 4},
  [22] = {.lex_state = 4},
  [23] = {.lex_state = 4},
  [24] = {.lex_state = 4},
  [25] = {.lex_state = 4},
  [26] = {.lex_state = 4},
  [27] = {.lex_state = 2},
  [28] = {.lex_state = 14},
  [29] = {.lex_state = 14},
  [30] = {.lex_state = 2},
  [31] = {.lex_state = 1},
  [32] = {.lex_state = 13},
  [33] = {.lex_state = 13},
  [34] = {.lex_state = 13},
  [35] = {.lex_state = 5},
  [36] = {.lex_state = 1},
  [37] = {.lex_state = 13},
  [38] = {.lex_state = 13},
  [39] = {.lex_state = 5},
  [40] = {.lex_state = 1},
  [41] = {.lex_state = 1},
  [42] = {.lex_state = 1},
  [43] = {.lex_state = 5},
  [44] = {.lex_state = 2},
  [45] = {.lex_state = 13},
  [46] = {.lex_state = 2},
  [47] = {.lex_state = 1},
  [48] = {.lex_state = 1},
  [49] = {.lex_state = 2},
  [50] = {.lex_state = 2},
  [51] = {.lex_state = 14},
  [52] = {.lex_state = 1},
  [53] = {.lex_state = 1},
  [54] = {.lex_state = 2},
  [55] = {.lex_state = 1},
  [56] = {.lex_state = 13},
  [57] = {.lex_state = 13},
  [58] = {.lex_state = 1},
  [59] = {.lex_state = 13},
  [60] = {.lex_state = 13},
  [61] = {.lex_state = 2},
  [62] = {.lex_state = 1},
  [63] = {.lex_state = 14},
  [64] = {.lex_state = 2},
  [65] = {.lex_state = 13},
  [66] = {.lex_state = 14},
  [67] = {.lex_state = 2},
  [68] = {.lex_state = 13},
  [69] = {.lex_state = 1},
  [70] = {.lex_state = 14},
  [71] = {.lex_state = 13},
  [72] = {.lex_state = 14},
  [73] = {.lex_state = 14},
  [74] = {.lex_state = 14},
  [75] = {.lex_state = 2},
  [76] = {.lex_state = 2},
  [77] = {.lex_state = 14},
  [78] = {.lex_state = 2},
  [79] = {.lex_state = 2},
  [80] = {.lex_state = 2},
  [81] = {.lex_state = 3},
  [82] = {.lex_state = 14},
  [83] = {.lex_state = 2},
  [84] = {.lex_state = 14},
  [85] = {.lex_state = 2},
  [86] = {.lex_state = 14},
  [87] = {.lex_state = 14},
  [88] = {.lex_state = 2},
  [89] = {.lex_state = 14},
  [90] = {.lex_state = 3},
  [91] = {.lex_state = 2},
  [92] = {.lex_state = 5},
  [93] = {.lex_state = 2},
  [94] = {.lex_state = 2},
  [95] = {.lex_state = 14},
  [96] = {.lex_state = 2},
  [97] = {.lex_state = 3},
  [98] = {.lex_state = 14},
  [99] = {.lex_state = 2},
  [100] = {.lex_state = 5},
  [101] = {.lex_state = 3},
  [102] = {.lex_state = 14},
  [103] = {.lex_state = 3},
  [104] = {.lex_state = 3},
  [105] = {.lex_state = 3},
  [106] = {.lex_state = 3},
  [107] = {.lex_state = 3},
  [108] = {.lex_state = 3},
  [109] = {.lex_state = 3},
  [110] = {.lex_state = 3},
  [111] = {.lex_state = 0},
  [112] = {.lex_state = 0},
  [113] = {.lex_state = 5},
  [114] = {.lex_state = 0},
  [115] = {.lex_state = 3},
  [116] = {.lex_state = 0},
  [117] = {.lex_state = 5},
  [118] = {.lex_state = 0},
  [119] = {.lex_state = 3},
  [120] = {.lex_state = 5},
  [121] = {.lex_state = 0},
  [122] = {.lex_state = 5},
  [123] = {.lex_state = 3},
  [124] = {.lex_state = 5},
  [125] = {.lex_state = 5},
  [126] = {.lex_state = 0},
  [127] = {.lex_state = 0},
  [128] = {.lex_state = 0},
  [129] = {.lex_state = 0},
  [130] = {.lex_state = 0},
  [131] = {.lex_state = 5},
  [132] = {.lex_state = 0},
  [133] = {.lex_state = 0},
  [134] = {.lex_state = 3},
  [135] = {.lex_state = 3},
  [136] = {.lex_state = 0},
  [137] = {.lex_state = 0},
  [138] = {.lex_state = 5},
  [139] = {.lex_state = 0},
  [140] = {.lex_state = 0},
  [141] = {.lex_state = 0},
  [142] = {.lex_state = 0},
  [143] = {.lex_state = 0},
  [144] = {.lex_state = 0},
  [145] = {.lex_state = 0},
  [146] = {.lex_state = 5},
  [147] = {.lex_state = 0},
  [148] = {.lex_state = 0},
  [149] = {.lex_state = 0},
  [150] = {.lex_state = 0},
  [151] = {.lex_state = 0},
  [152] = {.lex_state = 0},
  [153] = {.lex_state = 5},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_comment] = ACTIONS(1),
    [anon_sym_component] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_EQ_GT] = ACTIONS(1),
    [anon_sym_end] = ACTIONS(1),
    [anon_sym_signal] = ACTIONS(1),
    [anon_sym_LT_EQ] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [anon_sym_not] = ACTIONS(1),
    [anon_sym_and] = ACTIONS(1),
    [anon_sym_or] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
  },
  [1] = {
    [sym_source_file] = STATE(143),
    [aux_sym__source_block] = STATE(9),
    [sym__comments] = STATE(9),
    [sym__statements] = STATE(9),
    [sym__statement] = STATE(29),
    [sym_component] = STATE(29),
    [sym_declaration] = STATE(29),
    [sym_assignment] = STATE(29),
    [sym__assignment_left] = STATE(142),
    [sym_assignment_left_list] = STATE(142),
    [aux_sym__comments_repeat1] = STATE(86),
    [aux_sym__statements_repeat1] = STATE(29),
    [ts_builtin_sym_end] = ACTIONS(3),
    [sym_comment] = ACTIONS(5),
    [anon_sym_component] = ACTIONS(7),
    [anon_sym_signal] = ACTIONS(9),
    [sym_identifier] = ACTIONS(11),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 10,
    ACTIONS(11), 1,
      sym_identifier,
    ACTIONS(13), 1,
      sym_comment,
    ACTIONS(15), 1,
      anon_sym_component,
    ACTIONS(17), 1,
      anon_sym_end,
    ACTIONS(19), 1,
      anon_sym_signal,
    STATE(85), 1,
      aux_sym__comments_repeat1,
    STATE(135), 1,
      sym_component_body,
    STATE(141), 2,
      sym__assignment_left,
      sym_assignment_left_list,
    STATE(10), 3,
      aux_sym__source_block,
      sym__comments,
      sym__statements,
    STATE(30), 5,
      sym__statement,
      sym_component,
      sym_declaration,
      sym_assignment,
      aux_sym__statements_repeat1,
  [38] = 10,
    ACTIONS(11), 1,
      sym_identifier,
    ACTIONS(13), 1,
      sym_comment,
    ACTIONS(15), 1,
      anon_sym_component,
    ACTIONS(19), 1,
      anon_sym_signal,
    ACTIONS(21), 1,
      anon_sym_end,
    STATE(85), 1,
      aux_sym__comments_repeat1,
    STATE(134), 1,
      sym_component_body,
    STATE(141), 2,
      sym__assignment_left,
      sym_assignment_left_list,
    STATE(10), 3,
      aux_sym__source_block,
      sym__comments,
      sym__statements,
    STATE(30), 5,
      sym__statement,
      sym_component,
      sym_declaration,
      sym_assignment,
      aux_sym__statements_repeat1,
  [76] = 9,
    ACTIONS(23), 1,
      ts_builtin_sym_end,
    ACTIONS(25), 1,
      sym_comment,
    ACTIONS(28), 1,
      anon_sym_component,
    ACTIONS(31), 1,
      anon_sym_signal,
    ACTIONS(34), 1,
      sym_identifier,
    STATE(86), 1,
      aux_sym__comments_repeat1,
    STATE(142), 2,
      sym__assignment_left,
      sym_assignment_left_list,
    STATE(4), 3,
      aux_sym__source_block,
      sym__comments,
      sym__statements,
    STATE(29), 5,
      sym__statement,
      sym_component,
      sym_declaration,
      sym_assignment,
      aux_sym__statements_repeat1,
  [111] = 7,
    ACTIONS(37), 1,
      anon_sym_LPAREN,
    ACTIONS(39), 1,
      anon_sym_not,
    ACTIONS(41), 1,
      sym_identifier,
    ACTIONS(43), 1,
      sym_number,
    STATE(128), 2,
      sym__expression_component_input,
      sym_expression_component_input_list,
    STATE(147), 2,
      sym__expression_component_reference,
      sym_component_reference,
    STATE(97), 8,
      sym__expression,
      sym__expression_primary,
      sym__signal_reference,
      sym_reference,
      sym_expression_component,
      sym_expression_unary,
      sym_expression_binary,
      sym__atomic,
  [142] = 7,
    ACTIONS(37), 1,
      anon_sym_LPAREN,
    ACTIONS(39), 1,
      anon_sym_not,
    ACTIONS(41), 1,
      sym_identifier,
    ACTIONS(43), 1,
      sym_number,
    STATE(130), 2,
      sym__expression_component_input,
      sym_expression_component_input_list,
    STATE(147), 2,
      sym__expression_component_reference,
      sym_component_reference,
    STATE(97), 8,
      sym__expression,
      sym__expression_primary,
      sym__signal_reference,
      sym_reference,
      sym_expression_component,
      sym_expression_unary,
      sym_expression_binary,
      sym__atomic,
  [173] = 7,
    ACTIONS(37), 1,
      anon_sym_LPAREN,
    ACTIONS(39), 1,
      anon_sym_not,
    ACTIONS(41), 1,
      sym_identifier,
    ACTIONS(43), 1,
      sym_number,
    STATE(133), 2,
      sym__expression_component_input,
      sym_expression_component_input_list,
    STATE(147), 2,
      sym__expression_component_reference,
      sym_component_reference,
    STATE(97), 8,
      sym__expression,
      sym__expression_primary,
      sym__signal_reference,
      sym_reference,
      sym_expression_component,
      sym_expression_unary,
      sym_expression_binary,
      sym__atomic,
  [204] = 7,
    ACTIONS(45), 1,
      anon_sym_LPAREN,
    ACTIONS(47), 1,
      anon_sym_not,
    ACTIONS(49), 1,
      sym_identifier,
    ACTIONS(51), 1,
      sym_number,
    STATE(95), 2,
      sym__declaration_right,
      sym_declaration_right_list,
    STATE(137), 2,
      sym__expression_component_reference,
      sym_component_reference,
    STATE(38), 8,
      sym__expression,
      sym__expression_primary,
      sym__signal_reference,
      sym_reference,
      sym_expression_component,
      sym_expression_unary,
      sym_expression_binary,
      sym__atomic,
  [235] = 9,
    ACTIONS(5), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_component,
    ACTIONS(9), 1,
      anon_sym_signal,
    ACTIONS(11), 1,
      sym_identifier,
    ACTIONS(53), 1,
      ts_builtin_sym_end,
    STATE(86), 1,
      aux_sym__comments_repeat1,
    STATE(142), 2,
      sym__assignment_left,
      sym_assignment_left_list,
    STATE(4), 3,
      aux_sym__source_block,
      sym__comments,
      sym__statements,
    STATE(29), 5,
      sym__statement,
      sym_component,
      sym_declaration,
      sym_assignment,
      aux_sym__statements_repeat1,
  [270] = 9,
    ACTIONS(11), 1,
      sym_identifier,
    ACTIONS(13), 1,
      sym_comment,
    ACTIONS(15), 1,
      anon_sym_component,
    ACTIONS(19), 1,
      anon_sym_signal,
    ACTIONS(55), 1,
      anon_sym_end,
    STATE(85), 1,
      aux_sym__comments_repeat1,
    STATE(141), 2,
      sym__assignment_left,
      sym_assignment_left_list,
    STATE(12), 3,
      aux_sym__source_block,
      sym__comments,
      sym__statements,
    STATE(30), 5,
      sym__statement,
      sym_component,
      sym_declaration,
      sym_assignment,
      aux_sym__statements_repeat1,
  [305] = 7,
    ACTIONS(57), 1,
      anon_sym_LPAREN,
    ACTIONS(59), 1,
      anon_sym_not,
    ACTIONS(61), 1,
      sym_identifier,
    ACTIONS(63), 1,
      sym_number,
    STATE(96), 2,
      sym__assignment_right,
      sym_assignment_right_list,
    STATE(149), 2,
      sym__expression_component_reference,
      sym_component_reference,
    STATE(40), 8,
      sym__expression,
      sym__expression_primary,
      sym__signal_reference,
      sym_reference,
      sym_expression_component,
      sym_expression_unary,
      sym_expression_binary,
      sym__atomic,
  [336] = 9,
    ACTIONS(34), 1,
      sym_identifier,
    ACTIONS(65), 1,
      sym_comment,
    ACTIONS(68), 1,
      anon_sym_component,
    ACTIONS(71), 1,
      anon_sym_end,
    ACTIONS(73), 1,
      anon_sym_signal,
    STATE(85), 1,
      aux_sym__comments_repeat1,
    STATE(141), 2,
      sym__assignment_left,
      sym_assignment_left_list,
    STATE(12), 3,
      aux_sym__source_block,
      sym__comments,
      sym__statements,
    STATE(30), 5,
      sym__statement,
      sym_component,
      sym_declaration,
      sym_assignment,
      aux_sym__statements_repeat1,
  [371] = 7,
    ACTIONS(45), 1,
      anon_sym_LPAREN,
    ACTIONS(47), 1,
      anon_sym_not,
    ACTIONS(49), 1,
      sym_identifier,
    ACTIONS(76), 1,
      sym_number,
    STATE(98), 2,
      sym__assignment_right,
      sym_assignment_right_list,
    STATE(137), 2,
      sym__expression_component_reference,
      sym_component_reference,
    STATE(34), 8,
      sym__expression,
      sym__expression_primary,
      sym__signal_reference,
      sym_reference,
      sym_expression_component,
      sym_expression_unary,
      sym_expression_binary,
      sym__atomic,
  [402] = 7,
    ACTIONS(57), 1,
      anon_sym_LPAREN,
    ACTIONS(59), 1,
      anon_sym_not,
    ACTIONS(61), 1,
      sym_identifier,
    ACTIONS(78), 1,
      sym_number,
    STATE(91), 2,
      sym__declaration_right,
      sym_declaration_right_list,
    STATE(149), 2,
      sym__expression_component_reference,
      sym_component_reference,
    STATE(41), 8,
      sym__expression,
      sym__expression_primary,
      sym__signal_reference,
      sym_reference,
      sym_expression_component,
      sym_expression_unary,
      sym_expression_binary,
      sym__atomic,
  [433] = 6,
    ACTIONS(57), 1,
      anon_sym_LPAREN,
    ACTIONS(59), 1,
      anon_sym_not,
    ACTIONS(61), 1,
      sym_identifier,
    ACTIONS(80), 1,
      sym_number,
    STATE(149), 2,
      sym__expression_component_reference,
      sym_component_reference,
    STATE(48), 8,
      sym__expression,
      sym__expression_primary,
      sym__signal_reference,
      sym_reference,
      sym_expression_component,
      sym_expression_unary,
      sym_expression_binary,
      sym__atomic,
  [460] = 6,
    ACTIONS(37), 1,
      anon_sym_LPAREN,
    ACTIONS(39), 1,
      anon_sym_not,
    ACTIONS(41), 1,
      sym_identifier,
    ACTIONS(82), 1,
      sym_number,
    STATE(147), 2,
      sym__expression_component_reference,
      sym_component_reference,
    STATE(110), 8,
      sym__expression,
      sym__expression_primary,
      sym__signal_reference,
      sym_reference,
      sym_expression_component,
      sym_expression_unary,
      sym_expression_binary,
      sym__atomic,
  [487] = 6,
    ACTIONS(37), 1,
      anon_sym_LPAREN,
    ACTIONS(39), 1,
      anon_sym_not,
    ACTIONS(41), 1,
      sym_identifier,
    ACTIONS(84), 1,
      sym_number,
    STATE(147), 2,
      sym__expression_component_reference,
      sym_component_reference,
    STATE(119), 8,
      sym__expression,
      sym__expression_primary,
      sym__signal_reference,
      sym_reference,
      sym_expression_component,
      sym_expression_unary,
      sym_expression_binary,
      sym__atomic,
  [514] = 6,
    ACTIONS(37), 1,
      anon_sym_LPAREN,
    ACTIONS(39), 1,
      anon_sym_not,
    ACTIONS(41), 1,
      sym_identifier,
    ACTIONS(86), 1,
      sym_number,
    STATE(147), 2,
      sym__expression_component_reference,
      sym_component_reference,
    STATE(104), 8,
      sym__expression,
      sym__expression_primary,
      sym__signal_reference,
      sym_reference,
      sym_expression_component,
      sym_expression_unary,
      sym_expression_binary,
      sym__atomic,
  [541] = 6,
    ACTIONS(37), 1,
      anon_sym_LPAREN,
    ACTIONS(39), 1,
      anon_sym_not,
    ACTIONS(41), 1,
      sym_identifier,
    ACTIONS(88), 1,
      sym_number,
    STATE(147), 2,
      sym__expression_component_reference,
      sym_component_reference,
    STATE(103), 8,
      sym__expression,
      sym__expression_primary,
      sym__signal_reference,
      sym_reference,
      sym_expression_component,
      sym_expression_unary,
      sym_expression_binary,
      sym__atomic,
  [568] = 6,
    ACTIONS(37), 1,
      anon_sym_LPAREN,
    ACTIONS(39), 1,
      anon_sym_not,
    ACTIONS(41), 1,
      sym_identifier,
    ACTIONS(90), 1,
      sym_number,
    STATE(147), 2,
      sym__expression_component_reference,
      sym_component_reference,
    STATE(123), 8,
      sym__expression,
      sym__expression_primary,
      sym__signal_reference,
      sym_reference,
      sym_expression_component,
      sym_expression_unary,
      sym_expression_binary,
      sym__atomic,
  [595] = 6,
    ACTIONS(45), 1,
      anon_sym_LPAREN,
    ACTIONS(47), 1,
      anon_sym_not,
    ACTIONS(49), 1,
      sym_identifier,
    ACTIONS(92), 1,
      sym_number,
    STATE(137), 2,
      sym__expression_component_reference,
      sym_component_reference,
    STATE(60), 8,
      sym__expression,
      sym__expression_primary,
      sym__signal_reference,
      sym_reference,
      sym_expression_component,
      sym_expression_unary,
      sym_expression_binary,
      sym__atomic,
  [622] = 6,
    ACTIONS(37), 1,
      anon_sym_LPAREN,
    ACTIONS(39), 1,
      anon_sym_not,
    ACTIONS(41), 1,
      sym_identifier,
    ACTIONS(94), 1,
      sym_number,
    STATE(147), 2,
      sym__expression_component_reference,
      sym_component_reference,
    STATE(115), 8,
      sym__expression,
      sym__expression_primary,
      sym__signal_reference,
      sym_reference,
      sym_expression_component,
      sym_expression_unary,
      sym_expression_binary,
      sym__atomic,
  [649] = 6,
    ACTIONS(45), 1,
      anon_sym_LPAREN,
    ACTIONS(47), 1,
      anon_sym_not,
    ACTIONS(49), 1,
      sym_identifier,
    ACTIONS(96), 1,
      sym_number,
    STATE(137), 2,
      sym__expression_component_reference,
      sym_component_reference,
    STATE(57), 8,
      sym__expression,
      sym__expression_primary,
      sym__signal_reference,
      sym_reference,
      sym_expression_component,
      sym_expression_unary,
      sym_expression_binary,
      sym__atomic,
  [676] = 6,
    ACTIONS(45), 1,
      anon_sym_LPAREN,
    ACTIONS(47), 1,
      anon_sym_not,
    ACTIONS(49), 1,
      sym_identifier,
    ACTIONS(98), 1,
      sym_number,
    STATE(137), 2,
      sym__expression_component_reference,
      sym_component_reference,
    STATE(59), 8,
      sym__expression,
      sym__expression_primary,
      sym__signal_reference,
      sym_reference,
      sym_expression_component,
      sym_expression_unary,
      sym_expression_binary,
      sym__atomic,
  [703] = 6,
    ACTIONS(57), 1,
      anon_sym_LPAREN,
    ACTIONS(59), 1,
      anon_sym_not,
    ACTIONS(61), 1,
      sym_identifier,
    ACTIONS(100), 1,
      sym_number,
    STATE(149), 2,
      sym__expression_component_reference,
      sym_component_reference,
    STATE(52), 8,
      sym__expression,
      sym__expression_primary,
      sym__signal_reference,
      sym_reference,
      sym_expression_component,
      sym_expression_unary,
      sym_expression_binary,
      sym__atomic,
  [730] = 6,
    ACTIONS(57), 1,
      anon_sym_LPAREN,
    ACTIONS(59), 1,
      anon_sym_not,
    ACTIONS(61), 1,
      sym_identifier,
    ACTIONS(102), 1,
      sym_number,
    STATE(149), 2,
      sym__expression_component_reference,
      sym_component_reference,
    STATE(58), 8,
      sym__expression,
      sym__expression_primary,
      sym__signal_reference,
      sym_reference,
      sym_expression_component,
      sym_expression_unary,
      sym_expression_binary,
      sym__atomic,
  [757] = 7,
    ACTIONS(104), 1,
      sym_comment,
    ACTIONS(106), 1,
      anon_sym_component,
    ACTIONS(109), 1,
      anon_sym_end,
    ACTIONS(111), 1,
      anon_sym_signal,
    ACTIONS(114), 1,
      sym_identifier,
    STATE(141), 2,
      sym__assignment_left,
      sym_assignment_left_list,
    STATE(27), 5,
      sym__statement,
      sym_component,
      sym_declaration,
      sym_assignment,
      aux_sym__statements_repeat1,
  [784] = 6,
    ACTIONS(114), 1,
      sym_identifier,
    ACTIONS(117), 1,
      anon_sym_component,
    ACTIONS(120), 1,
      anon_sym_signal,
    ACTIONS(104), 2,
      ts_builtin_sym_end,
      sym_comment,
    STATE(142), 2,
      sym__assignment_left,
      sym_assignment_left_list,
    STATE(28), 5,
      sym__statement,
      sym_component,
      sym_declaration,
      sym_assignment,
      aux_sym__statements_repeat1,
  [809] = 6,
    ACTIONS(7), 1,
      anon_sym_component,
    ACTIONS(9), 1,
      anon_sym_signal,
    ACTIONS(11), 1,
      sym_identifier,
    ACTIONS(123), 2,
      ts_builtin_sym_end,
      sym_comment,
    STATE(142), 2,
      sym__assignment_left,
      sym_assignment_left_list,
    STATE(28), 5,
      sym__statement,
      sym_component,
      sym_declaration,
      sym_assignment,
      aux_sym__statements_repeat1,
  [834] = 7,
    ACTIONS(11), 1,
      sym_identifier,
    ACTIONS(15), 1,
      anon_sym_component,
    ACTIONS(19), 1,
      anon_sym_signal,
    ACTIONS(123), 1,
      sym_comment,
    ACTIONS(125), 1,
      anon_sym_end,
    STATE(141), 2,
      sym__assignment_left,
      sym_assignment_left_list,
    STATE(27), 5,
      sym__statement,
      sym_component,
      sym_declaration,
      sym_assignment,
      aux_sym__statements_repeat1,
  [861] = 5,
    ACTIONS(131), 1,
      anon_sym_LPAREN,
    ACTIONS(133), 1,
      anon_sym_DOT,
    STATE(111), 1,
      aux_sym_component_reference_repeat1,
    ACTIONS(127), 2,
      sym_comment,
      anon_sym_COMMA,
    ACTIONS(129), 6,
      anon_sym_component,
      anon_sym_end,
      anon_sym_signal,
      anon_sym_and,
      anon_sym_or,
      sym_identifier,
  [883] = 5,
    ACTIONS(131), 1,
      anon_sym_LPAREN,
    ACTIONS(135), 1,
      anon_sym_DOT,
    STATE(111), 1,
      aux_sym_component_reference_repeat1,
    ACTIONS(127), 3,
      ts_builtin_sym_end,
      sym_comment,
      anon_sym_COMMA,
    ACTIONS(129), 5,
      anon_sym_component,
      anon_sym_signal,
      anon_sym_and,
      anon_sym_or,
      sym_identifier,
  [905] = 3,
    ACTIONS(141), 1,
      anon_sym_COLON,
    ACTIONS(137), 3,
      ts_builtin_sym_end,
      sym_comment,
      anon_sym_COMMA,
    ACTIONS(139), 5,
      anon_sym_component,
      anon_sym_signal,
      anon_sym_and,
      anon_sym_or,
      sym_identifier,
  [921] = 5,
    ACTIONS(147), 1,
      anon_sym_COMMA,
    STATE(74), 1,
      aux_sym_declaration_right_list_repeat1,
    ACTIONS(143), 2,
      ts_builtin_sym_end,
      sym_comment,
    ACTIONS(149), 2,
      anon_sym_and,
      anon_sym_or,
    ACTIONS(145), 3,
      anon_sym_component,
      anon_sym_signal,
      sym_identifier,
  [941] = 4,
    ACTIONS(151), 1,
      anon_sym_COLON,
    ACTIONS(153), 1,
      sym_identifier,
    ACTIONS(155), 1,
      sym_number,
    STATE(106), 6,
      sym__subscript,
      sym__index,
      sym__range,
      sym_range_closed,
      sym_range_open_left,
      sym_range_open_right,
  [959] = 3,
    ACTIONS(157), 1,
      anon_sym_COLON,
    ACTIONS(137), 2,
      sym_comment,
      anon_sym_COMMA,
    ACTIONS(139), 6,
      anon_sym_component,
      anon_sym_end,
      anon_sym_signal,
      anon_sym_and,
      anon_sym_or,
      sym_identifier,
  [975] = 3,
    ACTIONS(163), 1,
      sym_number,
    ACTIONS(159), 3,
      ts_builtin_sym_end,
      sym_comment,
      anon_sym_COMMA,
    ACTIONS(161), 5,
      anon_sym_component,
      anon_sym_signal,
      anon_sym_and,
      anon_sym_or,
      sym_identifier,
  [991] = 5,
    ACTIONS(147), 1,
      anon_sym_COMMA,
    STATE(82), 1,
      aux_sym_declaration_right_list_repeat1,
    ACTIONS(149), 2,
      anon_sym_and,
      anon_sym_or,
    ACTIONS(165), 2,
      ts_builtin_sym_end,
      sym_comment,
    ACTIONS(167), 3,
      anon_sym_component,
      anon_sym_signal,
      sym_identifier,
  [1011] = 4,
    ACTIONS(153), 1,
      sym_identifier,
    ACTIONS(169), 1,
      anon_sym_COLON,
    ACTIONS(171), 1,
      sym_number,
    STATE(53), 6,
      sym__subscript,
      sym__index,
      sym__range,
      sym_range_closed,
      sym_range_open_left,
      sym_range_open_right,
  [1029] = 5,
    ACTIONS(143), 1,
      sym_comment,
    ACTIONS(173), 1,
      anon_sym_COMMA,
    STATE(76), 1,
      aux_sym_declaration_right_list_repeat1,
    ACTIONS(175), 2,
      anon_sym_and,
      anon_sym_or,
    ACTIONS(145), 4,
      anon_sym_component,
      anon_sym_end,
      anon_sym_signal,
      sym_identifier,
  [1049] = 5,
    ACTIONS(165), 1,
      sym_comment,
    ACTIONS(173), 1,
      anon_sym_COMMA,
    STATE(75), 1,
      aux_sym_declaration_right_list_repeat1,
    ACTIONS(175), 2,
      anon_sym_and,
      anon_sym_or,
    ACTIONS(167), 4,
      anon_sym_component,
      anon_sym_end,
      anon_sym_signal,
      sym_identifier,
  [1069] = 3,
    ACTIONS(177), 1,
      sym_number,
    ACTIONS(159), 2,
      sym_comment,
      anon_sym_COMMA,
    ACTIONS(161), 6,
      anon_sym_component,
      anon_sym_end,
      anon_sym_signal,
      anon_sym_and,
      anon_sym_or,
      sym_identifier,
  [1085] = 4,
    ACTIONS(153), 1,
      sym_identifier,
    ACTIONS(179), 1,
      anon_sym_COLON,
    ACTIONS(181), 1,
      sym_number,
    STATE(56), 6,
      sym__subscript,
      sym__index,
      sym__range,
      sym_range_closed,
      sym_range_open_left,
      sym_range_open_right,
  [1103] = 4,
    ACTIONS(187), 1,
      anon_sym_COMMA,
    STATE(44), 1,
      aux_sym_assignment_left_list_repeat1,
    ACTIONS(183), 3,
      sym_comment,
      anon_sym_RPAREN,
      anon_sym_LT_EQ,
    ACTIONS(185), 4,
      anon_sym_component,
      anon_sym_end,
      anon_sym_signal,
      sym_identifier,
  [1121] = 2,
    ACTIONS(190), 3,
      ts_builtin_sym_end,
      sym_comment,
      anon_sym_COMMA,
    ACTIONS(192), 5,
      anon_sym_component,
      anon_sym_signal,
      anon_sym_and,
      anon_sym_or,
      sym_identifier,
  [1134] = 4,
    ACTIONS(198), 1,
      anon_sym_COMMA,
    STATE(49), 1,
      aux_sym_assignment_left_list_repeat1,
    ACTIONS(194), 2,
      sym_comment,
      anon_sym_RPAREN,
    ACTIONS(196), 4,
      anon_sym_component,
      anon_sym_end,
      anon_sym_signal,
      sym_identifier,
  [1151] = 2,
    ACTIONS(200), 2,
      sym_comment,
      anon_sym_COMMA,
    ACTIONS(202), 6,
      anon_sym_component,
      anon_sym_end,
      anon_sym_signal,
      anon_sym_and,
      anon_sym_or,
      sym_identifier,
  [1164] = 2,
    ACTIONS(204), 2,
      sym_comment,
      anon_sym_COMMA,
    ACTIONS(206), 6,
      anon_sym_component,
      anon_sym_end,
      anon_sym_signal,
      anon_sym_and,
      anon_sym_or,
      sym_identifier,
  [1177] = 4,
    ACTIONS(198), 1,
      anon_sym_COMMA,
    STATE(44), 1,
      aux_sym_assignment_left_list_repeat1,
    ACTIONS(208), 2,
      sym_comment,
      anon_sym_RPAREN,
    ACTIONS(210), 4,
      anon_sym_component,
      anon_sym_end,
      anon_sym_signal,
      sym_identifier,
  [1194] = 2,
    ACTIONS(183), 4,
      sym_comment,
      anon_sym_RPAREN,
      anon_sym_LT_EQ,
      anon_sym_COMMA,
    ACTIONS(185), 4,
      anon_sym_component,
      anon_sym_end,
      anon_sym_signal,
      sym_identifier,
  [1207] = 4,
    ACTIONS(216), 1,
      anon_sym_COMMA,
    STATE(66), 1,
      aux_sym_declaration_left_list_repeat1,
    ACTIONS(212), 3,
      ts_builtin_sym_end,
      sym_comment,
      anon_sym_LT_EQ,
    ACTIONS(214), 3,
      anon_sym_component,
      anon_sym_signal,
      sym_identifier,
  [1224] = 3,
    ACTIONS(175), 2,
      anon_sym_and,
      anon_sym_or,
    ACTIONS(218), 2,
      sym_comment,
      anon_sym_COMMA,
    ACTIONS(220), 4,
      anon_sym_component,
      anon_sym_end,
      anon_sym_signal,
      sym_identifier,
  [1239] = 2,
    ACTIONS(222), 2,
      sym_comment,
      anon_sym_COMMA,
    ACTIONS(224), 6,
      anon_sym_component,
      anon_sym_end,
      anon_sym_signal,
      anon_sym_and,
      anon_sym_or,
      sym_identifier,
  [1252] = 4,
    ACTIONS(230), 1,
      anon_sym_COMMA,
    STATE(54), 1,
      aux_sym_declaration_left_list_repeat1,
    ACTIONS(226), 2,
      sym_comment,
      anon_sym_LT_EQ,
    ACTIONS(228), 4,
      anon_sym_component,
      anon_sym_end,
      anon_sym_signal,
      sym_identifier,
  [1269] = 2,
    ACTIONS(233), 2,
      sym_comment,
      anon_sym_COMMA,
    ACTIONS(235), 6,
      anon_sym_component,
      anon_sym_end,
      anon_sym_signal,
      anon_sym_and,
      anon_sym_or,
      sym_identifier,
  [1282] = 2,
    ACTIONS(222), 3,
      ts_builtin_sym_end,
      sym_comment,
      anon_sym_COMMA,
    ACTIONS(224), 5,
      anon_sym_component,
      anon_sym_signal,
      anon_sym_and,
      anon_sym_or,
      sym_identifier,
  [1295] = 2,
    ACTIONS(204), 3,
      ts_builtin_sym_end,
      sym_comment,
      anon_sym_COMMA,
    ACTIONS(206), 5,
      anon_sym_component,
      anon_sym_signal,
      anon_sym_and,
      anon_sym_or,
      sym_identifier,
  [1308] = 2,
    ACTIONS(237), 2,
      sym_comment,
      anon_sym_COMMA,
    ACTIONS(239), 6,
      anon_sym_component,
      anon_sym_end,
      anon_sym_signal,
      anon_sym_and,
      anon_sym_or,
      sym_identifier,
  [1321] = 3,
    ACTIONS(149), 2,
      anon_sym_and,
      anon_sym_or,
    ACTIONS(218), 3,
      ts_builtin_sym_end,
      sym_comment,
      anon_sym_COMMA,
    ACTIONS(220), 3,
      anon_sym_component,
      anon_sym_signal,
      sym_identifier,
  [1336] = 2,
    ACTIONS(237), 3,
      ts_builtin_sym_end,
      sym_comment,
      anon_sym_COMMA,
    ACTIONS(239), 5,
      anon_sym_component,
      anon_sym_signal,
      anon_sym_and,
      anon_sym_or,
      sym_identifier,
  [1349] = 4,
    ACTIONS(241), 1,
      anon_sym_COMMA,
    STATE(54), 1,
      aux_sym_declaration_left_list_repeat1,
    ACTIONS(212), 2,
      sym_comment,
      anon_sym_LT_EQ,
    ACTIONS(214), 4,
      anon_sym_component,
      anon_sym_end,
      anon_sym_signal,
      sym_identifier,
  [1366] = 2,
    ACTIONS(243), 2,
      sym_comment,
      anon_sym_COMMA,
    ACTIONS(245), 6,
      anon_sym_component,
      anon_sym_end,
      anon_sym_signal,
      anon_sym_and,
      anon_sym_or,
      sym_identifier,
  [1379] = 4,
    ACTIONS(216), 1,
      anon_sym_COMMA,
    STATE(51), 1,
      aux_sym_declaration_left_list_repeat1,
    ACTIONS(247), 3,
      ts_builtin_sym_end,
      sym_comment,
      anon_sym_LT_EQ,
    ACTIONS(249), 3,
      anon_sym_component,
      anon_sym_signal,
      sym_identifier,
  [1396] = 4,
    ACTIONS(241), 1,
      anon_sym_COMMA,
    STATE(61), 1,
      aux_sym_declaration_left_list_repeat1,
    ACTIONS(247), 2,
      sym_comment,
      anon_sym_LT_EQ,
    ACTIONS(249), 4,
      anon_sym_component,
      anon_sym_end,
      anon_sym_signal,
      sym_identifier,
  [1413] = 2,
    ACTIONS(200), 3,
      ts_builtin_sym_end,
      sym_comment,
      anon_sym_COMMA,
    ACTIONS(202), 5,
      anon_sym_component,
      anon_sym_signal,
      anon_sym_and,
      anon_sym_or,
      sym_identifier,
  [1426] = 4,
    ACTIONS(251), 1,
      anon_sym_COMMA,
    STATE(66), 1,
      aux_sym_declaration_left_list_repeat1,
    ACTIONS(226), 3,
      ts_builtin_sym_end,
      sym_comment,
      anon_sym_LT_EQ,
    ACTIONS(228), 3,
      anon_sym_component,
      anon_sym_signal,
      sym_identifier,
  [1443] = 3,
    ACTIONS(258), 1,
      anon_sym_COLON,
    ACTIONS(254), 3,
      sym_comment,
      anon_sym_LT_EQ,
      anon_sym_COMMA,
    ACTIONS(256), 4,
      anon_sym_component,
      anon_sym_end,
      anon_sym_signal,
      sym_identifier,
  [1458] = 2,
    ACTIONS(233), 3,
      ts_builtin_sym_end,
      sym_comment,
      anon_sym_COMMA,
    ACTIONS(235), 5,
      anon_sym_component,
      anon_sym_signal,
      anon_sym_and,
      anon_sym_or,
      sym_identifier,
  [1471] = 2,
    ACTIONS(190), 2,
      sym_comment,
      anon_sym_COMMA,
    ACTIONS(192), 6,
      anon_sym_component,
      anon_sym_end,
      anon_sym_signal,
      anon_sym_and,
      anon_sym_or,
      sym_identifier,
  [1484] = 3,
    ACTIONS(260), 1,
      anon_sym_COLON,
    ACTIONS(256), 3,
      anon_sym_component,
      anon_sym_signal,
      sym_identifier,
    ACTIONS(254), 4,
      ts_builtin_sym_end,
      sym_comment,
      anon_sym_LT_EQ,
      anon_sym_COMMA,
  [1499] = 2,
    ACTIONS(243), 3,
      ts_builtin_sym_end,
      sym_comment,
      anon_sym_COMMA,
    ACTIONS(245), 5,
      anon_sym_component,
      anon_sym_signal,
      anon_sym_and,
      anon_sym_or,
      sym_identifier,
  [1512] = 2,
    ACTIONS(228), 3,
      anon_sym_component,
      anon_sym_signal,
      sym_identifier,
    ACTIONS(226), 4,
      ts_builtin_sym_end,
      sym_comment,
      anon_sym_LT_EQ,
      anon_sym_COMMA,
  [1524] = 4,
    ACTIONS(262), 1,
      anon_sym_COMMA,
    STATE(73), 1,
      aux_sym_declaration_right_list_repeat1,
    ACTIONS(218), 2,
      ts_builtin_sym_end,
      sym_comment,
    ACTIONS(220), 3,
      anon_sym_component,
      anon_sym_signal,
      sym_identifier,
  [1540] = 4,
    ACTIONS(147), 1,
      anon_sym_COMMA,
    STATE(73), 1,
      aux_sym_declaration_right_list_repeat1,
    ACTIONS(265), 2,
      ts_builtin_sym_end,
      sym_comment,
    ACTIONS(267), 3,
      anon_sym_component,
      anon_sym_signal,
      sym_identifier,
  [1556] = 4,
    ACTIONS(173), 1,
      anon_sym_COMMA,
    ACTIONS(269), 1,
      sym_comment,
    STATE(79), 1,
      aux_sym_declaration_right_list_repeat1,
    ACTIONS(271), 4,
      anon_sym_component,
      anon_sym_end,
      anon_sym_signal,
      sym_identifier,
  [1572] = 4,
    ACTIONS(173), 1,
      anon_sym_COMMA,
    ACTIONS(265), 1,
      sym_comment,
    STATE(79), 1,
      aux_sym_declaration_right_list_repeat1,
    ACTIONS(267), 4,
      anon_sym_component,
      anon_sym_end,
      anon_sym_signal,
      sym_identifier,
  [1588] = 2,
    ACTIONS(275), 3,
      anon_sym_component,
      anon_sym_signal,
      sym_identifier,
    ACTIONS(273), 4,
      ts_builtin_sym_end,
      sym_comment,
      anon_sym_LT_EQ,
      anon_sym_COMMA,
  [1600] = 2,
    ACTIONS(226), 3,
      sym_comment,
      anon_sym_LT_EQ,
      anon_sym_COMMA,
    ACTIONS(228), 4,
      anon_sym_component,
      anon_sym_end,
      anon_sym_signal,
      sym_identifier,
  [1612] = 4,
    ACTIONS(218), 1,
      sym_comment,
    ACTIONS(277), 1,
      anon_sym_COMMA,
    STATE(79), 1,
      aux_sym_declaration_right_list_repeat1,
    ACTIONS(220), 4,
      anon_sym_component,
      anon_sym_end,
      anon_sym_signal,
      sym_identifier,
  [1628] = 2,
    ACTIONS(273), 3,
      sym_comment,
      anon_sym_LT_EQ,
      anon_sym_COMMA,
    ACTIONS(275), 4,
      anon_sym_component,
      anon_sym_end,
      anon_sym_signal,
      sym_identifier,
  [1640] = 4,
    ACTIONS(131), 1,
      anon_sym_LPAREN,
    ACTIONS(280), 1,
      anon_sym_DOT,
    STATE(111), 1,
      aux_sym_component_reference_repeat1,
    ACTIONS(127), 4,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_and,
      anon_sym_or,
  [1656] = 4,
    ACTIONS(147), 1,
      anon_sym_COMMA,
    STATE(73), 1,
      aux_sym_declaration_right_list_repeat1,
    ACTIONS(269), 2,
      ts_builtin_sym_end,
      sym_comment,
    ACTIONS(271), 3,
      anon_sym_component,
      anon_sym_signal,
      sym_identifier,
  [1672] = 3,
    ACTIONS(282), 1,
      sym_comment,
    STATE(83), 1,
      aux_sym__comments_repeat1,
    ACTIONS(285), 4,
      anon_sym_component,
      anon_sym_end,
      anon_sym_signal,
      sym_identifier,
  [1685] = 3,
    ACTIONS(291), 1,
      anon_sym_LT_EQ,
    ACTIONS(287), 2,
      ts_builtin_sym_end,
      sym_comment,
    ACTIONS(289), 3,
      anon_sym_component,
      anon_sym_signal,
      sym_identifier,
  [1698] = 3,
    ACTIONS(293), 1,
      sym_comment,
    STATE(83), 1,
      aux_sym__comments_repeat1,
    ACTIONS(295), 4,
      anon_sym_component,
      anon_sym_end,
      anon_sym_signal,
      sym_identifier,
  [1711] = 4,
    ACTIONS(297), 1,
      ts_builtin_sym_end,
    ACTIONS(299), 1,
      sym_comment,
    STATE(87), 1,
      aux_sym__comments_repeat1,
    ACTIONS(295), 3,
      anon_sym_component,
      anon_sym_signal,
      sym_identifier,
  [1726] = 4,
    ACTIONS(301), 1,
      ts_builtin_sym_end,
    ACTIONS(303), 1,
      sym_comment,
    STATE(87), 1,
      aux_sym__comments_repeat1,
    ACTIONS(285), 3,
      anon_sym_component,
      anon_sym_signal,
      sym_identifier,
  [1741] = 3,
    ACTIONS(287), 1,
      sym_comment,
    ACTIONS(306), 1,
      anon_sym_LT_EQ,
    ACTIONS(289), 4,
      anon_sym_component,
      anon_sym_end,
      anon_sym_signal,
      sym_identifier,
  [1754] = 2,
    ACTIONS(308), 2,
      ts_builtin_sym_end,
      sym_comment,
    ACTIONS(310), 3,
      anon_sym_component,
      anon_sym_signal,
      sym_identifier,
  [1764] = 2,
    ACTIONS(312), 1,
      anon_sym_COLON,
    ACTIONS(137), 4,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_and,
      anon_sym_or,
  [1774] = 2,
    ACTIONS(314), 1,
      sym_comment,
    ACTIONS(316), 4,
      anon_sym_component,
      anon_sym_end,
      anon_sym_signal,
      sym_identifier,
  [1784] = 3,
    ACTIONS(318), 1,
      sym_identifier,
    STATE(64), 2,
      sym__declarator,
      sym_declarator_subscript,
    STATE(88), 2,
      sym__declaration_left,
      sym_declaration_left_list,
  [1796] = 2,
    ACTIONS(320), 1,
      sym_comment,
    ACTIONS(322), 4,
      anon_sym_component,
      anon_sym_end,
      anon_sym_signal,
      sym_identifier,
  [1806] = 2,
    ACTIONS(324), 1,
      sym_comment,
    ACTIONS(326), 4,
      anon_sym_component,
      anon_sym_end,
      anon_sym_signal,
      sym_identifier,
  [1816] = 2,
    ACTIONS(314), 2,
      ts_builtin_sym_end,
      sym_comment,
    ACTIONS(316), 3,
      anon_sym_component,
      anon_sym_signal,
      sym_identifier,
  [1826] = 2,
    ACTIONS(328), 1,
      sym_comment,
    ACTIONS(330), 4,
      anon_sym_component,
      anon_sym_end,
      anon_sym_signal,
      sym_identifier,
  [1836] = 4,
    ACTIONS(332), 1,
      anon_sym_RPAREN,
    ACTIONS(334), 1,
      anon_sym_COMMA,
    STATE(118), 1,
      aux_sym_declaration_right_list_repeat1,
    ACTIONS(336), 2,
      anon_sym_and,
      anon_sym_or,
  [1850] = 2,
    ACTIONS(328), 2,
      ts_builtin_sym_end,
      sym_comment,
    ACTIONS(330), 3,
      anon_sym_component,
      anon_sym_signal,
      sym_identifier,
  [1860] = 2,
    ACTIONS(308), 1,
      sym_comment,
    ACTIONS(310), 4,
      anon_sym_component,
      anon_sym_end,
      anon_sym_signal,
      sym_identifier,
  [1870] = 3,
    ACTIONS(338), 1,
      sym_identifier,
    STATE(63), 2,
      sym__declarator,
      sym_declarator_subscript,
    STATE(84), 2,
      sym__declaration_left,
      sym_declaration_left_list,
  [1882] = 2,
    ACTIONS(340), 1,
      sym_number,
    ACTIONS(159), 4,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_and,
      anon_sym_or,
  [1892] = 2,
    ACTIONS(324), 2,
      ts_builtin_sym_end,
      sym_comment,
    ACTIONS(326), 3,
      anon_sym_component,
      anon_sym_signal,
      sym_identifier,
  [1902] = 1,
    ACTIONS(237), 4,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_and,
      anon_sym_or,
  [1909] = 2,
    ACTIONS(218), 2,
      anon_sym_RPAREN,
      anon_sym_COMMA,
    ACTIONS(336), 2,
      anon_sym_and,
      anon_sym_or,
  [1918] = 1,
    ACTIONS(200), 4,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_and,
      anon_sym_or,
  [1925] = 1,
    ACTIONS(222), 4,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_and,
      anon_sym_or,
  [1932] = 1,
    ACTIONS(233), 4,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_and,
      anon_sym_or,
  [1939] = 1,
    ACTIONS(243), 4,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_and,
      anon_sym_or,
  [1946] = 1,
    ACTIONS(190), 4,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_and,
      anon_sym_or,
  [1953] = 1,
    ACTIONS(204), 4,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_and,
      anon_sym_or,
  [1960] = 3,
    ACTIONS(342), 1,
      anon_sym_LPAREN,
    ACTIONS(344), 1,
      anon_sym_DOT,
    STATE(121), 1,
      aux_sym_component_reference_repeat1,
  [1970] = 3,
    ACTIONS(198), 1,
      anon_sym_COMMA,
    ACTIONS(346), 1,
      anon_sym_LT_EQ,
    STATE(44), 1,
      aux_sym_assignment_left_list_repeat1,
  [1980] = 3,
    ACTIONS(348), 1,
      sym_identifier,
    STATE(145), 1,
      sym__identifiers,
    STATE(150), 1,
      sym_component_inputs,
  [1990] = 3,
    ACTIONS(218), 1,
      anon_sym_RPAREN,
    ACTIONS(350), 1,
      anon_sym_COMMA,
    STATE(114), 1,
      aux_sym_declaration_right_list_repeat1,
  [2000] = 2,
    ACTIONS(353), 1,
      anon_sym_RPAREN,
    ACTIONS(336), 2,
      anon_sym_and,
      anon_sym_or,
  [2008] = 3,
    ACTIONS(198), 1,
      anon_sym_COMMA,
    ACTIONS(355), 1,
      anon_sym_LT_EQ,
    STATE(112), 1,
      aux_sym_assignment_left_list_repeat1,
  [2018] = 3,
    ACTIONS(348), 1,
      sym_identifier,
    STATE(2), 1,
      sym_component_outputs,
    STATE(93), 1,
      sym__identifiers,
  [2028] = 3,
    ACTIONS(334), 1,
      anon_sym_COMMA,
    ACTIONS(357), 1,
      anon_sym_RPAREN,
    STATE(114), 1,
      aux_sym_declaration_right_list_repeat1,
  [2038] = 2,
    ACTIONS(359), 1,
      anon_sym_RPAREN,
    ACTIONS(336), 2,
      anon_sym_and,
      anon_sym_or,
  [2046] = 3,
    ACTIONS(348), 1,
      sym_identifier,
    STATE(3), 1,
      sym_component_outputs,
    STATE(93), 1,
      sym__identifiers,
  [2056] = 3,
    ACTIONS(361), 1,
      anon_sym_LPAREN,
    ACTIONS(363), 1,
      anon_sym_DOT,
    STATE(121), 1,
      aux_sym_component_reference_repeat1,
  [2066] = 2,
    ACTIONS(338), 1,
      sym_identifier,
    STATE(72), 2,
      sym__declarator,
      sym_declarator_subscript,
  [2074] = 2,
    ACTIONS(366), 1,
      anon_sym_RPAREN,
    ACTIONS(336), 2,
      anon_sym_and,
      anon_sym_or,
  [2082] = 2,
    ACTIONS(318), 1,
      sym_identifier,
    STATE(78), 2,
      sym__declarator,
      sym_declarator_subscript,
  [2090] = 3,
    ACTIONS(348), 1,
      sym_identifier,
    STATE(144), 1,
      sym_component_inputs,
    STATE(145), 1,
      sym__identifiers,
  [2100] = 1,
    ACTIONS(361), 2,
      anon_sym_LPAREN,
      anon_sym_DOT,
  [2105] = 1,
    ACTIONS(368), 1,
      sym_number,
  [2109] = 1,
    ACTIONS(370), 1,
      anon_sym_RPAREN,
  [2113] = 1,
    ACTIONS(372), 1,
      sym_number,
  [2117] = 1,
    ACTIONS(374), 1,
      anon_sym_RPAREN,
  [2121] = 1,
    ACTIONS(376), 1,
      sym_identifier,
  [2125] = 1,
    ACTIONS(378), 1,
      anon_sym_EQ_GT,
  [2129] = 1,
    ACTIONS(380), 1,
      anon_sym_RPAREN,
  [2133] = 1,
    ACTIONS(382), 1,
      anon_sym_end,
  [2137] = 1,
    ACTIONS(384), 1,
      anon_sym_end,
  [2141] = 1,
    ACTIONS(386), 1,
      anon_sym_LPAREN,
  [2145] = 1,
    ACTIONS(388), 1,
      anon_sym_LPAREN,
  [2149] = 1,
    ACTIONS(153), 1,
      sym_identifier,
  [2153] = 1,
    ACTIONS(390), 1,
      sym_number,
  [2157] = 1,
    ACTIONS(392), 1,
      sym_number,
  [2161] = 1,
    ACTIONS(394), 1,
      anon_sym_LT_EQ,
  [2165] = 1,
    ACTIONS(396), 1,
      anon_sym_LT_EQ,
  [2169] = 1,
    ACTIONS(398), 1,
      ts_builtin_sym_end,
  [2173] = 1,
    ACTIONS(400), 1,
      anon_sym_RPAREN,
  [2177] = 1,
    ACTIONS(402), 1,
      anon_sym_RPAREN,
  [2181] = 1,
    ACTIONS(404), 1,
      sym_identifier,
  [2185] = 1,
    ACTIONS(406), 1,
      anon_sym_LPAREN,
  [2189] = 1,
    ACTIONS(408), 1,
      anon_sym_EQ_GT,
  [2193] = 1,
    ACTIONS(410), 1,
      anon_sym_LPAREN,
  [2197] = 1,
    ACTIONS(412), 1,
      anon_sym_RPAREN,
  [2201] = 1,
    ACTIONS(414), 1,
      sym_number,
  [2205] = 1,
    ACTIONS(416), 1,
      anon_sym_LPAREN,
  [2209] = 1,
    ACTIONS(418), 1,
      sym_identifier,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 38,
  [SMALL_STATE(4)] = 76,
  [SMALL_STATE(5)] = 111,
  [SMALL_STATE(6)] = 142,
  [SMALL_STATE(7)] = 173,
  [SMALL_STATE(8)] = 204,
  [SMALL_STATE(9)] = 235,
  [SMALL_STATE(10)] = 270,
  [SMALL_STATE(11)] = 305,
  [SMALL_STATE(12)] = 336,
  [SMALL_STATE(13)] = 371,
  [SMALL_STATE(14)] = 402,
  [SMALL_STATE(15)] = 433,
  [SMALL_STATE(16)] = 460,
  [SMALL_STATE(17)] = 487,
  [SMALL_STATE(18)] = 514,
  [SMALL_STATE(19)] = 541,
  [SMALL_STATE(20)] = 568,
  [SMALL_STATE(21)] = 595,
  [SMALL_STATE(22)] = 622,
  [SMALL_STATE(23)] = 649,
  [SMALL_STATE(24)] = 676,
  [SMALL_STATE(25)] = 703,
  [SMALL_STATE(26)] = 730,
  [SMALL_STATE(27)] = 757,
  [SMALL_STATE(28)] = 784,
  [SMALL_STATE(29)] = 809,
  [SMALL_STATE(30)] = 834,
  [SMALL_STATE(31)] = 861,
  [SMALL_STATE(32)] = 883,
  [SMALL_STATE(33)] = 905,
  [SMALL_STATE(34)] = 921,
  [SMALL_STATE(35)] = 941,
  [SMALL_STATE(36)] = 959,
  [SMALL_STATE(37)] = 975,
  [SMALL_STATE(38)] = 991,
  [SMALL_STATE(39)] = 1011,
  [SMALL_STATE(40)] = 1029,
  [SMALL_STATE(41)] = 1049,
  [SMALL_STATE(42)] = 1069,
  [SMALL_STATE(43)] = 1085,
  [SMALL_STATE(44)] = 1103,
  [SMALL_STATE(45)] = 1121,
  [SMALL_STATE(46)] = 1134,
  [SMALL_STATE(47)] = 1151,
  [SMALL_STATE(48)] = 1164,
  [SMALL_STATE(49)] = 1177,
  [SMALL_STATE(50)] = 1194,
  [SMALL_STATE(51)] = 1207,
  [SMALL_STATE(52)] = 1224,
  [SMALL_STATE(53)] = 1239,
  [SMALL_STATE(54)] = 1252,
  [SMALL_STATE(55)] = 1269,
  [SMALL_STATE(56)] = 1282,
  [SMALL_STATE(57)] = 1295,
  [SMALL_STATE(58)] = 1308,
  [SMALL_STATE(59)] = 1321,
  [SMALL_STATE(60)] = 1336,
  [SMALL_STATE(61)] = 1349,
  [SMALL_STATE(62)] = 1366,
  [SMALL_STATE(63)] = 1379,
  [SMALL_STATE(64)] = 1396,
  [SMALL_STATE(65)] = 1413,
  [SMALL_STATE(66)] = 1426,
  [SMALL_STATE(67)] = 1443,
  [SMALL_STATE(68)] = 1458,
  [SMALL_STATE(69)] = 1471,
  [SMALL_STATE(70)] = 1484,
  [SMALL_STATE(71)] = 1499,
  [SMALL_STATE(72)] = 1512,
  [SMALL_STATE(73)] = 1524,
  [SMALL_STATE(74)] = 1540,
  [SMALL_STATE(75)] = 1556,
  [SMALL_STATE(76)] = 1572,
  [SMALL_STATE(77)] = 1588,
  [SMALL_STATE(78)] = 1600,
  [SMALL_STATE(79)] = 1612,
  [SMALL_STATE(80)] = 1628,
  [SMALL_STATE(81)] = 1640,
  [SMALL_STATE(82)] = 1656,
  [SMALL_STATE(83)] = 1672,
  [SMALL_STATE(84)] = 1685,
  [SMALL_STATE(85)] = 1698,
  [SMALL_STATE(86)] = 1711,
  [SMALL_STATE(87)] = 1726,
  [SMALL_STATE(88)] = 1741,
  [SMALL_STATE(89)] = 1754,
  [SMALL_STATE(90)] = 1764,
  [SMALL_STATE(91)] = 1774,
  [SMALL_STATE(92)] = 1784,
  [SMALL_STATE(93)] = 1796,
  [SMALL_STATE(94)] = 1806,
  [SMALL_STATE(95)] = 1816,
  [SMALL_STATE(96)] = 1826,
  [SMALL_STATE(97)] = 1836,
  [SMALL_STATE(98)] = 1850,
  [SMALL_STATE(99)] = 1860,
  [SMALL_STATE(100)] = 1870,
  [SMALL_STATE(101)] = 1882,
  [SMALL_STATE(102)] = 1892,
  [SMALL_STATE(103)] = 1902,
  [SMALL_STATE(104)] = 1909,
  [SMALL_STATE(105)] = 1918,
  [SMALL_STATE(106)] = 1925,
  [SMALL_STATE(107)] = 1932,
  [SMALL_STATE(108)] = 1939,
  [SMALL_STATE(109)] = 1946,
  [SMALL_STATE(110)] = 1953,
  [SMALL_STATE(111)] = 1960,
  [SMALL_STATE(112)] = 1970,
  [SMALL_STATE(113)] = 1980,
  [SMALL_STATE(114)] = 1990,
  [SMALL_STATE(115)] = 2000,
  [SMALL_STATE(116)] = 2008,
  [SMALL_STATE(117)] = 2018,
  [SMALL_STATE(118)] = 2028,
  [SMALL_STATE(119)] = 2038,
  [SMALL_STATE(120)] = 2046,
  [SMALL_STATE(121)] = 2056,
  [SMALL_STATE(122)] = 2066,
  [SMALL_STATE(123)] = 2074,
  [SMALL_STATE(124)] = 2082,
  [SMALL_STATE(125)] = 2090,
  [SMALL_STATE(126)] = 2100,
  [SMALL_STATE(127)] = 2105,
  [SMALL_STATE(128)] = 2109,
  [SMALL_STATE(129)] = 2113,
  [SMALL_STATE(130)] = 2117,
  [SMALL_STATE(131)] = 2121,
  [SMALL_STATE(132)] = 2125,
  [SMALL_STATE(133)] = 2129,
  [SMALL_STATE(134)] = 2133,
  [SMALL_STATE(135)] = 2137,
  [SMALL_STATE(136)] = 2141,
  [SMALL_STATE(137)] = 2145,
  [SMALL_STATE(138)] = 2149,
  [SMALL_STATE(139)] = 2153,
  [SMALL_STATE(140)] = 2157,
  [SMALL_STATE(141)] = 2161,
  [SMALL_STATE(142)] = 2165,
  [SMALL_STATE(143)] = 2169,
  [SMALL_STATE(144)] = 2173,
  [SMALL_STATE(145)] = 2177,
  [SMALL_STATE(146)] = 2181,
  [SMALL_STATE(147)] = 2185,
  [SMALL_STATE(148)] = 2189,
  [SMALL_STATE(149)] = 2193,
  [SMALL_STATE(150)] = 2197,
  [SMALL_STATE(151)] = 2201,
  [SMALL_STATE(152)] = 2205,
  [SMALL_STATE(153)] = 2209,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(86),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(146),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(100),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(116),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(85),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(153),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(99),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(92),
  [21] = {.entry = {.count = 1, .reusable = false}}, SHIFT(89),
  [23] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__source_block, 2, 0, 0),
  [25] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__source_block, 2, 0, 0), SHIFT_REPEAT(86),
  [28] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__source_block, 2, 0, 0), SHIFT_REPEAT(146),
  [31] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__source_block, 2, 0, 0), SHIFT_REPEAT(100),
  [34] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__source_block, 2, 0, 0), SHIFT_REPEAT(116),
  [37] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [39] = {.entry = {.count = 1, .reusable = false}}, SHIFT(16),
  [41] = {.entry = {.count = 1, .reusable = false}}, SHIFT(81),
  [43] = {.entry = {.count = 1, .reusable = true}}, SHIFT(97),
  [45] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [47] = {.entry = {.count = 1, .reusable = false}}, SHIFT(23),
  [49] = {.entry = {.count = 1, .reusable = false}}, SHIFT(32),
  [51] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [53] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [55] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_component_body, 1, 0, 0),
  [57] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [59] = {.entry = {.count = 1, .reusable = false}}, SHIFT(15),
  [61] = {.entry = {.count = 1, .reusable = false}}, SHIFT(31),
  [63] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [65] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__source_block, 2, 0, 0), SHIFT_REPEAT(85),
  [68] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__source_block, 2, 0, 0), SHIFT_REPEAT(153),
  [71] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym__source_block, 2, 0, 0),
  [73] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__source_block, 2, 0, 0), SHIFT_REPEAT(92),
  [76] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [78] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [80] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [82] = {.entry = {.count = 1, .reusable = true}}, SHIFT(110),
  [84] = {.entry = {.count = 1, .reusable = true}}, SHIFT(119),
  [86] = {.entry = {.count = 1, .reusable = true}}, SHIFT(104),
  [88] = {.entry = {.count = 1, .reusable = true}}, SHIFT(103),
  [90] = {.entry = {.count = 1, .reusable = true}}, SHIFT(123),
  [92] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [94] = {.entry = {.count = 1, .reusable = true}}, SHIFT(115),
  [96] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [98] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [100] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [102] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [104] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__statements_repeat1, 2, 0, 0),
  [106] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__statements_repeat1, 2, 0, 0), SHIFT_REPEAT(153),
  [109] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym__statements_repeat1, 2, 0, 0),
  [111] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__statements_repeat1, 2, 0, 0), SHIFT_REPEAT(92),
  [114] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__statements_repeat1, 2, 0, 0), SHIFT_REPEAT(116),
  [117] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__statements_repeat1, 2, 0, 0), SHIFT_REPEAT(146),
  [120] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__statements_repeat1, 2, 0, 0), SHIFT_REPEAT(100),
  [123] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__statements, 1, 0, 0),
  [125] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__statements, 1, 0, 0),
  [127] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__atomic, 1, 0, 0),
  [129] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__atomic, 1, 0, 0),
  [131] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__expression_component_reference, 1, 0, 0),
  [133] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [135] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [137] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__index, 1, 0, 0),
  [139] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__index, 1, 0, 0),
  [141] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [143] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__assignment_right, 1, 0, 0),
  [145] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__assignment_right, 1, 0, 0),
  [147] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [149] = {.entry = {.count = 1, .reusable = false}}, SHIFT(21),
  [151] = {.entry = {.count = 1, .reusable = true}}, SHIFT(127),
  [153] = {.entry = {.count = 1, .reusable = true}}, SHIFT(126),
  [155] = {.entry = {.count = 1, .reusable = true}}, SHIFT(90),
  [157] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [159] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_range_open_right, 2, 0, 0),
  [161] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_range_open_right, 2, 0, 0),
  [163] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [165] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__declaration_right, 1, 0, 0),
  [167] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__declaration_right, 1, 0, 0),
  [169] = {.entry = {.count = 1, .reusable = true}}, SHIFT(139),
  [171] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [173] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [175] = {.entry = {.count = 1, .reusable = false}}, SHIFT(26),
  [177] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [179] = {.entry = {.count = 1, .reusable = true}}, SHIFT(151),
  [181] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [183] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_assignment_left_list_repeat1, 2, 0, 0),
  [185] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_assignment_left_list_repeat1, 2, 0, 0),
  [187] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_assignment_left_list_repeat1, 2, 0, 0), SHIFT_REPEAT(131),
  [190] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__expression_primary, 3, 0, 0),
  [192] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__expression_primary, 3, 0, 0),
  [194] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__identifiers, 1, 0, 0),
  [196] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__identifiers, 1, 0, 0),
  [198] = {.entry = {.count = 1, .reusable = true}}, SHIFT(131),
  [200] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_range_open_left, 2, 0, 0),
  [202] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_range_open_left, 2, 0, 0),
  [204] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression_unary, 2, 0, 5),
  [206] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expression_unary, 2, 0, 5),
  [208] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__identifiers, 2, 0, 0),
  [210] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__identifiers, 2, 0, 0),
  [212] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_declaration_left_list, 2, 0, 0),
  [214] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_declaration_left_list, 2, 0, 0),
  [216] = {.entry = {.count = 1, .reusable = true}}, SHIFT(122),
  [218] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_declaration_right_list_repeat1, 2, 0, 0),
  [220] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_declaration_right_list_repeat1, 2, 0, 0),
  [222] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_reference, 3, 0, 0),
  [224] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_reference, 3, 0, 0),
  [226] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_declaration_left_list_repeat1, 2, 0, 0),
  [228] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_declaration_left_list_repeat1, 2, 0, 0),
  [230] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_declaration_left_list_repeat1, 2, 0, 0), SHIFT_REPEAT(124),
  [233] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression_component, 4, 0, 6),
  [235] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expression_component, 4, 0, 6),
  [237] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression_binary, 3, 0, 2),
  [239] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expression_binary, 3, 0, 2),
  [241] = {.entry = {.count = 1, .reusable = true}}, SHIFT(124),
  [243] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_range_closed, 3, 0, 0),
  [245] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_range_closed, 3, 0, 0),
  [247] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__declaration_left, 1, 0, 0),
  [249] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__declaration_left, 1, 0, 0),
  [251] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_declaration_left_list_repeat1, 2, 0, 0), SHIFT_REPEAT(122),
  [254] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__declarator, 1, 0, 0),
  [256] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__declarator, 1, 0, 0),
  [258] = {.entry = {.count = 1, .reusable = true}}, SHIFT(129),
  [260] = {.entry = {.count = 1, .reusable = true}}, SHIFT(140),
  [262] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_declaration_right_list_repeat1, 2, 0, 0), SHIFT_REPEAT(24),
  [265] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_assignment_right_list, 2, 0, 0),
  [267] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_assignment_right_list, 2, 0, 0),
  [269] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_declaration_right_list, 2, 0, 0),
  [271] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_declaration_right_list, 2, 0, 0),
  [273] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_declarator_subscript, 3, 0, 3),
  [275] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_declarator_subscript, 3, 0, 3),
  [277] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_declaration_right_list_repeat1, 2, 0, 0), SHIFT_REPEAT(25),
  [280] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [282] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__comments_repeat1, 2, 0, 0), SHIFT_REPEAT(83),
  [285] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym__comments_repeat1, 2, 0, 0),
  [287] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_declaration, 2, 0, 1),
  [289] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_declaration, 2, 0, 1),
  [291] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [293] = {.entry = {.count = 1, .reusable = true}}, SHIFT(83),
  [295] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__comments, 1, 0, 0),
  [297] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__comments, 1, 0, 0),
  [299] = {.entry = {.count = 1, .reusable = true}}, SHIFT(87),
  [301] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__comments_repeat1, 2, 0, 0),
  [303] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__comments_repeat1, 2, 0, 0), SHIFT_REPEAT(87),
  [306] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [308] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_component, 8, 0, 7),
  [310] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_component, 8, 0, 7),
  [312] = {.entry = {.count = 1, .reusable = true}}, SHIFT(101),
  [314] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_declaration, 4, 0, 4),
  [316] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_declaration, 4, 0, 4),
  [318] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [320] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_component_outputs, 1, 0, 0),
  [322] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_component_outputs, 1, 0, 0),
  [324] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_component, 9, 0, 8),
  [326] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_component, 9, 0, 8),
  [328] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_assignment, 3, 0, 2),
  [330] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_assignment, 3, 0, 2),
  [332] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__expression_component_input, 1, 0, 0),
  [334] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [336] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [338] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [340] = {.entry = {.count = 1, .reusable = true}}, SHIFT(108),
  [342] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_component_reference, 2, 0, 0),
  [344] = {.entry = {.count = 1, .reusable = true}}, SHIFT(138),
  [346] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_assignment_left_list, 2, 0, 0),
  [348] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [350] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_declaration_right_list_repeat1, 2, 0, 0), SHIFT_REPEAT(18),
  [353] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [355] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__assignment_left, 1, 0, 0),
  [357] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression_component_input_list, 2, 0, 0),
  [359] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [361] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_component_reference_repeat1, 2, 0, 0),
  [363] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_component_reference_repeat1, 2, 0, 0), SHIFT_REPEAT(138),
  [366] = {.entry = {.count = 1, .reusable = true}}, SHIFT(109),
  [368] = {.entry = {.count = 1, .reusable = true}}, SHIFT(105),
  [370] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [372] = {.entry = {.count = 1, .reusable = true}}, SHIFT(80),
  [374] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [376] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [378] = {.entry = {.count = 1, .reusable = true}}, SHIFT(120),
  [380] = {.entry = {.count = 1, .reusable = true}}, SHIFT(107),
  [382] = {.entry = {.count = 1, .reusable = true}}, SHIFT(102),
  [384] = {.entry = {.count = 1, .reusable = true}}, SHIFT(94),
  [386] = {.entry = {.count = 1, .reusable = true}}, SHIFT(125),
  [388] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [390] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [392] = {.entry = {.count = 1, .reusable = true}}, SHIFT(77),
  [394] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [396] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [398] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [400] = {.entry = {.count = 1, .reusable = true}}, SHIFT(132),
  [402] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_component_inputs, 1, 0, 0),
  [404] = {.entry = {.count = 1, .reusable = true}}, SHIFT(136),
  [406] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [408] = {.entry = {.count = 1, .reusable = true}}, SHIFT(117),
  [410] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [412] = {.entry = {.count = 1, .reusable = true}}, SHIFT(148),
  [414] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [416] = {.entry = {.count = 1, .reusable = true}}, SHIFT(113),
  [418] = {.entry = {.count = 1, .reusable = true}}, SHIFT(152),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_cmdl(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
