#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 119
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 47
#define ALIAS_COUNT 0
#define TOKEN_COUNT 15
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 7
#define MAX_ALIAS_SEQUENCE_LENGTH 9
#define PRODUCTION_ID_COUNT 8

enum ts_symbol_identifiers {
  sym_comment = 1,
  anon_sym_component = 2,
  anon_sym_LPAREN = 3,
  anon_sym_RPAREN = 4,
  anon_sym_EQ_GT = 5,
  anon_sym_end = 6,
  anon_sym_signal = 7,
  anon_sym_LT_EQ = 8,
  anon_sym_COMMA = 9,
  anon_sym_not = 10,
  anon_sym_and = 11,
  anon_sym_or = 12,
  sym_identifier = 13,
  sym_number = 14,
  sym_source_file = 15,
  aux_sym__source_block = 16,
  sym__comments = 17,
  sym__statements = 18,
  sym__statement = 19,
  sym_component = 20,
  sym_component_inputs = 21,
  sym_component_outputs = 22,
  sym_component_body = 23,
  sym_declaration = 24,
  sym__declaration_left = 25,
  sym__declaration_right = 26,
  sym_declaration_left_list = 27,
  sym_declaration_right_list = 28,
  sym_assignment = 29,
  sym__assignment_left = 30,
  sym__assignment_right = 31,
  sym_assignment_left_list = 32,
  sym_assignment_right_list = 33,
  sym__expression = 34,
  sym__expression_primary = 35,
  sym_expression_component = 36,
  sym__expression_component_input = 37,
  sym_expression_component_input_list = 38,
  sym_expression_unary = 39,
  sym_expression_binary = 40,
  sym__atomic = 41,
  sym__identifiers = 42,
  aux_sym__comments_repeat1 = 43,
  aux_sym__statements_repeat1 = 44,
  aux_sym_declaration_left_list_repeat1 = 45,
  aux_sym_declaration_right_list_repeat1 = 46,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_comment] = "comment",
  [anon_sym_component] = "component",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_EQ_GT] = "=>",
  [anon_sym_end] = "end",
  [anon_sym_signal] = "signal",
  [anon_sym_LT_EQ] = "<=",
  [anon_sym_COMMA] = ",",
  [anon_sym_not] = "not",
  [anon_sym_and] = "and",
  [anon_sym_or] = "or",
  [sym_identifier] = "identifier",
  [sym_number] = "number",
  [sym_source_file] = "source_file",
  [aux_sym__source_block] = "_source_block",
  [sym__comments] = "_comments",
  [sym__statements] = "_statements",
  [sym__statement] = "_statement",
  [sym_component] = "component",
  [sym_component_inputs] = "component_inputs",
  [sym_component_outputs] = "component_outputs",
  [sym_component_body] = "component_body",
  [sym_declaration] = "declaration",
  [sym__declaration_left] = "_declaration_left",
  [sym__declaration_right] = "_declaration_right",
  [sym_declaration_left_list] = "declaration_left_list",
  [sym_declaration_right_list] = "declaration_right_list",
  [sym_assignment] = "assignment",
  [sym__assignment_left] = "_assignment_left",
  [sym__assignment_right] = "_assignment_right",
  [sym_assignment_left_list] = "assignment_left_list",
  [sym_assignment_right_list] = "assignment_right_list",
  [sym__expression] = "_expression",
  [sym__expression_primary] = "_expression_primary",
  [sym_expression_component] = "expression_component",
  [sym__expression_component_input] = "_expression_component_input",
  [sym_expression_component_input_list] = "expression_component_input_list",
  [sym_expression_unary] = "expression_unary",
  [sym_expression_binary] = "expression_binary",
  [sym__atomic] = "_atomic",
  [sym__identifiers] = "_identifiers",
  [aux_sym__comments_repeat1] = "_comments_repeat1",
  [aux_sym__statements_repeat1] = "_statements_repeat1",
  [aux_sym_declaration_left_list_repeat1] = "declaration_left_list_repeat1",
  [aux_sym_declaration_right_list_repeat1] = "declaration_right_list_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_comment] = sym_comment,
  [anon_sym_component] = anon_sym_component,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_EQ_GT] = anon_sym_EQ_GT,
  [anon_sym_end] = anon_sym_end,
  [anon_sym_signal] = anon_sym_signal,
  [anon_sym_LT_EQ] = anon_sym_LT_EQ,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_not] = anon_sym_not,
  [anon_sym_and] = anon_sym_and,
  [anon_sym_or] = anon_sym_or,
  [sym_identifier] = sym_identifier,
  [sym_number] = sym_number,
  [sym_source_file] = sym_source_file,
  [aux_sym__source_block] = aux_sym__source_block,
  [sym__comments] = sym__comments,
  [sym__statements] = sym__statements,
  [sym__statement] = sym__statement,
  [sym_component] = sym_component,
  [sym_component_inputs] = sym_component_inputs,
  [sym_component_outputs] = sym_component_outputs,
  [sym_component_body] = sym_component_body,
  [sym_declaration] = sym_declaration,
  [sym__declaration_left] = sym__declaration_left,
  [sym__declaration_right] = sym__declaration_right,
  [sym_declaration_left_list] = sym_declaration_left_list,
  [sym_declaration_right_list] = sym_declaration_right_list,
  [sym_assignment] = sym_assignment,
  [sym__assignment_left] = sym__assignment_left,
  [sym__assignment_right] = sym__assignment_right,
  [sym_assignment_left_list] = sym_assignment_left_list,
  [sym_assignment_right_list] = sym_assignment_right_list,
  [sym__expression] = sym__expression,
  [sym__expression_primary] = sym__expression_primary,
  [sym_expression_component] = sym_expression_component,
  [sym__expression_component_input] = sym__expression_component_input,
  [sym_expression_component_input_list] = sym_expression_component_input_list,
  [sym_expression_unary] = sym_expression_unary,
  [sym_expression_binary] = sym_expression_binary,
  [sym__atomic] = sym__atomic,
  [sym__identifiers] = sym__identifiers,
  [aux_sym__comments_repeat1] = aux_sym__comments_repeat1,
  [aux_sym__statements_repeat1] = aux_sym__statements_repeat1,
  [aux_sym_declaration_left_list_repeat1] = aux_sym_declaration_left_list_repeat1,
  [aux_sym_declaration_right_list_repeat1] = aux_sym_declaration_right_list_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_component] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_end] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_signal] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_not] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_and] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_or] = {
    .visible = true,
    .named = false,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [aux_sym__source_block] = {
    .visible = false,
    .named = false,
  },
  [sym__comments] = {
    .visible = false,
    .named = true,
  },
  [sym__statements] = {
    .visible = false,
    .named = true,
  },
  [sym__statement] = {
    .visible = false,
    .named = true,
  },
  [sym_component] = {
    .visible = true,
    .named = true,
  },
  [sym_component_inputs] = {
    .visible = true,
    .named = true,
  },
  [sym_component_outputs] = {
    .visible = true,
    .named = true,
  },
  [sym_component_body] = {
    .visible = true,
    .named = true,
  },
  [sym_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym__declaration_left] = {
    .visible = false,
    .named = true,
  },
  [sym__declaration_right] = {
    .visible = false,
    .named = true,
  },
  [sym_declaration_left_list] = {
    .visible = true,
    .named = true,
  },
  [sym_declaration_right_list] = {
    .visible = true,
    .named = true,
  },
  [sym_assignment] = {
    .visible = true,
    .named = true,
  },
  [sym__assignment_left] = {
    .visible = false,
    .named = true,
  },
  [sym__assignment_right] = {
    .visible = false,
    .named = true,
  },
  [sym_assignment_left_list] = {
    .visible = true,
    .named = true,
  },
  [sym_assignment_right_list] = {
    .visible = true,
    .named = true,
  },
  [sym__expression] = {
    .visible = false,
    .named = true,
  },
  [sym__expression_primary] = {
    .visible = false,
    .named = true,
  },
  [sym_expression_component] = {
    .visible = true,
    .named = true,
  },
  [sym__expression_component_input] = {
    .visible = false,
    .named = true,
  },
  [sym_expression_component_input_list] = {
    .visible = true,
    .named = true,
  },
  [sym_expression_unary] = {
    .visible = true,
    .named = true,
  },
  [sym_expression_binary] = {
    .visible = true,
    .named = true,
  },
  [sym__atomic] = {
    .visible = false,
    .named = true,
  },
  [sym__identifiers] = {
    .visible = false,
    .named = true,
  },
  [aux_sym__comments_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__statements_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_declaration_left_list_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_declaration_right_list_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_body = 1,
  field_inputs = 2,
  field_left = 3,
  field_name = 4,
  field_operand = 5,
  field_outputs = 6,
  field_right = 7,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_body] = "body",
  [field_inputs] = "inputs",
  [field_left] = "left",
  [field_name] = "name",
  [field_operand] = "operand",
  [field_outputs] = "outputs",
  [field_right] = "right",
};

static const TSFieldMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 2},
  [3] = {.index = 3, .length = 2},
  [4] = {.index = 5, .length = 1},
  [5] = {.index = 6, .length = 2},
  [6] = {.index = 8, .length = 3},
  [7] = {.index = 11, .length = 4},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_left, 1},
  [1] =
    {field_left, 0},
    {field_right, 2},
  [3] =
    {field_left, 1},
    {field_right, 3},
  [5] =
    {field_operand, 1},
  [6] =
    {field_inputs, 2},
    {field_name, 0},
  [8] =
    {field_inputs, 3},
    {field_name, 1},
    {field_outputs, 6},
  [11] =
    {field_body, 7},
    {field_inputs, 3},
    {field_name, 1},
    {field_outputs, 6},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 2,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 5,
  [8] = 8,
  [9] = 9,
  [10] = 9,
  [11] = 11,
  [12] = 8,
  [13] = 11,
  [14] = 9,
  [15] = 15,
  [16] = 16,
  [17] = 16,
  [18] = 15,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 20,
  [24] = 22,
  [25] = 22,
  [26] = 21,
  [27] = 21,
  [28] = 19,
  [29] = 20,
  [30] = 19,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 31,
  [36] = 34,
  [37] = 33,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 41,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 38,
  [47] = 47,
  [48] = 32,
  [49] = 40,
  [50] = 43,
  [51] = 44,
  [52] = 45,
  [53] = 47,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 39,
  [58] = 55,
  [59] = 54,
  [60] = 60,
  [61] = 61,
  [62] = 60,
  [63] = 63,
  [64] = 64,
  [65] = 63,
  [66] = 66,
  [67] = 64,
  [68] = 66,
  [69] = 69,
  [70] = 70,
  [71] = 33,
  [72] = 72,
  [73] = 73,
  [74] = 69,
  [75] = 75,
  [76] = 72,
  [77] = 73,
  [78] = 78,
  [79] = 70,
  [80] = 44,
  [81] = 47,
  [82] = 38,
  [83] = 43,
  [84] = 40,
  [85] = 55,
  [86] = 86,
  [87] = 87,
  [88] = 88,
  [89] = 56,
  [90] = 86,
  [91] = 91,
  [92] = 61,
  [93] = 88,
  [94] = 94,
  [95] = 87,
  [96] = 96,
  [97] = 97,
  [98] = 86,
  [99] = 94,
  [100] = 100,
  [101] = 101,
  [102] = 102,
  [103] = 103,
  [104] = 104,
  [105] = 105,
  [106] = 105,
  [107] = 102,
  [108] = 108,
  [109] = 108,
  [110] = 110,
  [111] = 111,
  [112] = 112,
  [113] = 102,
  [114] = 112,
  [115] = 101,
  [116] = 104,
  [117] = 103,
  [118] = 111,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(15);
      ADVANCE_MAP(
        '#', 16,
        '(', 18,
        ')', 19,
        ',', 25,
        '<', 5,
        '=', 6,
        'a', 39,
        'c', 44,
        'e', 42,
        'n', 45,
        'o', 48,
        's', 36,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(52);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(51);
      END_STATE();
    case 1:
      ADVANCE_MAP(
        '#', 16,
        '(', 18,
        ',', 25,
        'a', 39,
        'c', 44,
        'e', 42,
        'o', 48,
        's', 36,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(1);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(51);
      END_STATE();
    case 2:
      if (lookahead == '#') ADVANCE(16);
      if (lookahead == ',') ADVANCE(25);
      if (lookahead == '<') ADVANCE(5);
      if (lookahead == 'c') ADVANCE(44);
      if (lookahead == 'e') ADVANCE(42);
      if (lookahead == 's') ADVANCE(36);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(2);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(51);
      END_STATE();
    case 3:
      if (lookahead == '(') ADVANCE(18);
      if (lookahead == ')') ADVANCE(19);
      if (lookahead == ',') ADVANCE(25);
      if (lookahead == 'a') ADVANCE(9);
      if (lookahead == 'e') ADVANCE(10);
      if (lookahead == 'o') ADVANCE(11);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(3);
      END_STATE();
    case 4:
      if (lookahead == '(') ADVANCE(18);
      if (lookahead == 'n') ADVANCE(45);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(4);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(52);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(51);
      END_STATE();
    case 5:
      if (lookahead == '=') ADVANCE(24);
      END_STATE();
    case 6:
      if (lookahead == '>') ADVANCE(20);
      END_STATE();
    case 7:
      if (lookahead == 'd') ADVANCE(27);
      END_STATE();
    case 8:
      if (lookahead == 'd') ADVANCE(21);
      END_STATE();
    case 9:
      if (lookahead == 'n') ADVANCE(7);
      END_STATE();
    case 10:
      if (lookahead == 'n') ADVANCE(8);
      END_STATE();
    case 11:
      if (lookahead == 'r') ADVANCE(29);
      END_STATE();
    case 12:
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(12);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(51);
      END_STATE();
    case 13:
      if (eof) ADVANCE(15);
      if (lookahead == '#') ADVANCE(16);
      if (lookahead == '(') ADVANCE(18);
      if (lookahead == ',') ADVANCE(25);
      if (lookahead == 'a') ADVANCE(39);
      if (lookahead == 'c') ADVANCE(44);
      if (lookahead == 'o') ADVANCE(48);
      if (lookahead == 's') ADVANCE(36);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(13);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(51);
      END_STATE();
    case 14:
      if (eof) ADVANCE(15);
      if (lookahead == '#') ADVANCE(16);
      if (lookahead == ')') ADVANCE(19);
      if (lookahead == ',') ADVANCE(25);
      if (lookahead == '<') ADVANCE(5);
      if (lookahead == 'c') ADVANCE(44);
      if (lookahead == 's') ADVANCE(36);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(14);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(51);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(16);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_component);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(51);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_EQ_GT);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_end);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_end);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(51);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_signal);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(51);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_LT_EQ);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_not);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(51);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_and);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_and);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(51);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_or);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_or);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(51);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'a') ADVANCE(37);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(51);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'd') ADVANCE(28);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(51);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'd') ADVANCE(22);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(51);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(43);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(51);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'g') ADVANCE(40);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(51);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'i') ADVANCE(35);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(51);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'l') ADVANCE(23);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(51);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'm') ADVANCE(47);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(51);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'n') ADVANCE(32);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(51);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'n') ADVANCE(31);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(51);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'n') ADVANCE(34);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(51);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'n') ADVANCE(33);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(51);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'n') ADVANCE(50);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(51);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'o') ADVANCE(38);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(51);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'o') ADVANCE(49);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(51);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'o') ADVANCE(41);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(51);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'p') ADVANCE(46);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(51);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'r') ADVANCE(30);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(51);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 't') ADVANCE(26);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(51);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 't') ADVANCE(17);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(51);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(51);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(52);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 14},
  [2] = {.lex_state = 2},
  [3] = {.lex_state = 2},
  [4] = {.lex_state = 2},
  [5] = {.lex_state = 2},
  [6] = {.lex_state = 14},
  [7] = {.lex_state = 14},
  [8] = {.lex_state = 14},
  [9] = {.lex_state = 4},
  [10] = {.lex_state = 4},
  [11] = {.lex_state = 14},
  [12] = {.lex_state = 2},
  [13] = {.lex_state = 2},
  [14] = {.lex_state = 4},
  [15] = {.lex_state = 4},
  [16] = {.lex_state = 4},
  [17] = {.lex_state = 4},
  [18] = {.lex_state = 4},
  [19] = {.lex_state = 4},
  [20] = {.lex_state = 4},
  [21] = {.lex_state = 4},
  [22] = {.lex_state = 4},
  [23] = {.lex_state = 4},
  [24] = {.lex_state = 4},
  [25] = {.lex_state = 4},
  [26] = {.lex_state = 4},
  [27] = {.lex_state = 4},
  [28] = {.lex_state = 4},
  [29] = {.lex_state = 4},
  [30] = {.lex_state = 4},
  [31] = {.lex_state = 1},
  [32] = {.lex_state = 14},
  [33] = {.lex_state = 13},
  [34] = {.lex_state = 1},
  [35] = {.lex_state = 13},
  [36] = {.lex_state = 13},
  [37] = {.lex_state = 1},
  [38] = {.lex_state = 1},
  [39] = {.lex_state = 14},
  [40] = {.lex_state = 1},
  [41] = {.lex_state = 14},
  [42] = {.lex_state = 2},
  [43] = {.lex_state = 13},
  [44] = {.lex_state = 1},
  [45] = {.lex_state = 14},
  [46] = {.lex_state = 13},
  [47] = {.lex_state = 13},
  [48] = {.lex_state = 2},
  [49] = {.lex_state = 13},
  [50] = {.lex_state = 1},
  [51] = {.lex_state = 13},
  [52] = {.lex_state = 2},
  [53] = {.lex_state = 1},
  [54] = {.lex_state = 2},
  [55] = {.lex_state = 2},
  [56] = {.lex_state = 2},
  [57] = {.lex_state = 2},
  [58] = {.lex_state = 14},
  [59] = {.lex_state = 14},
  [60] = {.lex_state = 2},
  [61] = {.lex_state = 2},
  [62] = {.lex_state = 14},
  [63] = {.lex_state = 2},
  [64] = {.lex_state = 2},
  [65] = {.lex_state = 14},
  [66] = {.lex_state = 14},
  [67] = {.lex_state = 14},
  [68] = {.lex_state = 2},
  [69] = {.lex_state = 2},
  [70] = {.lex_state = 14},
  [71] = {.lex_state = 3},
  [72] = {.lex_state = 2},
  [73] = {.lex_state = 2},
  [74] = {.lex_state = 14},
  [75] = {.lex_state = 2},
  [76] = {.lex_state = 14},
  [77] = {.lex_state = 14},
  [78] = {.lex_state = 3},
  [79] = {.lex_state = 2},
  [80] = {.lex_state = 3},
  [81] = {.lex_state = 3},
  [82] = {.lex_state = 3},
  [83] = {.lex_state = 3},
  [84] = {.lex_state = 3},
  [85] = {.lex_state = 0},
  [86] = {.lex_state = 3},
  [87] = {.lex_state = 12},
  [88] = {.lex_state = 12},
  [89] = {.lex_state = 0},
  [90] = {.lex_state = 3},
  [91] = {.lex_state = 0},
  [92] = {.lex_state = 0},
  [93] = {.lex_state = 12},
  [94] = {.lex_state = 12},
  [95] = {.lex_state = 12},
  [96] = {.lex_state = 0},
  [97] = {.lex_state = 0},
  [98] = {.lex_state = 3},
  [99] = {.lex_state = 12},
  [100] = {.lex_state = 0},
  [101] = {.lex_state = 0},
  [102] = {.lex_state = 0},
  [103] = {.lex_state = 0},
  [104] = {.lex_state = 3},
  [105] = {.lex_state = 12},
  [106] = {.lex_state = 12},
  [107] = {.lex_state = 0},
  [108] = {.lex_state = 0},
  [109] = {.lex_state = 0},
  [110] = {.lex_state = 0},
  [111] = {.lex_state = 12},
  [112] = {.lex_state = 0},
  [113] = {.lex_state = 0},
  [114] = {.lex_state = 0},
  [115] = {.lex_state = 0},
  [116] = {.lex_state = 3},
  [117] = {.lex_state = 0},
  [118] = {.lex_state = 12},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_comment] = ACTIONS(1),
    [anon_sym_component] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_EQ_GT] = ACTIONS(1),
    [anon_sym_end] = ACTIONS(1),
    [anon_sym_signal] = ACTIONS(1),
    [anon_sym_LT_EQ] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_not] = ACTIONS(1),
    [anon_sym_and] = ACTIONS(1),
    [anon_sym_or] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
  },
  [1] = {
    [sym_source_file] = STATE(110),
    [aux_sym__source_block] = STATE(6),
    [sym__comments] = STATE(6),
    [sym__statements] = STATE(6),
    [sym__statement] = STATE(11),
    [sym_component] = STATE(11),
    [sym_declaration] = STATE(11),
    [sym_assignment] = STATE(11),
    [sym__assignment_left] = STATE(109),
    [sym_assignment_left_list] = STATE(109),
    [aux_sym__comments_repeat1] = STATE(65),
    [aux_sym__statements_repeat1] = STATE(11),
    [ts_builtin_sym_end] = ACTIONS(3),
    [sym_comment] = ACTIONS(5),
    [anon_sym_component] = ACTIONS(7),
    [anon_sym_signal] = ACTIONS(9),
    [sym_identifier] = ACTIONS(11),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 10,
    ACTIONS(11), 1,
      sym_identifier,
    ACTIONS(13), 1,
      sym_comment,
    ACTIONS(15), 1,
      anon_sym_component,
    ACTIONS(17), 1,
      anon_sym_end,
    ACTIONS(19), 1,
      anon_sym_signal,
    STATE(63), 1,
      aux_sym__comments_repeat1,
    STATE(104), 1,
      sym_component_body,
    STATE(108), 2,
      sym__assignment_left,
      sym_assignment_left_list,
    STATE(4), 3,
      aux_sym__source_block,
      sym__comments,
      sym__statements,
    STATE(13), 5,
      sym__statement,
      sym_component,
      sym_declaration,
      sym_assignment,
      aux_sym__statements_repeat1,
  [38] = 10,
    ACTIONS(11), 1,
      sym_identifier,
    ACTIONS(13), 1,
      sym_comment,
    ACTIONS(15), 1,
      anon_sym_component,
    ACTIONS(19), 1,
      anon_sym_signal,
    ACTIONS(21), 1,
      anon_sym_end,
    STATE(63), 1,
      aux_sym__comments_repeat1,
    STATE(116), 1,
      sym_component_body,
    STATE(108), 2,
      sym__assignment_left,
      sym_assignment_left_list,
    STATE(4), 3,
      aux_sym__source_block,
      sym__comments,
      sym__statements,
    STATE(13), 5,
      sym__statement,
      sym_component,
      sym_declaration,
      sym_assignment,
      aux_sym__statements_repeat1,
  [76] = 9,
    ACTIONS(11), 1,
      sym_identifier,
    ACTIONS(13), 1,
      sym_comment,
    ACTIONS(15), 1,
      anon_sym_component,
    ACTIONS(19), 1,
      anon_sym_signal,
    ACTIONS(23), 1,
      anon_sym_end,
    STATE(63), 1,
      aux_sym__comments_repeat1,
    STATE(108), 2,
      sym__assignment_left,
      sym_assignment_left_list,
    STATE(5), 3,
      aux_sym__source_block,
      sym__comments,
      sym__statements,
    STATE(13), 5,
      sym__statement,
      sym_component,
      sym_declaration,
      sym_assignment,
      aux_sym__statements_repeat1,
  [111] = 9,
    ACTIONS(25), 1,
      sym_comment,
    ACTIONS(28), 1,
      anon_sym_component,
    ACTIONS(31), 1,
      anon_sym_end,
    ACTIONS(33), 1,
      anon_sym_signal,
    ACTIONS(36), 1,
      sym_identifier,
    STATE(63), 1,
      aux_sym__comments_repeat1,
    STATE(108), 2,
      sym__assignment_left,
      sym_assignment_left_list,
    STATE(5), 3,
      aux_sym__source_block,
      sym__comments,
      sym__statements,
    STATE(13), 5,
      sym__statement,
      sym_component,
      sym_declaration,
      sym_assignment,
      aux_sym__statements_repeat1,
  [146] = 9,
    ACTIONS(5), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_component,
    ACTIONS(9), 1,
      anon_sym_signal,
    ACTIONS(11), 1,
      sym_identifier,
    ACTIONS(39), 1,
      ts_builtin_sym_end,
    STATE(65), 1,
      aux_sym__comments_repeat1,
    STATE(109), 2,
      sym__assignment_left,
      sym_assignment_left_list,
    STATE(7), 3,
      aux_sym__source_block,
      sym__comments,
      sym__statements,
    STATE(11), 5,
      sym__statement,
      sym_component,
      sym_declaration,
      sym_assignment,
      aux_sym__statements_repeat1,
  [181] = 9,
    ACTIONS(36), 1,
      sym_identifier,
    ACTIONS(41), 1,
      ts_builtin_sym_end,
    ACTIONS(43), 1,
      sym_comment,
    ACTIONS(46), 1,
      anon_sym_component,
    ACTIONS(49), 1,
      anon_sym_signal,
    STATE(65), 1,
      aux_sym__comments_repeat1,
    STATE(109), 2,
      sym__assignment_left,
      sym_assignment_left_list,
    STATE(7), 3,
      aux_sym__source_block,
      sym__comments,
      sym__statements,
    STATE(11), 5,
      sym__statement,
      sym_component,
      sym_declaration,
      sym_assignment,
      aux_sym__statements_repeat1,
  [216] = 6,
    ACTIONS(54), 1,
      anon_sym_component,
    ACTIONS(57), 1,
      anon_sym_signal,
    ACTIONS(60), 1,
      sym_identifier,
    ACTIONS(52), 2,
      ts_builtin_sym_end,
      sym_comment,
    STATE(109), 2,
      sym__assignment_left,
      sym_assignment_left_list,
    STATE(8), 5,
      sym__statement,
      sym_component,
      sym_declaration,
      sym_assignment,
      aux_sym__statements_repeat1,
  [241] = 6,
    ACTIONS(63), 1,
      anon_sym_LPAREN,
    ACTIONS(65), 1,
      anon_sym_not,
    ACTIONS(67), 1,
      sym_identifier,
    ACTIONS(69), 1,
      sym_number,
    STATE(107), 2,
      sym__expression_component_input,
      sym_expression_component_input_list,
    STATE(78), 6,
      sym__expression,
      sym__expression_primary,
      sym_expression_component,
      sym_expression_unary,
      sym_expression_binary,
      sym__atomic,
  [266] = 6,
    ACTIONS(63), 1,
      anon_sym_LPAREN,
    ACTIONS(65), 1,
      anon_sym_not,
    ACTIONS(67), 1,
      sym_identifier,
    ACTIONS(69), 1,
      sym_number,
    STATE(113), 2,
      sym__expression_component_input,
      sym_expression_component_input_list,
    STATE(78), 6,
      sym__expression,
      sym__expression_primary,
      sym_expression_component,
      sym_expression_unary,
      sym_expression_binary,
      sym__atomic,
  [291] = 6,
    ACTIONS(7), 1,
      anon_sym_component,
    ACTIONS(9), 1,
      anon_sym_signal,
    ACTIONS(11), 1,
      sym_identifier,
    ACTIONS(71), 2,
      ts_builtin_sym_end,
      sym_comment,
    STATE(109), 2,
      sym__assignment_left,
      sym_assignment_left_list,
    STATE(8), 5,
      sym__statement,
      sym_component,
      sym_declaration,
      sym_assignment,
      aux_sym__statements_repeat1,
  [316] = 7,
    ACTIONS(52), 1,
      sym_comment,
    ACTIONS(60), 1,
      sym_identifier,
    ACTIONS(73), 1,
      anon_sym_component,
    ACTIONS(76), 1,
      anon_sym_end,
    ACTIONS(78), 1,
      anon_sym_signal,
    STATE(108), 2,
      sym__assignment_left,
      sym_assignment_left_list,
    STATE(12), 5,
      sym__statement,
      sym_component,
      sym_declaration,
      sym_assignment,
      aux_sym__statements_repeat1,
  [343] = 7,
    ACTIONS(11), 1,
      sym_identifier,
    ACTIONS(15), 1,
      anon_sym_component,
    ACTIONS(19), 1,
      anon_sym_signal,
    ACTIONS(71), 1,
      sym_comment,
    ACTIONS(81), 1,
      anon_sym_end,
    STATE(108), 2,
      sym__assignment_left,
      sym_assignment_left_list,
    STATE(12), 5,
      sym__statement,
      sym_component,
      sym_declaration,
      sym_assignment,
      aux_sym__statements_repeat1,
  [370] = 6,
    ACTIONS(63), 1,
      anon_sym_LPAREN,
    ACTIONS(65), 1,
      anon_sym_not,
    ACTIONS(67), 1,
      sym_identifier,
    ACTIONS(69), 1,
      sym_number,
    STATE(102), 2,
      sym__expression_component_input,
      sym_expression_component_input_list,
    STATE(78), 6,
      sym__expression,
      sym__expression_primary,
      sym_expression_component,
      sym_expression_unary,
      sym_expression_binary,
      sym__atomic,
  [395] = 6,
    ACTIONS(83), 1,
      anon_sym_LPAREN,
    ACTIONS(85), 1,
      anon_sym_not,
    ACTIONS(87), 1,
      sym_identifier,
    ACTIONS(89), 1,
      sym_number,
    STATE(73), 2,
      sym__declaration_right,
      sym_declaration_right_list,
    STATE(34), 6,
      sym__expression,
      sym__expression_primary,
      sym_expression_component,
      sym_expression_unary,
      sym_expression_binary,
      sym__atomic,
  [420] = 6,
    ACTIONS(91), 1,
      anon_sym_LPAREN,
    ACTIONS(93), 1,
      anon_sym_not,
    ACTIONS(95), 1,
      sym_identifier,
    ACTIONS(97), 1,
      sym_number,
    STATE(76), 2,
      sym__assignment_right,
      sym_assignment_right_list,
    STATE(35), 6,
      sym__expression,
      sym__expression_primary,
      sym_expression_component,
      sym_expression_unary,
      sym_expression_binary,
      sym__atomic,
  [445] = 6,
    ACTIONS(83), 1,
      anon_sym_LPAREN,
    ACTIONS(85), 1,
      anon_sym_not,
    ACTIONS(87), 1,
      sym_identifier,
    ACTIONS(99), 1,
      sym_number,
    STATE(72), 2,
      sym__assignment_right,
      sym_assignment_right_list,
    STATE(31), 6,
      sym__expression,
      sym__expression_primary,
      sym_expression_component,
      sym_expression_unary,
      sym_expression_binary,
      sym__atomic,
  [470] = 6,
    ACTIONS(91), 1,
      anon_sym_LPAREN,
    ACTIONS(93), 1,
      anon_sym_not,
    ACTIONS(95), 1,
      sym_identifier,
    ACTIONS(101), 1,
      sym_number,
    STATE(77), 2,
      sym__declaration_right,
      sym_declaration_right_list,
    STATE(36), 6,
      sym__expression,
      sym__expression_primary,
      sym_expression_component,
      sym_expression_unary,
      sym_expression_binary,
      sym__atomic,
  [495] = 5,
    ACTIONS(63), 1,
      anon_sym_LPAREN,
    ACTIONS(65), 1,
      anon_sym_not,
    ACTIONS(67), 1,
      sym_identifier,
    ACTIONS(103), 1,
      sym_number,
    STATE(82), 6,
      sym__expression,
      sym__expression_primary,
      sym_expression_component,
      sym_expression_unary,
      sym_expression_binary,
      sym__atomic,
  [516] = 5,
    ACTIONS(63), 1,
      anon_sym_LPAREN,
    ACTIONS(65), 1,
      anon_sym_not,
    ACTIONS(67), 1,
      sym_identifier,
    ACTIONS(105), 1,
      sym_number,
    STATE(84), 6,
      sym__expression,
      sym__expression_primary,
      sym_expression_component,
      sym_expression_unary,
      sym_expression_binary,
      sym__atomic,
  [537] = 5,
    ACTIONS(91), 1,
      anon_sym_LPAREN,
    ACTIONS(93), 1,
      anon_sym_not,
    ACTIONS(95), 1,
      sym_identifier,
    ACTIONS(107), 1,
      sym_number,
    STATE(47), 6,
      sym__expression,
      sym__expression_primary,
      sym_expression_component,
      sym_expression_unary,
      sym_expression_binary,
      sym__atomic,
  [558] = 5,
    ACTIONS(63), 1,
      anon_sym_LPAREN,
    ACTIONS(65), 1,
      anon_sym_not,
    ACTIONS(67), 1,
      sym_identifier,
    ACTIONS(109), 1,
      sym_number,
    STATE(90), 6,
      sym__expression,
      sym__expression_primary,
      sym_expression_component,
      sym_expression_unary,
      sym_expression_binary,
      sym__atomic,
  [579] = 5,
    ACTIONS(91), 1,
      anon_sym_LPAREN,
    ACTIONS(93), 1,
      anon_sym_not,
    ACTIONS(95), 1,
      sym_identifier,
    ACTIONS(111), 1,
      sym_number,
    STATE(49), 6,
      sym__expression,
      sym__expression_primary,
      sym_expression_component,
      sym_expression_unary,
      sym_expression_binary,
      sym__atomic,
  [600] = 5,
    ACTIONS(63), 1,
      anon_sym_LPAREN,
    ACTIONS(65), 1,
      anon_sym_not,
    ACTIONS(67), 1,
      sym_identifier,
    ACTIONS(113), 1,
      sym_number,
    STATE(86), 6,
      sym__expression,
      sym__expression_primary,
      sym_expression_component,
      sym_expression_unary,
      sym_expression_binary,
      sym__atomic,
  [621] = 5,
    ACTIONS(63), 1,
      anon_sym_LPAREN,
    ACTIONS(65), 1,
      anon_sym_not,
    ACTIONS(67), 1,
      sym_identifier,
    ACTIONS(115), 1,
      sym_number,
    STATE(98), 6,
      sym__expression,
      sym__expression_primary,
      sym_expression_component,
      sym_expression_unary,
      sym_expression_binary,
      sym__atomic,
  [642] = 5,
    ACTIONS(63), 1,
      anon_sym_LPAREN,
    ACTIONS(65), 1,
      anon_sym_not,
    ACTIONS(67), 1,
      sym_identifier,
    ACTIONS(117), 1,
      sym_number,
    STATE(81), 6,
      sym__expression,
      sym__expression_primary,
      sym_expression_component,
      sym_expression_unary,
      sym_expression_binary,
      sym__atomic,
  [663] = 5,
    ACTIONS(83), 1,
      anon_sym_LPAREN,
    ACTIONS(85), 1,
      anon_sym_not,
    ACTIONS(87), 1,
      sym_identifier,
    ACTIONS(119), 1,
      sym_number,
    STATE(53), 6,
      sym__expression,
      sym__expression_primary,
      sym_expression_component,
      sym_expression_unary,
      sym_expression_binary,
      sym__atomic,
  [684] = 5,
    ACTIONS(83), 1,
      anon_sym_LPAREN,
    ACTIONS(85), 1,
      anon_sym_not,
    ACTIONS(87), 1,
      sym_identifier,
    ACTIONS(121), 1,
      sym_number,
    STATE(38), 6,
      sym__expression,
      sym__expression_primary,
      sym_expression_component,
      sym_expression_unary,
      sym_expression_binary,
      sym__atomic,
  [705] = 5,
    ACTIONS(83), 1,
      anon_sym_LPAREN,
    ACTIONS(85), 1,
      anon_sym_not,
    ACTIONS(87), 1,
      sym_identifier,
    ACTIONS(123), 1,
      sym_number,
    STATE(40), 6,
      sym__expression,
      sym__expression_primary,
      sym_expression_component,
      sym_expression_unary,
      sym_expression_binary,
      sym__atomic,
  [726] = 5,
    ACTIONS(91), 1,
      anon_sym_LPAREN,
    ACTIONS(93), 1,
      anon_sym_not,
    ACTIONS(95), 1,
      sym_identifier,
    ACTIONS(125), 1,
      sym_number,
    STATE(46), 6,
      sym__expression,
      sym__expression_primary,
      sym_expression_component,
      sym_expression_unary,
      sym_expression_binary,
      sym__atomic,
  [747] = 5,
    ACTIONS(127), 1,
      sym_comment,
    ACTIONS(131), 1,
      anon_sym_COMMA,
    STATE(54), 1,
      aux_sym_declaration_right_list_repeat1,
    ACTIONS(133), 2,
      anon_sym_and,
      anon_sym_or,
    ACTIONS(129), 4,
      anon_sym_component,
      anon_sym_end,
      anon_sym_signal,
      sym_identifier,
  [767] = 4,
    ACTIONS(139), 1,
      anon_sym_COMMA,
    STATE(32), 1,
      aux_sym_declaration_left_list_repeat1,
    ACTIONS(137), 3,
      anon_sym_component,
      anon_sym_signal,
      sym_identifier,
    ACTIONS(135), 4,
      ts_builtin_sym_end,
      sym_comment,
      anon_sym_RPAREN,
      anon_sym_LT_EQ,
  [785] = 3,
    ACTIONS(146), 1,
      anon_sym_LPAREN,
    ACTIONS(142), 3,
      ts_builtin_sym_end,
      sym_comment,
      anon_sym_COMMA,
    ACTIONS(144), 5,
      anon_sym_component,
      anon_sym_signal,
      anon_sym_and,
      anon_sym_or,
      sym_identifier,
  [801] = 5,
    ACTIONS(131), 1,
      anon_sym_COMMA,
    ACTIONS(148), 1,
      sym_comment,
    STATE(60), 1,
      aux_sym_declaration_right_list_repeat1,
    ACTIONS(133), 2,
      anon_sym_and,
      anon_sym_or,
    ACTIONS(150), 4,
      anon_sym_component,
      anon_sym_end,
      anon_sym_signal,
      sym_identifier,
  [821] = 5,
    ACTIONS(152), 1,
      anon_sym_COMMA,
    STATE(59), 1,
      aux_sym_declaration_right_list_repeat1,
    ACTIONS(127), 2,
      ts_builtin_sym_end,
      sym_comment,
    ACTIONS(154), 2,
      anon_sym_and,
      anon_sym_or,
    ACTIONS(129), 3,
      anon_sym_component,
      anon_sym_signal,
      sym_identifier,
  [841] = 5,
    ACTIONS(152), 1,
      anon_sym_COMMA,
    STATE(62), 1,
      aux_sym_declaration_right_list_repeat1,
    ACTIONS(148), 2,
      ts_builtin_sym_end,
      sym_comment,
    ACTIONS(154), 2,
      anon_sym_and,
      anon_sym_or,
    ACTIONS(150), 3,
      anon_sym_component,
      anon_sym_signal,
      sym_identifier,
  [861] = 3,
    ACTIONS(156), 1,
      anon_sym_LPAREN,
    ACTIONS(142), 2,
      sym_comment,
      anon_sym_COMMA,
    ACTIONS(144), 6,
      anon_sym_component,
      anon_sym_end,
      anon_sym_signal,
      anon_sym_and,
      anon_sym_or,
      sym_identifier,
  [877] = 3,
    ACTIONS(133), 2,
      anon_sym_and,
      anon_sym_or,
    ACTIONS(158), 2,
      sym_comment,
      anon_sym_COMMA,
    ACTIONS(160), 4,
      anon_sym_component,
      anon_sym_end,
      anon_sym_signal,
      sym_identifier,
  [892] = 2,
    ACTIONS(137), 3,
      anon_sym_component,
      anon_sym_signal,
      sym_identifier,
    ACTIONS(135), 5,
      ts_builtin_sym_end,
      sym_comment,
      anon_sym_RPAREN,
      anon_sym_LT_EQ,
      anon_sym_COMMA,
  [905] = 2,
    ACTIONS(162), 2,
      sym_comment,
      anon_sym_COMMA,
    ACTIONS(164), 6,
      anon_sym_component,
      anon_sym_end,
      anon_sym_signal,
      anon_sym_and,
      anon_sym_or,
      sym_identifier,
  [918] = 4,
    ACTIONS(170), 1,
      anon_sym_COMMA,
    STATE(45), 1,
      aux_sym_declaration_left_list_repeat1,
    ACTIONS(166), 3,
      ts_builtin_sym_end,
      sym_comment,
      anon_sym_LT_EQ,
    ACTIONS(168), 3,
      anon_sym_component,
      anon_sym_signal,
      sym_identifier,
  [935] = 4,
    ACTIONS(172), 1,
      anon_sym_COMMA,
    STATE(52), 1,
      aux_sym_declaration_left_list_repeat1,
    ACTIONS(166), 2,
      sym_comment,
      anon_sym_LT_EQ,
    ACTIONS(168), 4,
      anon_sym_component,
      anon_sym_end,
      anon_sym_signal,
      sym_identifier,
  [952] = 2,
    ACTIONS(174), 3,
      ts_builtin_sym_end,
      sym_comment,
      anon_sym_COMMA,
    ACTIONS(176), 5,
      anon_sym_component,
      anon_sym_signal,
      anon_sym_and,
      anon_sym_or,
      sym_identifier,
  [965] = 2,
    ACTIONS(178), 2,
      sym_comment,
      anon_sym_COMMA,
    ACTIONS(180), 6,
      anon_sym_component,
      anon_sym_end,
      anon_sym_signal,
      anon_sym_and,
      anon_sym_or,
      sym_identifier,
  [978] = 4,
    ACTIONS(170), 1,
      anon_sym_COMMA,
    STATE(32), 1,
      aux_sym_declaration_left_list_repeat1,
    ACTIONS(182), 3,
      ts_builtin_sym_end,
      sym_comment,
      anon_sym_LT_EQ,
    ACTIONS(184), 3,
      anon_sym_component,
      anon_sym_signal,
      sym_identifier,
  [995] = 3,
    ACTIONS(154), 2,
      anon_sym_and,
      anon_sym_or,
    ACTIONS(158), 3,
      ts_builtin_sym_end,
      sym_comment,
      anon_sym_COMMA,
    ACTIONS(160), 3,
      anon_sym_component,
      anon_sym_signal,
      sym_identifier,
  [1010] = 2,
    ACTIONS(186), 3,
      ts_builtin_sym_end,
      sym_comment,
      anon_sym_COMMA,
    ACTIONS(188), 5,
      anon_sym_component,
      anon_sym_signal,
      anon_sym_and,
      anon_sym_or,
      sym_identifier,
  [1023] = 4,
    ACTIONS(190), 1,
      anon_sym_COMMA,
    STATE(48), 1,
      aux_sym_declaration_left_list_repeat1,
    ACTIONS(135), 2,
      sym_comment,
      anon_sym_LT_EQ,
    ACTIONS(137), 4,
      anon_sym_component,
      anon_sym_end,
      anon_sym_signal,
      sym_identifier,
  [1040] = 2,
    ACTIONS(162), 3,
      ts_builtin_sym_end,
      sym_comment,
      anon_sym_COMMA,
    ACTIONS(164), 5,
      anon_sym_component,
      anon_sym_signal,
      anon_sym_and,
      anon_sym_or,
      sym_identifier,
  [1053] = 2,
    ACTIONS(174), 2,
      sym_comment,
      anon_sym_COMMA,
    ACTIONS(176), 6,
      anon_sym_component,
      anon_sym_end,
      anon_sym_signal,
      anon_sym_and,
      anon_sym_or,
      sym_identifier,
  [1066] = 2,
    ACTIONS(178), 3,
      ts_builtin_sym_end,
      sym_comment,
      anon_sym_COMMA,
    ACTIONS(180), 5,
      anon_sym_component,
      anon_sym_signal,
      anon_sym_and,
      anon_sym_or,
      sym_identifier,
  [1079] = 4,
    ACTIONS(172), 1,
      anon_sym_COMMA,
    STATE(48), 1,
      aux_sym_declaration_left_list_repeat1,
    ACTIONS(182), 2,
      sym_comment,
      anon_sym_LT_EQ,
    ACTIONS(184), 4,
      anon_sym_component,
      anon_sym_end,
      anon_sym_signal,
      sym_identifier,
  [1096] = 2,
    ACTIONS(186), 2,
      sym_comment,
      anon_sym_COMMA,
    ACTIONS(188), 6,
      anon_sym_component,
      anon_sym_end,
      anon_sym_signal,
      anon_sym_and,
      anon_sym_or,
      sym_identifier,
  [1109] = 4,
    ACTIONS(131), 1,
      anon_sym_COMMA,
    ACTIONS(193), 1,
      sym_comment,
    STATE(55), 1,
      aux_sym_declaration_right_list_repeat1,
    ACTIONS(195), 4,
      anon_sym_component,
      anon_sym_end,
      anon_sym_signal,
      sym_identifier,
  [1125] = 4,
    ACTIONS(158), 1,
      sym_comment,
    ACTIONS(197), 1,
      anon_sym_COMMA,
    STATE(55), 1,
      aux_sym_declaration_right_list_repeat1,
    ACTIONS(160), 4,
      anon_sym_component,
      anon_sym_end,
      anon_sym_signal,
      sym_identifier,
  [1141] = 4,
    ACTIONS(172), 1,
      anon_sym_COMMA,
    ACTIONS(200), 1,
      sym_comment,
    STATE(48), 1,
      aux_sym_declaration_left_list_repeat1,
    ACTIONS(202), 4,
      anon_sym_component,
      anon_sym_end,
      anon_sym_signal,
      sym_identifier,
  [1157] = 2,
    ACTIONS(135), 3,
      sym_comment,
      anon_sym_LT_EQ,
      anon_sym_COMMA,
    ACTIONS(137), 4,
      anon_sym_component,
      anon_sym_end,
      anon_sym_signal,
      sym_identifier,
  [1169] = 4,
    ACTIONS(204), 1,
      anon_sym_COMMA,
    STATE(58), 1,
      aux_sym_declaration_right_list_repeat1,
    ACTIONS(158), 2,
      ts_builtin_sym_end,
      sym_comment,
    ACTIONS(160), 3,
      anon_sym_component,
      anon_sym_signal,
      sym_identifier,
  [1185] = 4,
    ACTIONS(152), 1,
      anon_sym_COMMA,
    STATE(58), 1,
      aux_sym_declaration_right_list_repeat1,
    ACTIONS(193), 2,
      ts_builtin_sym_end,
      sym_comment,
    ACTIONS(195), 3,
      anon_sym_component,
      anon_sym_signal,
      sym_identifier,
  [1201] = 4,
    ACTIONS(131), 1,
      anon_sym_COMMA,
    ACTIONS(207), 1,
      sym_comment,
    STATE(55), 1,
      aux_sym_declaration_right_list_repeat1,
    ACTIONS(209), 4,
      anon_sym_component,
      anon_sym_end,
      anon_sym_signal,
      sym_identifier,
  [1217] = 4,
    ACTIONS(172), 1,
      anon_sym_COMMA,
    ACTIONS(211), 1,
      sym_comment,
    STATE(56), 1,
      aux_sym_declaration_left_list_repeat1,
    ACTIONS(213), 4,
      anon_sym_component,
      anon_sym_end,
      anon_sym_signal,
      sym_identifier,
  [1233] = 4,
    ACTIONS(152), 1,
      anon_sym_COMMA,
    STATE(58), 1,
      aux_sym_declaration_right_list_repeat1,
    ACTIONS(207), 2,
      ts_builtin_sym_end,
      sym_comment,
    ACTIONS(209), 3,
      anon_sym_component,
      anon_sym_signal,
      sym_identifier,
  [1249] = 3,
    ACTIONS(215), 1,
      sym_comment,
    STATE(64), 1,
      aux_sym__comments_repeat1,
    ACTIONS(217), 4,
      anon_sym_component,
      anon_sym_end,
      anon_sym_signal,
      sym_identifier,
  [1262] = 3,
    ACTIONS(219), 1,
      sym_comment,
    STATE(64), 1,
      aux_sym__comments_repeat1,
    ACTIONS(222), 4,
      anon_sym_component,
      anon_sym_end,
      anon_sym_signal,
      sym_identifier,
  [1275] = 4,
    ACTIONS(224), 1,
      ts_builtin_sym_end,
    ACTIONS(226), 1,
      sym_comment,
    STATE(67), 1,
      aux_sym__comments_repeat1,
    ACTIONS(217), 3,
      anon_sym_component,
      anon_sym_signal,
      sym_identifier,
  [1290] = 3,
    ACTIONS(232), 1,
      anon_sym_LT_EQ,
    ACTIONS(228), 2,
      ts_builtin_sym_end,
      sym_comment,
    ACTIONS(230), 3,
      anon_sym_component,
      anon_sym_signal,
      sym_identifier,
  [1303] = 4,
    ACTIONS(234), 1,
      ts_builtin_sym_end,
    ACTIONS(236), 1,
      sym_comment,
    STATE(67), 1,
      aux_sym__comments_repeat1,
    ACTIONS(222), 3,
      anon_sym_component,
      anon_sym_signal,
      sym_identifier,
  [1318] = 3,
    ACTIONS(228), 1,
      sym_comment,
    ACTIONS(239), 1,
      anon_sym_LT_EQ,
    ACTIONS(230), 4,
      anon_sym_component,
      anon_sym_end,
      anon_sym_signal,
      sym_identifier,
  [1331] = 2,
    ACTIONS(241), 1,
      sym_comment,
    ACTIONS(243), 4,
      anon_sym_component,
      anon_sym_end,
      anon_sym_signal,
      sym_identifier,
  [1341] = 2,
    ACTIONS(245), 2,
      ts_builtin_sym_end,
      sym_comment,
    ACTIONS(247), 3,
      anon_sym_component,
      anon_sym_signal,
      sym_identifier,
  [1351] = 2,
    ACTIONS(249), 1,
      anon_sym_LPAREN,
    ACTIONS(142), 4,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_and,
      anon_sym_or,
  [1361] = 2,
    ACTIONS(251), 1,
      sym_comment,
    ACTIONS(253), 4,
      anon_sym_component,
      anon_sym_end,
      anon_sym_signal,
      sym_identifier,
  [1371] = 2,
    ACTIONS(255), 1,
      sym_comment,
    ACTIONS(257), 4,
      anon_sym_component,
      anon_sym_end,
      anon_sym_signal,
      sym_identifier,
  [1381] = 2,
    ACTIONS(241), 2,
      ts_builtin_sym_end,
      sym_comment,
    ACTIONS(243), 3,
      anon_sym_component,
      anon_sym_signal,
      sym_identifier,
  [1391] = 2,
    ACTIONS(259), 1,
      sym_comment,
    ACTIONS(261), 4,
      anon_sym_component,
      anon_sym_end,
      anon_sym_signal,
      sym_identifier,
  [1401] = 2,
    ACTIONS(251), 2,
      ts_builtin_sym_end,
      sym_comment,
    ACTIONS(253), 3,
      anon_sym_component,
      anon_sym_signal,
      sym_identifier,
  [1411] = 2,
    ACTIONS(255), 2,
      ts_builtin_sym_end,
      sym_comment,
    ACTIONS(257), 3,
      anon_sym_component,
      anon_sym_signal,
      sym_identifier,
  [1421] = 4,
    ACTIONS(263), 1,
      anon_sym_RPAREN,
    ACTIONS(265), 1,
      anon_sym_COMMA,
    STATE(96), 1,
      aux_sym_declaration_right_list_repeat1,
    ACTIONS(267), 2,
      anon_sym_and,
      anon_sym_or,
  [1435] = 2,
    ACTIONS(245), 1,
      sym_comment,
    ACTIONS(247), 4,
      anon_sym_component,
      anon_sym_end,
      anon_sym_signal,
      sym_identifier,
  [1445] = 1,
    ACTIONS(178), 4,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_and,
      anon_sym_or,
  [1452] = 1,
    ACTIONS(186), 4,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_and,
      anon_sym_or,
  [1459] = 2,
    ACTIONS(158), 2,
      anon_sym_RPAREN,
      anon_sym_COMMA,
    ACTIONS(267), 2,
      anon_sym_and,
      anon_sym_or,
  [1468] = 1,
    ACTIONS(174), 4,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_and,
      anon_sym_or,
  [1475] = 1,
    ACTIONS(162), 4,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_and,
      anon_sym_or,
  [1482] = 3,
    ACTIONS(158), 1,
      anon_sym_RPAREN,
    ACTIONS(269), 1,
      anon_sym_COMMA,
    STATE(85), 1,
      aux_sym_declaration_right_list_repeat1,
  [1492] = 2,
    ACTIONS(272), 1,
      anon_sym_RPAREN,
    ACTIONS(267), 2,
      anon_sym_and,
      anon_sym_or,
  [1500] = 3,
    ACTIONS(274), 1,
      sym_identifier,
    STATE(100), 1,
      sym__identifiers,
    STATE(115), 1,
      sym_component_inputs,
  [1510] = 3,
    ACTIONS(276), 1,
      sym_identifier,
    STATE(2), 1,
      sym_component_outputs,
    STATE(75), 1,
      sym__identifiers,
  [1520] = 3,
    ACTIONS(170), 1,
      anon_sym_COMMA,
    ACTIONS(200), 1,
      anon_sym_RPAREN,
    STATE(32), 1,
      aux_sym_declaration_left_list_repeat1,
  [1530] = 2,
    ACTIONS(278), 1,
      anon_sym_RPAREN,
    ACTIONS(267), 2,
      anon_sym_and,
      anon_sym_or,
  [1538] = 3,
    ACTIONS(170), 1,
      anon_sym_COMMA,
    ACTIONS(280), 1,
      anon_sym_LT_EQ,
    STATE(97), 1,
      aux_sym_declaration_left_list_repeat1,
  [1548] = 3,
    ACTIONS(170), 1,
      anon_sym_COMMA,
    ACTIONS(211), 1,
      anon_sym_RPAREN,
    STATE(89), 1,
      aux_sym_declaration_left_list_repeat1,
  [1558] = 3,
    ACTIONS(276), 1,
      sym_identifier,
    STATE(3), 1,
      sym_component_outputs,
    STATE(75), 1,
      sym__identifiers,
  [1568] = 2,
    ACTIONS(282), 1,
      sym_identifier,
    STATE(68), 2,
      sym__declaration_left,
      sym_declaration_left_list,
  [1576] = 3,
    ACTIONS(274), 1,
      sym_identifier,
    STATE(100), 1,
      sym__identifiers,
    STATE(101), 1,
      sym_component_inputs,
  [1586] = 3,
    ACTIONS(265), 1,
      anon_sym_COMMA,
    ACTIONS(284), 1,
      anon_sym_RPAREN,
    STATE(85), 1,
      aux_sym_declaration_right_list_repeat1,
  [1596] = 3,
    ACTIONS(170), 1,
      anon_sym_COMMA,
    ACTIONS(286), 1,
      anon_sym_LT_EQ,
    STATE(32), 1,
      aux_sym_declaration_left_list_repeat1,
  [1606] = 2,
    ACTIONS(288), 1,
      anon_sym_RPAREN,
    ACTIONS(267), 2,
      anon_sym_and,
      anon_sym_or,
  [1614] = 2,
    ACTIONS(290), 1,
      sym_identifier,
    STATE(66), 2,
      sym__declaration_left,
      sym_declaration_left_list,
  [1622] = 1,
    ACTIONS(292), 1,
      anon_sym_RPAREN,
  [1626] = 1,
    ACTIONS(294), 1,
      anon_sym_RPAREN,
  [1630] = 1,
    ACTIONS(296), 1,
      anon_sym_RPAREN,
  [1634] = 1,
    ACTIONS(298), 1,
      anon_sym_LPAREN,
  [1638] = 1,
    ACTIONS(300), 1,
      anon_sym_end,
  [1642] = 1,
    ACTIONS(302), 1,
      sym_identifier,
  [1646] = 1,
    ACTIONS(304), 1,
      sym_identifier,
  [1650] = 1,
    ACTIONS(306), 1,
      anon_sym_RPAREN,
  [1654] = 1,
    ACTIONS(308), 1,
      anon_sym_LT_EQ,
  [1658] = 1,
    ACTIONS(310), 1,
      anon_sym_LT_EQ,
  [1662] = 1,
    ACTIONS(312), 1,
      ts_builtin_sym_end,
  [1666] = 1,
    ACTIONS(314), 1,
      sym_identifier,
  [1670] = 1,
    ACTIONS(316), 1,
      anon_sym_EQ_GT,
  [1674] = 1,
    ACTIONS(318), 1,
      anon_sym_RPAREN,
  [1678] = 1,
    ACTIONS(320), 1,
      anon_sym_EQ_GT,
  [1682] = 1,
    ACTIONS(322), 1,
      anon_sym_RPAREN,
  [1686] = 1,
    ACTIONS(324), 1,
      anon_sym_end,
  [1690] = 1,
    ACTIONS(326), 1,
      anon_sym_LPAREN,
  [1694] = 1,
    ACTIONS(328), 1,
      sym_identifier,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 38,
  [SMALL_STATE(4)] = 76,
  [SMALL_STATE(5)] = 111,
  [SMALL_STATE(6)] = 146,
  [SMALL_STATE(7)] = 181,
  [SMALL_STATE(8)] = 216,
  [SMALL_STATE(9)] = 241,
  [SMALL_STATE(10)] = 266,
  [SMALL_STATE(11)] = 291,
  [SMALL_STATE(12)] = 316,
  [SMALL_STATE(13)] = 343,
  [SMALL_STATE(14)] = 370,
  [SMALL_STATE(15)] = 395,
  [SMALL_STATE(16)] = 420,
  [SMALL_STATE(17)] = 445,
  [SMALL_STATE(18)] = 470,
  [SMALL_STATE(19)] = 495,
  [SMALL_STATE(20)] = 516,
  [SMALL_STATE(21)] = 537,
  [SMALL_STATE(22)] = 558,
  [SMALL_STATE(23)] = 579,
  [SMALL_STATE(24)] = 600,
  [SMALL_STATE(25)] = 621,
  [SMALL_STATE(26)] = 642,
  [SMALL_STATE(27)] = 663,
  [SMALL_STATE(28)] = 684,
  [SMALL_STATE(29)] = 705,
  [SMALL_STATE(30)] = 726,
  [SMALL_STATE(31)] = 747,
  [SMALL_STATE(32)] = 767,
  [SMALL_STATE(33)] = 785,
  [SMALL_STATE(34)] = 801,
  [SMALL_STATE(35)] = 821,
  [SMALL_STATE(36)] = 841,
  [SMALL_STATE(37)] = 861,
  [SMALL_STATE(38)] = 877,
  [SMALL_STATE(39)] = 892,
  [SMALL_STATE(40)] = 905,
  [SMALL_STATE(41)] = 918,
  [SMALL_STATE(42)] = 935,
  [SMALL_STATE(43)] = 952,
  [SMALL_STATE(44)] = 965,
  [SMALL_STATE(45)] = 978,
  [SMALL_STATE(46)] = 995,
  [SMALL_STATE(47)] = 1010,
  [SMALL_STATE(48)] = 1023,
  [SMALL_STATE(49)] = 1040,
  [SMALL_STATE(50)] = 1053,
  [SMALL_STATE(51)] = 1066,
  [SMALL_STATE(52)] = 1079,
  [SMALL_STATE(53)] = 1096,
  [SMALL_STATE(54)] = 1109,
  [SMALL_STATE(55)] = 1125,
  [SMALL_STATE(56)] = 1141,
  [SMALL_STATE(57)] = 1157,
  [SMALL_STATE(58)] = 1169,
  [SMALL_STATE(59)] = 1185,
  [SMALL_STATE(60)] = 1201,
  [SMALL_STATE(61)] = 1217,
  [SMALL_STATE(62)] = 1233,
  [SMALL_STATE(63)] = 1249,
  [SMALL_STATE(64)] = 1262,
  [SMALL_STATE(65)] = 1275,
  [SMALL_STATE(66)] = 1290,
  [SMALL_STATE(67)] = 1303,
  [SMALL_STATE(68)] = 1318,
  [SMALL_STATE(69)] = 1331,
  [SMALL_STATE(70)] = 1341,
  [SMALL_STATE(71)] = 1351,
  [SMALL_STATE(72)] = 1361,
  [SMALL_STATE(73)] = 1371,
  [SMALL_STATE(74)] = 1381,
  [SMALL_STATE(75)] = 1391,
  [SMALL_STATE(76)] = 1401,
  [SMALL_STATE(77)] = 1411,
  [SMALL_STATE(78)] = 1421,
  [SMALL_STATE(79)] = 1435,
  [SMALL_STATE(80)] = 1445,
  [SMALL_STATE(81)] = 1452,
  [SMALL_STATE(82)] = 1459,
  [SMALL_STATE(83)] = 1468,
  [SMALL_STATE(84)] = 1475,
  [SMALL_STATE(85)] = 1482,
  [SMALL_STATE(86)] = 1492,
  [SMALL_STATE(87)] = 1500,
  [SMALL_STATE(88)] = 1510,
  [SMALL_STATE(89)] = 1520,
  [SMALL_STATE(90)] = 1530,
  [SMALL_STATE(91)] = 1538,
  [SMALL_STATE(92)] = 1548,
  [SMALL_STATE(93)] = 1558,
  [SMALL_STATE(94)] = 1568,
  [SMALL_STATE(95)] = 1576,
  [SMALL_STATE(96)] = 1586,
  [SMALL_STATE(97)] = 1596,
  [SMALL_STATE(98)] = 1606,
  [SMALL_STATE(99)] = 1614,
  [SMALL_STATE(100)] = 1622,
  [SMALL_STATE(101)] = 1626,
  [SMALL_STATE(102)] = 1630,
  [SMALL_STATE(103)] = 1634,
  [SMALL_STATE(104)] = 1638,
  [SMALL_STATE(105)] = 1642,
  [SMALL_STATE(106)] = 1646,
  [SMALL_STATE(107)] = 1650,
  [SMALL_STATE(108)] = 1654,
  [SMALL_STATE(109)] = 1658,
  [SMALL_STATE(110)] = 1662,
  [SMALL_STATE(111)] = 1666,
  [SMALL_STATE(112)] = 1670,
  [SMALL_STATE(113)] = 1674,
  [SMALL_STATE(114)] = 1678,
  [SMALL_STATE(115)] = 1682,
  [SMALL_STATE(116)] = 1686,
  [SMALL_STATE(117)] = 1690,
  [SMALL_STATE(118)] = 1694,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(111),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(99),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(91),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(118),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(69),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(94),
  [21] = {.entry = {.count = 1, .reusable = false}}, SHIFT(74),
  [23] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_component_body, 1, 0, 0),
  [25] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__source_block, 2, 0, 0), SHIFT_REPEAT(63),
  [28] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__source_block, 2, 0, 0), SHIFT_REPEAT(118),
  [31] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym__source_block, 2, 0, 0),
  [33] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__source_block, 2, 0, 0), SHIFT_REPEAT(94),
  [36] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__source_block, 2, 0, 0), SHIFT_REPEAT(91),
  [39] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [41] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__source_block, 2, 0, 0),
  [43] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__source_block, 2, 0, 0), SHIFT_REPEAT(65),
  [46] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__source_block, 2, 0, 0), SHIFT_REPEAT(111),
  [49] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__source_block, 2, 0, 0), SHIFT_REPEAT(99),
  [52] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__statements_repeat1, 2, 0, 0),
  [54] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__statements_repeat1, 2, 0, 0), SHIFT_REPEAT(111),
  [57] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__statements_repeat1, 2, 0, 0), SHIFT_REPEAT(99),
  [60] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__statements_repeat1, 2, 0, 0), SHIFT_REPEAT(91),
  [63] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [65] = {.entry = {.count = 1, .reusable = false}}, SHIFT(20),
  [67] = {.entry = {.count = 1, .reusable = false}}, SHIFT(71),
  [69] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [71] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__statements, 1, 0, 0),
  [73] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__statements_repeat1, 2, 0, 0), SHIFT_REPEAT(118),
  [76] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym__statements_repeat1, 2, 0, 0),
  [78] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__statements_repeat1, 2, 0, 0), SHIFT_REPEAT(94),
  [81] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__statements, 1, 0, 0),
  [83] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [85] = {.entry = {.count = 1, .reusable = false}}, SHIFT(29),
  [87] = {.entry = {.count = 1, .reusable = false}}, SHIFT(37),
  [89] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [91] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [93] = {.entry = {.count = 1, .reusable = false}}, SHIFT(23),
  [95] = {.entry = {.count = 1, .reusable = false}}, SHIFT(33),
  [97] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [99] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [101] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [103] = {.entry = {.count = 1, .reusable = true}}, SHIFT(82),
  [105] = {.entry = {.count = 1, .reusable = true}}, SHIFT(84),
  [107] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [109] = {.entry = {.count = 1, .reusable = true}}, SHIFT(90),
  [111] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [113] = {.entry = {.count = 1, .reusable = true}}, SHIFT(86),
  [115] = {.entry = {.count = 1, .reusable = true}}, SHIFT(98),
  [117] = {.entry = {.count = 1, .reusable = true}}, SHIFT(81),
  [119] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [121] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [123] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [125] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [127] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__assignment_right, 1, 0, 0),
  [129] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__assignment_right, 1, 0, 0),
  [131] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [133] = {.entry = {.count = 1, .reusable = false}}, SHIFT(27),
  [135] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_declaration_left_list_repeat1, 2, 0, 0),
  [137] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_declaration_left_list_repeat1, 2, 0, 0),
  [139] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_declaration_left_list_repeat1, 2, 0, 0), SHIFT_REPEAT(105),
  [142] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__atomic, 1, 0, 0),
  [144] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__atomic, 1, 0, 0),
  [146] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [148] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__declaration_right, 1, 0, 0),
  [150] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__declaration_right, 1, 0, 0),
  [152] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [154] = {.entry = {.count = 1, .reusable = false}}, SHIFT(21),
  [156] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [158] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_declaration_right_list_repeat1, 2, 0, 0),
  [160] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_declaration_right_list_repeat1, 2, 0, 0),
  [162] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression_unary, 2, 0, 4),
  [164] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expression_unary, 2, 0, 4),
  [166] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__declaration_left, 1, 0, 0),
  [168] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__declaration_left, 1, 0, 0),
  [170] = {.entry = {.count = 1, .reusable = true}}, SHIFT(105),
  [172] = {.entry = {.count = 1, .reusable = true}}, SHIFT(106),
  [174] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__expression_primary, 3, 0, 0),
  [176] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__expression_primary, 3, 0, 0),
  [178] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression_component, 4, 0, 5),
  [180] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expression_component, 4, 0, 5),
  [182] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_declaration_left_list, 2, 0, 0),
  [184] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_declaration_left_list, 2, 0, 0),
  [186] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression_binary, 3, 0, 2),
  [188] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expression_binary, 3, 0, 2),
  [190] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_declaration_left_list_repeat1, 2, 0, 0), SHIFT_REPEAT(106),
  [193] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_assignment_right_list, 2, 0, 0),
  [195] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_assignment_right_list, 2, 0, 0),
  [197] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_declaration_right_list_repeat1, 2, 0, 0), SHIFT_REPEAT(28),
  [200] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__identifiers, 2, 0, 0),
  [202] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__identifiers, 2, 0, 0),
  [204] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_declaration_right_list_repeat1, 2, 0, 0), SHIFT_REPEAT(30),
  [207] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_declaration_right_list, 2, 0, 0),
  [209] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_declaration_right_list, 2, 0, 0),
  [211] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__identifiers, 1, 0, 0),
  [213] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__identifiers, 1, 0, 0),
  [215] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [217] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__comments, 1, 0, 0),
  [219] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__comments_repeat1, 2, 0, 0), SHIFT_REPEAT(64),
  [222] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym__comments_repeat1, 2, 0, 0),
  [224] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__comments, 1, 0, 0),
  [226] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [228] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_declaration, 2, 0, 1),
  [230] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_declaration, 2, 0, 1),
  [232] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [234] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__comments_repeat1, 2, 0, 0),
  [236] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__comments_repeat1, 2, 0, 0), SHIFT_REPEAT(67),
  [239] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [241] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_component, 8, 0, 6),
  [243] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_component, 8, 0, 6),
  [245] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_component, 9, 0, 7),
  [247] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_component, 9, 0, 7),
  [249] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [251] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_assignment, 3, 0, 2),
  [253] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_assignment, 3, 0, 2),
  [255] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_declaration, 4, 0, 3),
  [257] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_declaration, 4, 0, 3),
  [259] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_component_outputs, 1, 0, 0),
  [261] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_component_outputs, 1, 0, 0),
  [263] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__expression_component_input, 1, 0, 0),
  [265] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [267] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [269] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_declaration_right_list_repeat1, 2, 0, 0), SHIFT_REPEAT(19),
  [272] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [274] = {.entry = {.count = 1, .reusable = true}}, SHIFT(92),
  [276] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [278] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [280] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__assignment_left, 1, 0, 0),
  [282] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [284] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression_component_input_list, 2, 0, 0),
  [286] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_assignment_left_list, 2, 0, 0),
  [288] = {.entry = {.count = 1, .reusable = true}}, SHIFT(83),
  [290] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [292] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_component_inputs, 1, 0, 0),
  [294] = {.entry = {.count = 1, .reusable = true}}, SHIFT(112),
  [296] = {.entry = {.count = 1, .reusable = true}}, SHIFT(80),
  [298] = {.entry = {.count = 1, .reusable = true}}, SHIFT(95),
  [300] = {.entry = {.count = 1, .reusable = true}}, SHIFT(79),
  [302] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [304] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [306] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [308] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [310] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [312] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [314] = {.entry = {.count = 1, .reusable = true}}, SHIFT(103),
  [316] = {.entry = {.count = 1, .reusable = true}}, SHIFT(93),
  [318] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [320] = {.entry = {.count = 1, .reusable = true}}, SHIFT(88),
  [322] = {.entry = {.count = 1, .reusable = true}}, SHIFT(114),
  [324] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [326] = {.entry = {.count = 1, .reusable = true}}, SHIFT(87),
  [328] = {.entry = {.count = 1, .reusable = true}}, SHIFT(117),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_cmdl(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
