#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 125
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 30
#define ALIAS_COUNT 0
#define TOKEN_COUNT 14
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 8
#define MAX_ALIAS_SEQUENCE_LENGTH 9
#define PRODUCTION_ID_COUNT 6

enum ts_symbol_identifiers {
  anon_sym_component = 1,
  anon_sym_LPAREN = 2,
  anon_sym_RPAREN = 3,
  anon_sym_EQ_GT = 4,
  anon_sym_end = 5,
  anon_sym_signal = 6,
  anon_sym_LT_EQ = 7,
  anon_sym_or = 8,
  anon_sym_and = 9,
  anon_sym_not = 10,
  anon_sym_COMMA = 11,
  sym_identifier = 12,
  sym_number = 13,
  sym_source_file = 14,
  sym_statement = 15,
  sym_component = 16,
  sym_declaration = 17,
  sym_assignment = 18,
  sym_definition = 19,
  sym_expression = 20,
  sym_expression_or = 21,
  sym_expression_and = 22,
  sym_expression_not = 23,
  sym_expression_component = 24,
  sym_atomics = 25,
  sym_identifiers = 26,
  aux_sym_source_file_repeat1 = 27,
  aux_sym_atomics_repeat1 = 28,
  aux_sym_identifiers_repeat1 = 29,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_component] = "component",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_EQ_GT] = "=>",
  [anon_sym_end] = "end",
  [anon_sym_signal] = "signal",
  [anon_sym_LT_EQ] = "<=",
  [anon_sym_or] = "or",
  [anon_sym_and] = "and",
  [anon_sym_not] = "not",
  [anon_sym_COMMA] = ",",
  [sym_identifier] = "identifier",
  [sym_number] = "number",
  [sym_source_file] = "source_file",
  [sym_statement] = "statement",
  [sym_component] = "component",
  [sym_declaration] = "declaration",
  [sym_assignment] = "assignment",
  [sym_definition] = "definition",
  [sym_expression] = "expression",
  [sym_expression_or] = "expression_or",
  [sym_expression_and] = "expression_and",
  [sym_expression_not] = "expression_not",
  [sym_expression_component] = "expression_component",
  [sym_atomics] = "atomics",
  [sym_identifiers] = "identifiers",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_atomics_repeat1] = "atomics_repeat1",
  [aux_sym_identifiers_repeat1] = "identifiers_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_component] = anon_sym_component,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_EQ_GT] = anon_sym_EQ_GT,
  [anon_sym_end] = anon_sym_end,
  [anon_sym_signal] = anon_sym_signal,
  [anon_sym_LT_EQ] = anon_sym_LT_EQ,
  [anon_sym_or] = anon_sym_or,
  [anon_sym_and] = anon_sym_and,
  [anon_sym_not] = anon_sym_not,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [sym_identifier] = sym_identifier,
  [sym_number] = sym_number,
  [sym_source_file] = sym_source_file,
  [sym_statement] = sym_statement,
  [sym_component] = sym_component,
  [sym_declaration] = sym_declaration,
  [sym_assignment] = sym_assignment,
  [sym_definition] = sym_definition,
  [sym_expression] = sym_expression,
  [sym_expression_or] = sym_expression_or,
  [sym_expression_and] = sym_expression_and,
  [sym_expression_not] = sym_expression_not,
  [sym_expression_component] = sym_expression_component,
  [sym_atomics] = sym_atomics,
  [sym_identifiers] = sym_identifiers,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_atomics_repeat1] = aux_sym_atomics_repeat1,
  [aux_sym_identifiers_repeat1] = aux_sym_identifiers_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_component] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_end] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_signal] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_or] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_and] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_not] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_component] = {
    .visible = true,
    .named = true,
  },
  [sym_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym_assignment] = {
    .visible = true,
    .named = true,
  },
  [sym_definition] = {
    .visible = true,
    .named = true,
  },
  [sym_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_expression_or] = {
    .visible = true,
    .named = true,
  },
  [sym_expression_and] = {
    .visible = true,
    .named = true,
  },
  [sym_expression_not] = {
    .visible = true,
    .named = true,
  },
  [sym_expression_component] = {
    .visible = true,
    .named = true,
  },
  [sym_atomics] = {
    .visible = true,
    .named = true,
  },
  [sym_identifiers] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_atomics_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_identifiers_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_inputs = 1,
  field_left_and = 2,
  field_left_or = 3,
  field_name = 4,
  field_not = 5,
  field_outputs = 6,
  field_right_and = 7,
  field_right_or = 8,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_inputs] = "inputs",
  [field_left_and] = "left_and",
  [field_left_or] = "left_or",
  [field_name] = "name",
  [field_not] = "not",
  [field_outputs] = "outputs",
  [field_right_and] = "right_and",
  [field_right_or] = "right_or",
};

static const TSFieldMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 2},
  [3] = {.index = 3, .length = 2},
  [4] = {.index = 5, .length = 2},
  [5] = {.index = 7, .length = 3},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_not, 1},
  [1] =
    {field_left_or, 0},
    {field_right_or, 2},
  [3] =
    {field_left_and, 0},
    {field_right_and, 2},
  [5] =
    {field_inputs, 2},
    {field_name, 0},
  [7] =
    {field_inputs, 3},
    {field_name, 1},
    {field_outputs, 6},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 3,
  [6] = 4,
  [7] = 2,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 9,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 13,
  [16] = 16,
  [17] = 12,
  [18] = 10,
  [19] = 14,
  [20] = 14,
  [21] = 10,
  [22] = 16,
  [23] = 16,
  [24] = 9,
  [25] = 25,
  [26] = 26,
  [27] = 25,
  [28] = 28,
  [29] = 29,
  [30] = 29,
  [31] = 26,
  [32] = 32,
  [33] = 28,
  [34] = 34,
  [35] = 34,
  [36] = 36,
  [37] = 37,
  [38] = 36,
  [39] = 32,
  [40] = 37,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 47,
  [52] = 46,
  [53] = 49,
  [54] = 44,
  [55] = 55,
  [56] = 56,
  [57] = 42,
  [58] = 58,
  [59] = 48,
  [60] = 25,
  [61] = 55,
  [62] = 50,
  [63] = 45,
  [64] = 64,
  [65] = 65,
  [66] = 65,
  [67] = 43,
  [68] = 58,
  [69] = 41,
  [70] = 64,
  [71] = 56,
  [72] = 29,
  [73] = 26,
  [74] = 28,
  [75] = 75,
  [76] = 75,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 77,
  [81] = 79,
  [82] = 78,
  [83] = 32,
  [84] = 84,
  [85] = 85,
  [86] = 49,
  [87] = 85,
  [88] = 84,
  [89] = 89,
  [90] = 45,
  [91] = 65,
  [92] = 42,
  [93] = 56,
  [94] = 55,
  [95] = 44,
  [96] = 89,
  [97] = 47,
  [98] = 46,
  [99] = 89,
  [100] = 84,
  [101] = 64,
  [102] = 102,
  [103] = 103,
  [104] = 103,
  [105] = 102,
  [106] = 106,
  [107] = 106,
  [108] = 106,
  [109] = 109,
  [110] = 110,
  [111] = 111,
  [112] = 111,
  [113] = 113,
  [114] = 110,
  [115] = 115,
  [116] = 116,
  [117] = 113,
  [118] = 118,
  [119] = 113,
  [120] = 116,
  [121] = 118,
  [122] = 122,
  [123] = 109,
  [124] = 122,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(13);
      ADVANCE_MAP(
        '(', 15,
        ')', 16,
        ',', 26,
        '<', 5,
        '=', 6,
        'a', 35,
        'c', 40,
        'e', 38,
        'n', 41,
        'o', 44,
        's', 32,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(48);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(47);
      END_STATE();
    case 1:
      if (lookahead == '(') ADVANCE(15);
      if (lookahead == ')') ADVANCE(16);
      if (lookahead == ',') ADVANCE(26);
      if (lookahead == 'a') ADVANCE(8);
      if (lookahead == 'o') ADVANCE(9);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(1);
      END_STATE();
    case 2:
      if (lookahead == '(') ADVANCE(15);
      if (lookahead == ',') ADVANCE(26);
      if (lookahead == 'a') ADVANCE(35);
      if (lookahead == 'c') ADVANCE(40);
      if (lookahead == 'e') ADVANCE(38);
      if (lookahead == 'o') ADVANCE(44);
      if (lookahead == 's') ADVANCE(32);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(2);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(47);
      END_STATE();
    case 3:
      if (lookahead == '(') ADVANCE(15);
      if (lookahead == 'n') ADVANCE(41);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(3);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(48);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(47);
      END_STATE();
    case 4:
      if (lookahead == ',') ADVANCE(26);
      if (lookahead == '<') ADVANCE(5);
      if (lookahead == 'c') ADVANCE(40);
      if (lookahead == 'e') ADVANCE(38);
      if (lookahead == 's') ADVANCE(32);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(4);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(47);
      END_STATE();
    case 5:
      if (lookahead == '=') ADVANCE(20);
      END_STATE();
    case 6:
      if (lookahead == '>') ADVANCE(17);
      END_STATE();
    case 7:
      if (lookahead == 'd') ADVANCE(23);
      END_STATE();
    case 8:
      if (lookahead == 'n') ADVANCE(7);
      END_STATE();
    case 9:
      if (lookahead == 'r') ADVANCE(21);
      END_STATE();
    case 10:
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(10);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(48);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(47);
      END_STATE();
    case 11:
      if (eof) ADVANCE(13);
      if (lookahead == '(') ADVANCE(15);
      if (lookahead == ')') ADVANCE(16);
      if (lookahead == ',') ADVANCE(26);
      if (lookahead == 'a') ADVANCE(35);
      if (lookahead == 'c') ADVANCE(40);
      if (lookahead == 'o') ADVANCE(44);
      if (lookahead == 's') ADVANCE(32);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(11);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(47);
      END_STATE();
    case 12:
      if (eof) ADVANCE(13);
      if (lookahead == ',') ADVANCE(26);
      if (lookahead == '<') ADVANCE(5);
      if (lookahead == 'c') ADVANCE(40);
      if (lookahead == 's') ADVANCE(32);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(12);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(47);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_component);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(47);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_EQ_GT);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_end);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(47);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_signal);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(47);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_LT_EQ);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_or);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_or);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(47);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_and);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_and);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(47);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_not);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(47);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'a') ADVANCE(33);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(47);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'd') ADVANCE(24);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(47);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'd') ADVANCE(18);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(47);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(39);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(47);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'g') ADVANCE(36);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(47);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'i') ADVANCE(31);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(47);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'l') ADVANCE(19);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(47);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'm') ADVANCE(43);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(47);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'n') ADVANCE(28);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(47);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'n') ADVANCE(27);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(47);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'n') ADVANCE(30);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(47);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'n') ADVANCE(29);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(47);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'n') ADVANCE(46);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(47);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'o') ADVANCE(34);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(47);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'o') ADVANCE(45);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(47);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'o') ADVANCE(37);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(47);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'p') ADVANCE(42);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(47);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'r') ADVANCE(22);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(47);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 't') ADVANCE(25);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(47);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 't') ADVANCE(14);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(47);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(47);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(48);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 12},
  [2] = {.lex_state = 4},
  [3] = {.lex_state = 4},
  [4] = {.lex_state = 4},
  [5] = {.lex_state = 12},
  [6] = {.lex_state = 4},
  [7] = {.lex_state = 4},
  [8] = {.lex_state = 12},
  [9] = {.lex_state = 3},
  [10] = {.lex_state = 3},
  [11] = {.lex_state = 3},
  [12] = {.lex_state = 3},
  [13] = {.lex_state = 3},
  [14] = {.lex_state = 3},
  [15] = {.lex_state = 3},
  [16] = {.lex_state = 3},
  [17] = {.lex_state = 3},
  [18] = {.lex_state = 3},
  [19] = {.lex_state = 3},
  [20] = {.lex_state = 3},
  [21] = {.lex_state = 3},
  [22] = {.lex_state = 3},
  [23] = {.lex_state = 3},
  [24] = {.lex_state = 3},
  [25] = {.lex_state = 2},
  [26] = {.lex_state = 11},
  [27] = {.lex_state = 11},
  [28] = {.lex_state = 11},
  [29] = {.lex_state = 11},
  [30] = {.lex_state = 2},
  [31] = {.lex_state = 2},
  [32] = {.lex_state = 11},
  [33] = {.lex_state = 2},
  [34] = {.lex_state = 4},
  [35] = {.lex_state = 12},
  [36] = {.lex_state = 12},
  [37] = {.lex_state = 4},
  [38] = {.lex_state = 4},
  [39] = {.lex_state = 2},
  [40] = {.lex_state = 12},
  [41] = {.lex_state = 11},
  [42] = {.lex_state = 2},
  [43] = {.lex_state = 11},
  [44] = {.lex_state = 2},
  [45] = {.lex_state = 11},
  [46] = {.lex_state = 2},
  [47] = {.lex_state = 2},
  [48] = {.lex_state = 12},
  [49] = {.lex_state = 11},
  [50] = {.lex_state = 11},
  [51] = {.lex_state = 11},
  [52] = {.lex_state = 11},
  [53] = {.lex_state = 2},
  [54] = {.lex_state = 11},
  [55] = {.lex_state = 11},
  [56] = {.lex_state = 11},
  [57] = {.lex_state = 11},
  [58] = {.lex_state = 11},
  [59] = {.lex_state = 4},
  [60] = {.lex_state = 1},
  [61] = {.lex_state = 2},
  [62] = {.lex_state = 2},
  [63] = {.lex_state = 2},
  [64] = {.lex_state = 2},
  [65] = {.lex_state = 2},
  [66] = {.lex_state = 11},
  [67] = {.lex_state = 2},
  [68] = {.lex_state = 2},
  [69] = {.lex_state = 2},
  [70] = {.lex_state = 11},
  [71] = {.lex_state = 2},
  [72] = {.lex_state = 1},
  [73] = {.lex_state = 1},
  [74] = {.lex_state = 1},
  [75] = {.lex_state = 4},
  [76] = {.lex_state = 12},
  [77] = {.lex_state = 4},
  [78] = {.lex_state = 12},
  [79] = {.lex_state = 12},
  [80] = {.lex_state = 12},
  [81] = {.lex_state = 4},
  [82] = {.lex_state = 4},
  [83] = {.lex_state = 1},
  [84] = {.lex_state = 1},
  [85] = {.lex_state = 10},
  [86] = {.lex_state = 1},
  [87] = {.lex_state = 10},
  [88] = {.lex_state = 1},
  [89] = {.lex_state = 10},
  [90] = {.lex_state = 1},
  [91] = {.lex_state = 1},
  [92] = {.lex_state = 1},
  [93] = {.lex_state = 1},
  [94] = {.lex_state = 1},
  [95] = {.lex_state = 1},
  [96] = {.lex_state = 10},
  [97] = {.lex_state = 1},
  [98] = {.lex_state = 1},
  [99] = {.lex_state = 10},
  [100] = {.lex_state = 1},
  [101] = {.lex_state = 1},
  [102] = {.lex_state = 10},
  [103] = {.lex_state = 10},
  [104] = {.lex_state = 10},
  [105] = {.lex_state = 10},
  [106] = {.lex_state = 10},
  [107] = {.lex_state = 10},
  [108] = {.lex_state = 10},
  [109] = {.lex_state = 0},
  [110] = {.lex_state = 0},
  [111] = {.lex_state = 10},
  [112] = {.lex_state = 10},
  [113] = {.lex_state = 0},
  [114] = {.lex_state = 0},
  [115] = {.lex_state = 0},
  [116] = {.lex_state = 0},
  [117] = {.lex_state = 0},
  [118] = {.lex_state = 0},
  [119] = {.lex_state = 0},
  [120] = {.lex_state = 0},
  [121] = {.lex_state = 0},
  [122] = {.lex_state = 10},
  [123] = {.lex_state = 0},
  [124] = {.lex_state = 10},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_component] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_EQ_GT] = ACTIONS(1),
    [anon_sym_end] = ACTIONS(1),
    [anon_sym_signal] = ACTIONS(1),
    [anon_sym_LT_EQ] = ACTIONS(1),
    [anon_sym_or] = ACTIONS(1),
    [anon_sym_and] = ACTIONS(1),
    [anon_sym_not] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
  },
  [1] = {
    [sym_source_file] = STATE(115),
    [sym_statement] = STATE(8),
    [sym_component] = STATE(79),
    [sym_declaration] = STATE(79),
    [sym_assignment] = STATE(79),
    [sym_definition] = STATE(79),
    [sym_identifiers] = STATE(110),
    [aux_sym_source_file_repeat1] = STATE(8),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_component] = ACTIONS(5),
    [anon_sym_signal] = ACTIONS(7),
    [sym_identifier] = ACTIONS(9),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 7,
    ACTIONS(9), 1,
      sym_identifier,
    ACTIONS(11), 1,
      anon_sym_component,
    ACTIONS(13), 1,
      anon_sym_end,
    ACTIONS(15), 1,
      anon_sym_signal,
    STATE(114), 1,
      sym_identifiers,
    STATE(4), 2,
      sym_statement,
      aux_sym_source_file_repeat1,
    STATE(81), 4,
      sym_component,
      sym_declaration,
      sym_assignment,
      sym_definition,
  [26] = 7,
    ACTIONS(17), 1,
      anon_sym_component,
    ACTIONS(20), 1,
      anon_sym_end,
    ACTIONS(22), 1,
      anon_sym_signal,
    ACTIONS(25), 1,
      sym_identifier,
    STATE(114), 1,
      sym_identifiers,
    STATE(3), 2,
      sym_statement,
      aux_sym_source_file_repeat1,
    STATE(81), 4,
      sym_component,
      sym_declaration,
      sym_assignment,
      sym_definition,
  [52] = 7,
    ACTIONS(9), 1,
      sym_identifier,
    ACTIONS(11), 1,
      anon_sym_component,
    ACTIONS(15), 1,
      anon_sym_signal,
    ACTIONS(28), 1,
      anon_sym_end,
    STATE(114), 1,
      sym_identifiers,
    STATE(3), 2,
      sym_statement,
      aux_sym_source_file_repeat1,
    STATE(81), 4,
      sym_component,
      sym_declaration,
      sym_assignment,
      sym_definition,
  [78] = 7,
    ACTIONS(25), 1,
      sym_identifier,
    ACTIONS(30), 1,
      ts_builtin_sym_end,
    ACTIONS(32), 1,
      anon_sym_component,
    ACTIONS(35), 1,
      anon_sym_signal,
    STATE(110), 1,
      sym_identifiers,
    STATE(5), 2,
      sym_statement,
      aux_sym_source_file_repeat1,
    STATE(79), 4,
      sym_component,
      sym_declaration,
      sym_assignment,
      sym_definition,
  [104] = 7,
    ACTIONS(9), 1,
      sym_identifier,
    ACTIONS(11), 1,
      anon_sym_component,
    ACTIONS(15), 1,
      anon_sym_signal,
    ACTIONS(38), 1,
      anon_sym_end,
    STATE(114), 1,
      sym_identifiers,
    STATE(3), 2,
      sym_statement,
      aux_sym_source_file_repeat1,
    STATE(81), 4,
      sym_component,
      sym_declaration,
      sym_assignment,
      sym_definition,
  [130] = 7,
    ACTIONS(9), 1,
      sym_identifier,
    ACTIONS(11), 1,
      anon_sym_component,
    ACTIONS(15), 1,
      anon_sym_signal,
    ACTIONS(40), 1,
      anon_sym_end,
    STATE(114), 1,
      sym_identifiers,
    STATE(6), 2,
      sym_statement,
      aux_sym_source_file_repeat1,
    STATE(81), 4,
      sym_component,
      sym_declaration,
      sym_assignment,
      sym_definition,
  [156] = 7,
    ACTIONS(5), 1,
      anon_sym_component,
    ACTIONS(7), 1,
      anon_sym_signal,
    ACTIONS(9), 1,
      sym_identifier,
    ACTIONS(42), 1,
      ts_builtin_sym_end,
    STATE(110), 1,
      sym_identifiers,
    STATE(5), 2,
      sym_statement,
      aux_sym_source_file_repeat1,
    STATE(79), 4,
      sym_component,
      sym_declaration,
      sym_assignment,
      sym_definition,
  [182] = 10,
    ACTIONS(44), 1,
      anon_sym_LPAREN,
    ACTIONS(46), 1,
      anon_sym_not,
    ACTIONS(48), 1,
      sym_identifier,
    ACTIONS(50), 1,
      sym_number,
    STATE(45), 1,
      sym_expression,
    STATE(55), 1,
      sym_expression_or,
    STATE(56), 1,
      sym_expression_and,
    STATE(57), 1,
      sym_expression_not,
    STATE(66), 1,
      sym_expression_component,
    STATE(70), 1,
      sym_atomics,
  [213] = 10,
    ACTIONS(52), 1,
      anon_sym_LPAREN,
    ACTIONS(54), 1,
      anon_sym_not,
    ACTIONS(56), 1,
      sym_identifier,
    ACTIONS(58), 1,
      sym_number,
    STATE(42), 1,
      sym_expression_not,
    STATE(47), 1,
      sym_expression,
    STATE(61), 1,
      sym_expression_or,
    STATE(64), 1,
      sym_atomics,
    STATE(65), 1,
      sym_expression_component,
    STATE(71), 1,
      sym_expression_and,
  [244] = 10,
    ACTIONS(60), 1,
      anon_sym_LPAREN,
    ACTIONS(62), 1,
      anon_sym_not,
    ACTIONS(64), 1,
      sym_identifier,
    ACTIONS(66), 1,
      sym_number,
    STATE(90), 1,
      sym_expression,
    STATE(91), 1,
      sym_expression_component,
    STATE(92), 1,
      sym_expression_not,
    STATE(93), 1,
      sym_expression_and,
    STATE(94), 1,
      sym_expression_or,
    STATE(101), 1,
      sym_atomics,
  [275] = 10,
    ACTIONS(52), 1,
      anon_sym_LPAREN,
    ACTIONS(54), 1,
      anon_sym_not,
    ACTIONS(56), 1,
      sym_identifier,
    ACTIONS(58), 1,
      sym_number,
    STATE(42), 1,
      sym_expression_not,
    STATE(61), 1,
      sym_expression_or,
    STATE(65), 1,
      sym_expression_component,
    STATE(68), 1,
      sym_expression,
    STATE(69), 1,
      sym_atomics,
    STATE(71), 1,
      sym_expression_and,
  [306] = 10,
    ACTIONS(52), 1,
      anon_sym_LPAREN,
    ACTIONS(54), 1,
      anon_sym_not,
    ACTIONS(56), 1,
      sym_identifier,
    ACTIONS(58), 1,
      sym_number,
    STATE(42), 1,
      sym_expression_not,
    STATE(61), 1,
      sym_expression_or,
    STATE(62), 1,
      sym_expression,
    STATE(65), 1,
      sym_expression_component,
    STATE(67), 1,
      sym_atomics,
    STATE(71), 1,
      sym_expression_and,
  [337] = 10,
    ACTIONS(60), 1,
      anon_sym_LPAREN,
    ACTIONS(62), 1,
      anon_sym_not,
    ACTIONS(64), 1,
      sym_identifier,
    ACTIONS(66), 1,
      sym_number,
    STATE(91), 1,
      sym_expression_component,
    STATE(92), 1,
      sym_expression_not,
    STATE(93), 1,
      sym_expression_and,
    STATE(94), 1,
      sym_expression_or,
    STATE(100), 1,
      sym_expression,
    STATE(101), 1,
      sym_atomics,
  [368] = 10,
    ACTIONS(44), 1,
      anon_sym_LPAREN,
    ACTIONS(46), 1,
      anon_sym_not,
    ACTIONS(48), 1,
      sym_identifier,
    ACTIONS(50), 1,
      sym_number,
    STATE(43), 1,
      sym_atomics,
    STATE(50), 1,
      sym_expression,
    STATE(55), 1,
      sym_expression_or,
    STATE(56), 1,
      sym_expression_and,
    STATE(57), 1,
      sym_expression_not,
    STATE(66), 1,
      sym_expression_component,
  [399] = 10,
    ACTIONS(44), 1,
      anon_sym_LPAREN,
    ACTIONS(46), 1,
      anon_sym_not,
    ACTIONS(48), 1,
      sym_identifier,
    ACTIONS(50), 1,
      sym_number,
    STATE(52), 1,
      sym_expression,
    STATE(55), 1,
      sym_expression_or,
    STATE(56), 1,
      sym_expression_and,
    STATE(57), 1,
      sym_expression_not,
    STATE(66), 1,
      sym_expression_component,
    STATE(70), 1,
      sym_atomics,
  [430] = 10,
    ACTIONS(44), 1,
      anon_sym_LPAREN,
    ACTIONS(46), 1,
      anon_sym_not,
    ACTIONS(48), 1,
      sym_identifier,
    ACTIONS(50), 1,
      sym_number,
    STATE(41), 1,
      sym_atomics,
    STATE(55), 1,
      sym_expression_or,
    STATE(56), 1,
      sym_expression_and,
    STATE(57), 1,
      sym_expression_not,
    STATE(58), 1,
      sym_expression,
    STATE(66), 1,
      sym_expression_component,
  [461] = 10,
    ACTIONS(44), 1,
      anon_sym_LPAREN,
    ACTIONS(46), 1,
      anon_sym_not,
    ACTIONS(48), 1,
      sym_identifier,
    ACTIONS(50), 1,
      sym_number,
    STATE(51), 1,
      sym_expression,
    STATE(55), 1,
      sym_expression_or,
    STATE(56), 1,
      sym_expression_and,
    STATE(57), 1,
      sym_expression_not,
    STATE(66), 1,
      sym_expression_component,
    STATE(70), 1,
      sym_atomics,
  [492] = 10,
    ACTIONS(60), 1,
      anon_sym_LPAREN,
    ACTIONS(62), 1,
      anon_sym_not,
    ACTIONS(64), 1,
      sym_identifier,
    ACTIONS(66), 1,
      sym_number,
    STATE(84), 1,
      sym_expression,
    STATE(91), 1,
      sym_expression_component,
    STATE(92), 1,
      sym_expression_not,
    STATE(93), 1,
      sym_expression_and,
    STATE(94), 1,
      sym_expression_or,
    STATE(101), 1,
      sym_atomics,
  [523] = 10,
    ACTIONS(60), 1,
      anon_sym_LPAREN,
    ACTIONS(62), 1,
      anon_sym_not,
    ACTIONS(64), 1,
      sym_identifier,
    ACTIONS(66), 1,
      sym_number,
    STATE(88), 1,
      sym_expression,
    STATE(91), 1,
      sym_expression_component,
    STATE(92), 1,
      sym_expression_not,
    STATE(93), 1,
      sym_expression_and,
    STATE(94), 1,
      sym_expression_or,
    STATE(101), 1,
      sym_atomics,
  [554] = 10,
    ACTIONS(60), 1,
      anon_sym_LPAREN,
    ACTIONS(62), 1,
      anon_sym_not,
    ACTIONS(64), 1,
      sym_identifier,
    ACTIONS(66), 1,
      sym_number,
    STATE(91), 1,
      sym_expression_component,
    STATE(92), 1,
      sym_expression_not,
    STATE(93), 1,
      sym_expression_and,
    STATE(94), 1,
      sym_expression_or,
    STATE(97), 1,
      sym_expression,
    STATE(101), 1,
      sym_atomics,
  [585] = 10,
    ACTIONS(60), 1,
      anon_sym_LPAREN,
    ACTIONS(62), 1,
      anon_sym_not,
    ACTIONS(64), 1,
      sym_identifier,
    ACTIONS(66), 1,
      sym_number,
    STATE(91), 1,
      sym_expression_component,
    STATE(92), 1,
      sym_expression_not,
    STATE(93), 1,
      sym_expression_and,
    STATE(94), 1,
      sym_expression_or,
    STATE(98), 1,
      sym_expression,
    STATE(101), 1,
      sym_atomics,
  [616] = 10,
    ACTIONS(52), 1,
      anon_sym_LPAREN,
    ACTIONS(54), 1,
      anon_sym_not,
    ACTIONS(56), 1,
      sym_identifier,
    ACTIONS(58), 1,
      sym_number,
    STATE(42), 1,
      sym_expression_not,
    STATE(46), 1,
      sym_expression,
    STATE(61), 1,
      sym_expression_or,
    STATE(64), 1,
      sym_atomics,
    STATE(65), 1,
      sym_expression_component,
    STATE(71), 1,
      sym_expression_and,
  [647] = 10,
    ACTIONS(52), 1,
      anon_sym_LPAREN,
    ACTIONS(54), 1,
      anon_sym_not,
    ACTIONS(56), 1,
      sym_identifier,
    ACTIONS(58), 1,
      sym_number,
    STATE(42), 1,
      sym_expression_not,
    STATE(61), 1,
      sym_expression_or,
    STATE(63), 1,
      sym_expression,
    STATE(64), 1,
      sym_atomics,
    STATE(65), 1,
      sym_expression_component,
    STATE(71), 1,
      sym_expression_and,
  [678] = 4,
    ACTIONS(70), 1,
      anon_sym_LPAREN,
    ACTIONS(72), 1,
      anon_sym_COMMA,
    STATE(30), 1,
      aux_sym_atomics_repeat1,
    ACTIONS(68), 6,
      anon_sym_component,
      anon_sym_end,
      anon_sym_signal,
      anon_sym_or,
      anon_sym_and,
      sym_identifier,
  [696] = 4,
    ACTIONS(76), 1,
      anon_sym_COMMA,
    STATE(29), 1,
      aux_sym_atomics_repeat1,
    ACTIONS(74), 2,
      ts_builtin_sym_end,
      anon_sym_RPAREN,
    ACTIONS(68), 5,
      anon_sym_component,
      anon_sym_signal,
      anon_sym_or,
      anon_sym_and,
      sym_identifier,
  [714] = 5,
    ACTIONS(74), 1,
      ts_builtin_sym_end,
    ACTIONS(76), 1,
      anon_sym_COMMA,
    ACTIONS(78), 1,
      anon_sym_LPAREN,
    STATE(29), 1,
      aux_sym_atomics_repeat1,
    ACTIONS(68), 5,
      anon_sym_component,
      anon_sym_signal,
      anon_sym_or,
      anon_sym_and,
      sym_identifier,
  [734] = 4,
    ACTIONS(84), 1,
      anon_sym_COMMA,
    STATE(28), 1,
      aux_sym_atomics_repeat1,
    ACTIONS(80), 2,
      ts_builtin_sym_end,
      anon_sym_RPAREN,
    ACTIONS(82), 5,
      anon_sym_component,
      anon_sym_signal,
      anon_sym_or,
      anon_sym_and,
      sym_identifier,
  [752] = 4,
    ACTIONS(76), 1,
      anon_sym_COMMA,
    STATE(28), 1,
      aux_sym_atomics_repeat1,
    ACTIONS(87), 2,
      ts_builtin_sym_end,
      anon_sym_RPAREN,
    ACTIONS(89), 5,
      anon_sym_component,
      anon_sym_signal,
      anon_sym_or,
      anon_sym_and,
      sym_identifier,
  [770] = 3,
    ACTIONS(72), 1,
      anon_sym_COMMA,
    STATE(33), 1,
      aux_sym_atomics_repeat1,
    ACTIONS(89), 6,
      anon_sym_component,
      anon_sym_end,
      anon_sym_signal,
      anon_sym_or,
      anon_sym_and,
      sym_identifier,
  [785] = 3,
    ACTIONS(72), 1,
      anon_sym_COMMA,
    STATE(30), 1,
      aux_sym_atomics_repeat1,
    ACTIONS(68), 6,
      anon_sym_component,
      anon_sym_end,
      anon_sym_signal,
      anon_sym_or,
      anon_sym_and,
      sym_identifier,
  [800] = 2,
    ACTIONS(80), 3,
      ts_builtin_sym_end,
      anon_sym_RPAREN,
      anon_sym_COMMA,
    ACTIONS(82), 5,
      anon_sym_component,
      anon_sym_signal,
      anon_sym_or,
      anon_sym_and,
      sym_identifier,
  [813] = 3,
    ACTIONS(91), 1,
      anon_sym_COMMA,
    STATE(33), 1,
      aux_sym_atomics_repeat1,
    ACTIONS(82), 6,
      anon_sym_component,
      anon_sym_end,
      anon_sym_signal,
      anon_sym_or,
      anon_sym_and,
      sym_identifier,
  [828] = 4,
    ACTIONS(96), 1,
      anon_sym_LT_EQ,
    ACTIONS(98), 1,
      anon_sym_COMMA,
    STATE(34), 1,
      aux_sym_identifiers_repeat1,
    ACTIONS(94), 4,
      anon_sym_component,
      anon_sym_end,
      anon_sym_signal,
      sym_identifier,
  [844] = 4,
    ACTIONS(101), 1,
      anon_sym_COMMA,
    STATE(35), 1,
      aux_sym_identifiers_repeat1,
    ACTIONS(96), 2,
      ts_builtin_sym_end,
      anon_sym_LT_EQ,
    ACTIONS(94), 3,
      anon_sym_component,
      anon_sym_signal,
      sym_identifier,
  [860] = 4,
    ACTIONS(108), 1,
      anon_sym_COMMA,
    STATE(40), 1,
      aux_sym_identifiers_repeat1,
    ACTIONS(104), 2,
      ts_builtin_sym_end,
      anon_sym_LT_EQ,
    ACTIONS(106), 3,
      anon_sym_component,
      anon_sym_signal,
      sym_identifier,
  [876] = 4,
    ACTIONS(112), 1,
      anon_sym_LT_EQ,
    ACTIONS(114), 1,
      anon_sym_COMMA,
    STATE(34), 1,
      aux_sym_identifiers_repeat1,
    ACTIONS(110), 4,
      anon_sym_component,
      anon_sym_end,
      anon_sym_signal,
      sym_identifier,
  [892] = 4,
    ACTIONS(104), 1,
      anon_sym_LT_EQ,
    ACTIONS(114), 1,
      anon_sym_COMMA,
    STATE(37), 1,
      aux_sym_identifiers_repeat1,
    ACTIONS(106), 4,
      anon_sym_component,
      anon_sym_end,
      anon_sym_signal,
      sym_identifier,
  [908] = 2,
    ACTIONS(80), 1,
      anon_sym_COMMA,
    ACTIONS(82), 6,
      anon_sym_component,
      anon_sym_end,
      anon_sym_signal,
      anon_sym_or,
      anon_sym_and,
      sym_identifier,
  [920] = 4,
    ACTIONS(108), 1,
      anon_sym_COMMA,
    STATE(35), 1,
      aux_sym_identifiers_repeat1,
    ACTIONS(112), 2,
      ts_builtin_sym_end,
      anon_sym_LT_EQ,
    ACTIONS(110), 3,
      anon_sym_component,
      anon_sym_signal,
      sym_identifier,
  [936] = 3,
    ACTIONS(116), 1,
      ts_builtin_sym_end,
    ACTIONS(120), 2,
      anon_sym_or,
      anon_sym_and,
    ACTIONS(118), 3,
      anon_sym_component,
      anon_sym_signal,
      sym_identifier,
  [949] = 1,
    ACTIONS(120), 6,
      anon_sym_component,
      anon_sym_end,
      anon_sym_signal,
      anon_sym_or,
      anon_sym_and,
      sym_identifier,
  [958] = 3,
    ACTIONS(122), 1,
      ts_builtin_sym_end,
    ACTIONS(120), 2,
      anon_sym_or,
      anon_sym_and,
    ACTIONS(124), 3,
      anon_sym_component,
      anon_sym_signal,
      sym_identifier,
  [971] = 1,
    ACTIONS(126), 6,
      anon_sym_component,
      anon_sym_end,
      anon_sym_signal,
      anon_sym_or,
      anon_sym_and,
      sym_identifier,
  [980] = 2,
    ACTIONS(128), 1,
      ts_builtin_sym_end,
    ACTIONS(130), 5,
      anon_sym_component,
      anon_sym_signal,
      anon_sym_or,
      anon_sym_and,
      sym_identifier,
  [991] = 1,
    ACTIONS(132), 6,
      anon_sym_component,
      anon_sym_end,
      anon_sym_signal,
      anon_sym_or,
      anon_sym_and,
      sym_identifier,
  [1000] = 1,
    ACTIONS(134), 6,
      anon_sym_component,
      anon_sym_end,
      anon_sym_signal,
      anon_sym_or,
      anon_sym_and,
      sym_identifier,
  [1009] = 2,
    ACTIONS(94), 3,
      anon_sym_component,
      anon_sym_signal,
      sym_identifier,
    ACTIONS(96), 3,
      ts_builtin_sym_end,
      anon_sym_LT_EQ,
      anon_sym_COMMA,
  [1020] = 2,
    ACTIONS(136), 1,
      ts_builtin_sym_end,
    ACTIONS(138), 5,
      anon_sym_component,
      anon_sym_signal,
      anon_sym_or,
      anon_sym_and,
      sym_identifier,
  [1031] = 4,
    ACTIONS(122), 1,
      ts_builtin_sym_end,
    ACTIONS(140), 1,
      anon_sym_or,
    ACTIONS(142), 1,
      anon_sym_and,
    ACTIONS(124), 3,
      anon_sym_component,
      anon_sym_signal,
      sym_identifier,
  [1046] = 2,
    ACTIONS(144), 1,
      ts_builtin_sym_end,
    ACTIONS(134), 5,
      anon_sym_component,
      anon_sym_signal,
      anon_sym_or,
      anon_sym_and,
      sym_identifier,
  [1057] = 2,
    ACTIONS(146), 1,
      ts_builtin_sym_end,
    ACTIONS(132), 5,
      anon_sym_component,
      anon_sym_signal,
      anon_sym_or,
      anon_sym_and,
      sym_identifier,
  [1068] = 1,
    ACTIONS(138), 6,
      anon_sym_component,
      anon_sym_end,
      anon_sym_signal,
      anon_sym_or,
      anon_sym_and,
      sym_identifier,
  [1077] = 2,
    ACTIONS(148), 1,
      ts_builtin_sym_end,
    ACTIONS(126), 5,
      anon_sym_component,
      anon_sym_signal,
      anon_sym_or,
      anon_sym_and,
      sym_identifier,
  [1088] = 2,
    ACTIONS(150), 1,
      ts_builtin_sym_end,
    ACTIONS(120), 5,
      anon_sym_component,
      anon_sym_signal,
      anon_sym_or,
      anon_sym_and,
      sym_identifier,
  [1099] = 2,
    ACTIONS(150), 1,
      ts_builtin_sym_end,
    ACTIONS(120), 5,
      anon_sym_component,
      anon_sym_signal,
      anon_sym_or,
      anon_sym_and,
      sym_identifier,
  [1110] = 2,
    ACTIONS(150), 1,
      ts_builtin_sym_end,
    ACTIONS(120), 5,
      anon_sym_component,
      anon_sym_signal,
      anon_sym_or,
      anon_sym_and,
      sym_identifier,
  [1121] = 4,
    ACTIONS(116), 1,
      ts_builtin_sym_end,
    ACTIONS(140), 1,
      anon_sym_or,
    ACTIONS(142), 1,
      anon_sym_and,
    ACTIONS(118), 3,
      anon_sym_component,
      anon_sym_signal,
      sym_identifier,
  [1136] = 2,
    ACTIONS(96), 2,
      anon_sym_LT_EQ,
      anon_sym_COMMA,
    ACTIONS(94), 4,
      anon_sym_component,
      anon_sym_end,
      anon_sym_signal,
      sym_identifier,
  [1147] = 4,
    ACTIONS(152), 1,
      anon_sym_LPAREN,
    ACTIONS(154), 1,
      anon_sym_COMMA,
    STATE(72), 1,
      aux_sym_atomics_repeat1,
    ACTIONS(74), 3,
      anon_sym_RPAREN,
      anon_sym_or,
      anon_sym_and,
  [1162] = 1,
    ACTIONS(120), 6,
      anon_sym_component,
      anon_sym_end,
      anon_sym_signal,
      anon_sym_or,
      anon_sym_and,
      sym_identifier,
  [1171] = 3,
    ACTIONS(156), 1,
      anon_sym_or,
    ACTIONS(158), 1,
      anon_sym_and,
    ACTIONS(124), 4,
      anon_sym_component,
      anon_sym_end,
      anon_sym_signal,
      sym_identifier,
  [1184] = 1,
    ACTIONS(130), 6,
      anon_sym_component,
      anon_sym_end,
      anon_sym_signal,
      anon_sym_or,
      anon_sym_and,
      sym_identifier,
  [1193] = 1,
    ACTIONS(120), 6,
      anon_sym_component,
      anon_sym_end,
      anon_sym_signal,
      anon_sym_or,
      anon_sym_and,
      sym_identifier,
  [1202] = 1,
    ACTIONS(120), 6,
      anon_sym_component,
      anon_sym_end,
      anon_sym_signal,
      anon_sym_or,
      anon_sym_and,
      sym_identifier,
  [1211] = 2,
    ACTIONS(150), 1,
      ts_builtin_sym_end,
    ACTIONS(120), 5,
      anon_sym_component,
      anon_sym_signal,
      anon_sym_or,
      anon_sym_and,
      sym_identifier,
  [1222] = 2,
    ACTIONS(120), 2,
      anon_sym_or,
      anon_sym_and,
    ACTIONS(124), 4,
      anon_sym_component,
      anon_sym_end,
      anon_sym_signal,
      sym_identifier,
  [1233] = 3,
    ACTIONS(156), 1,
      anon_sym_or,
    ACTIONS(158), 1,
      anon_sym_and,
    ACTIONS(118), 4,
      anon_sym_component,
      anon_sym_end,
      anon_sym_signal,
      sym_identifier,
  [1246] = 2,
    ACTIONS(120), 2,
      anon_sym_or,
      anon_sym_and,
    ACTIONS(118), 4,
      anon_sym_component,
      anon_sym_end,
      anon_sym_signal,
      sym_identifier,
  [1257] = 2,
    ACTIONS(150), 1,
      ts_builtin_sym_end,
    ACTIONS(120), 5,
      anon_sym_component,
      anon_sym_signal,
      anon_sym_or,
      anon_sym_and,
      sym_identifier,
  [1268] = 1,
    ACTIONS(120), 6,
      anon_sym_component,
      anon_sym_end,
      anon_sym_signal,
      anon_sym_or,
      anon_sym_and,
      sym_identifier,
  [1277] = 3,
    ACTIONS(154), 1,
      anon_sym_COMMA,
    STATE(74), 1,
      aux_sym_atomics_repeat1,
    ACTIONS(87), 3,
      anon_sym_RPAREN,
      anon_sym_or,
      anon_sym_and,
  [1289] = 3,
    ACTIONS(154), 1,
      anon_sym_COMMA,
    STATE(72), 1,
      aux_sym_atomics_repeat1,
    ACTIONS(74), 3,
      anon_sym_RPAREN,
      anon_sym_or,
      anon_sym_and,
  [1301] = 3,
    ACTIONS(160), 1,
      anon_sym_COMMA,
    STATE(74), 1,
      aux_sym_atomics_repeat1,
    ACTIONS(80), 3,
      anon_sym_RPAREN,
      anon_sym_or,
      anon_sym_and,
  [1313] = 2,
    ACTIONS(165), 1,
      anon_sym_LT_EQ,
    ACTIONS(163), 4,
      anon_sym_component,
      anon_sym_end,
      anon_sym_signal,
      sym_identifier,
  [1323] = 3,
    ACTIONS(167), 1,
      ts_builtin_sym_end,
    ACTIONS(169), 1,
      anon_sym_LT_EQ,
    ACTIONS(163), 3,
      anon_sym_component,
      anon_sym_signal,
      sym_identifier,
  [1335] = 1,
    ACTIONS(171), 4,
      anon_sym_component,
      anon_sym_end,
      anon_sym_signal,
      sym_identifier,
  [1342] = 2,
    ACTIONS(173), 1,
      ts_builtin_sym_end,
    ACTIONS(175), 3,
      anon_sym_component,
      anon_sym_signal,
      sym_identifier,
  [1351] = 2,
    ACTIONS(177), 1,
      ts_builtin_sym_end,
    ACTIONS(179), 3,
      anon_sym_component,
      anon_sym_signal,
      sym_identifier,
  [1360] = 2,
    ACTIONS(181), 1,
      ts_builtin_sym_end,
    ACTIONS(171), 3,
      anon_sym_component,
      anon_sym_signal,
      sym_identifier,
  [1369] = 1,
    ACTIONS(179), 4,
      anon_sym_component,
      anon_sym_end,
      anon_sym_signal,
      sym_identifier,
  [1376] = 1,
    ACTIONS(175), 4,
      anon_sym_component,
      anon_sym_end,
      anon_sym_signal,
      sym_identifier,
  [1383] = 1,
    ACTIONS(80), 4,
      anon_sym_RPAREN,
      anon_sym_or,
      anon_sym_and,
      anon_sym_COMMA,
  [1390] = 3,
    ACTIONS(183), 1,
      anon_sym_RPAREN,
    ACTIONS(185), 1,
      anon_sym_or,
    ACTIONS(187), 1,
      anon_sym_and,
  [1400] = 2,
    STATE(118), 1,
      sym_atomics,
    ACTIONS(50), 2,
      sym_identifier,
      sym_number,
  [1408] = 1,
    ACTIONS(136), 3,
      anon_sym_RPAREN,
      anon_sym_or,
      anon_sym_and,
  [1414] = 2,
    STATE(121), 1,
      sym_atomics,
    ACTIONS(50), 2,
      sym_identifier,
      sym_number,
  [1422] = 3,
    ACTIONS(185), 1,
      anon_sym_or,
    ACTIONS(187), 1,
      anon_sym_and,
    ACTIONS(189), 1,
      anon_sym_RPAREN,
  [1432] = 2,
    STATE(113), 1,
      sym_atomics,
    ACTIONS(50), 2,
      sym_identifier,
      sym_number,
  [1440] = 1,
    ACTIONS(128), 3,
      anon_sym_RPAREN,
      anon_sym_or,
      anon_sym_and,
  [1446] = 1,
    ACTIONS(150), 3,
      anon_sym_RPAREN,
      anon_sym_or,
      anon_sym_and,
  [1452] = 1,
    ACTIONS(150), 3,
      anon_sym_RPAREN,
      anon_sym_or,
      anon_sym_and,
  [1458] = 1,
    ACTIONS(150), 3,
      anon_sym_RPAREN,
      anon_sym_or,
      anon_sym_and,
  [1464] = 1,
    ACTIONS(150), 3,
      anon_sym_RPAREN,
      anon_sym_or,
      anon_sym_and,
  [1470] = 1,
    ACTIONS(148), 3,
      anon_sym_RPAREN,
      anon_sym_or,
      anon_sym_and,
  [1476] = 2,
    STATE(117), 1,
      sym_atomics,
    ACTIONS(50), 2,
      sym_identifier,
      sym_number,
  [1484] = 1,
    ACTIONS(144), 3,
      anon_sym_RPAREN,
      anon_sym_or,
      anon_sym_and,
  [1490] = 1,
    ACTIONS(146), 3,
      anon_sym_RPAREN,
      anon_sym_or,
      anon_sym_and,
  [1496] = 2,
    STATE(119), 1,
      sym_atomics,
    ACTIONS(50), 2,
      sym_identifier,
      sym_number,
  [1504] = 3,
    ACTIONS(185), 1,
      anon_sym_or,
    ACTIONS(187), 1,
      anon_sym_and,
    ACTIONS(191), 1,
      anon_sym_RPAREN,
  [1514] = 1,
    ACTIONS(150), 3,
      anon_sym_RPAREN,
      anon_sym_or,
      anon_sym_and,
  [1520] = 2,
    ACTIONS(193), 1,
      sym_identifier,
    STATE(2), 1,
      sym_identifiers,
  [1527] = 2,
    ACTIONS(193), 1,
      sym_identifier,
    STATE(75), 1,
      sym_identifiers,
  [1534] = 2,
    ACTIONS(195), 1,
      sym_identifier,
    STATE(76), 1,
      sym_identifiers,
  [1541] = 2,
    ACTIONS(193), 1,
      sym_identifier,
    STATE(7), 1,
      sym_identifiers,
  [1548] = 1,
    ACTIONS(197), 2,
      sym_identifier,
      sym_number,
  [1553] = 1,
    ACTIONS(199), 2,
      sym_identifier,
      sym_number,
  [1558] = 1,
    ACTIONS(201), 2,
      sym_identifier,
      sym_number,
  [1563] = 1,
    ACTIONS(203), 1,
      anon_sym_LPAREN,
  [1567] = 1,
    ACTIONS(205), 1,
      anon_sym_LT_EQ,
  [1571] = 1,
    ACTIONS(207), 1,
      sym_identifier,
  [1575] = 1,
    ACTIONS(209), 1,
      sym_identifier,
  [1579] = 1,
    ACTIONS(211), 1,
      anon_sym_RPAREN,
  [1583] = 1,
    ACTIONS(213), 1,
      anon_sym_LT_EQ,
  [1587] = 1,
    ACTIONS(215), 1,
      ts_builtin_sym_end,
  [1591] = 1,
    ACTIONS(217), 1,
      anon_sym_EQ_GT,
  [1595] = 1,
    ACTIONS(219), 1,
      anon_sym_RPAREN,
  [1599] = 1,
    ACTIONS(221), 1,
      anon_sym_RPAREN,
  [1603] = 1,
    ACTIONS(223), 1,
      anon_sym_RPAREN,
  [1607] = 1,
    ACTIONS(225), 1,
      anon_sym_EQ_GT,
  [1611] = 1,
    ACTIONS(227), 1,
      anon_sym_RPAREN,
  [1615] = 1,
    ACTIONS(229), 1,
      sym_identifier,
  [1619] = 1,
    ACTIONS(231), 1,
      anon_sym_LPAREN,
  [1623] = 1,
    ACTIONS(233), 1,
      sym_identifier,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 26,
  [SMALL_STATE(4)] = 52,
  [SMALL_STATE(5)] = 78,
  [SMALL_STATE(6)] = 104,
  [SMALL_STATE(7)] = 130,
  [SMALL_STATE(8)] = 156,
  [SMALL_STATE(9)] = 182,
  [SMALL_STATE(10)] = 213,
  [SMALL_STATE(11)] = 244,
  [SMALL_STATE(12)] = 275,
  [SMALL_STATE(13)] = 306,
  [SMALL_STATE(14)] = 337,
  [SMALL_STATE(15)] = 368,
  [SMALL_STATE(16)] = 399,
  [SMALL_STATE(17)] = 430,
  [SMALL_STATE(18)] = 461,
  [SMALL_STATE(19)] = 492,
  [SMALL_STATE(20)] = 523,
  [SMALL_STATE(21)] = 554,
  [SMALL_STATE(22)] = 585,
  [SMALL_STATE(23)] = 616,
  [SMALL_STATE(24)] = 647,
  [SMALL_STATE(25)] = 678,
  [SMALL_STATE(26)] = 696,
  [SMALL_STATE(27)] = 714,
  [SMALL_STATE(28)] = 734,
  [SMALL_STATE(29)] = 752,
  [SMALL_STATE(30)] = 770,
  [SMALL_STATE(31)] = 785,
  [SMALL_STATE(32)] = 800,
  [SMALL_STATE(33)] = 813,
  [SMALL_STATE(34)] = 828,
  [SMALL_STATE(35)] = 844,
  [SMALL_STATE(36)] = 860,
  [SMALL_STATE(37)] = 876,
  [SMALL_STATE(38)] = 892,
  [SMALL_STATE(39)] = 908,
  [SMALL_STATE(40)] = 920,
  [SMALL_STATE(41)] = 936,
  [SMALL_STATE(42)] = 949,
  [SMALL_STATE(43)] = 958,
  [SMALL_STATE(44)] = 971,
  [SMALL_STATE(45)] = 980,
  [SMALL_STATE(46)] = 991,
  [SMALL_STATE(47)] = 1000,
  [SMALL_STATE(48)] = 1009,
  [SMALL_STATE(49)] = 1020,
  [SMALL_STATE(50)] = 1031,
  [SMALL_STATE(51)] = 1046,
  [SMALL_STATE(52)] = 1057,
  [SMALL_STATE(53)] = 1068,
  [SMALL_STATE(54)] = 1077,
  [SMALL_STATE(55)] = 1088,
  [SMALL_STATE(56)] = 1099,
  [SMALL_STATE(57)] = 1110,
  [SMALL_STATE(58)] = 1121,
  [SMALL_STATE(59)] = 1136,
  [SMALL_STATE(60)] = 1147,
  [SMALL_STATE(61)] = 1162,
  [SMALL_STATE(62)] = 1171,
  [SMALL_STATE(63)] = 1184,
  [SMALL_STATE(64)] = 1193,
  [SMALL_STATE(65)] = 1202,
  [SMALL_STATE(66)] = 1211,
  [SMALL_STATE(67)] = 1222,
  [SMALL_STATE(68)] = 1233,
  [SMALL_STATE(69)] = 1246,
  [SMALL_STATE(70)] = 1257,
  [SMALL_STATE(71)] = 1268,
  [SMALL_STATE(72)] = 1277,
  [SMALL_STATE(73)] = 1289,
  [SMALL_STATE(74)] = 1301,
  [SMALL_STATE(75)] = 1313,
  [SMALL_STATE(76)] = 1323,
  [SMALL_STATE(77)] = 1335,
  [SMALL_STATE(78)] = 1342,
  [SMALL_STATE(79)] = 1351,
  [SMALL_STATE(80)] = 1360,
  [SMALL_STATE(81)] = 1369,
  [SMALL_STATE(82)] = 1376,
  [SMALL_STATE(83)] = 1383,
  [SMALL_STATE(84)] = 1390,
  [SMALL_STATE(85)] = 1400,
  [SMALL_STATE(86)] = 1408,
  [SMALL_STATE(87)] = 1414,
  [SMALL_STATE(88)] = 1422,
  [SMALL_STATE(89)] = 1432,
  [SMALL_STATE(90)] = 1440,
  [SMALL_STATE(91)] = 1446,
  [SMALL_STATE(92)] = 1452,
  [SMALL_STATE(93)] = 1458,
  [SMALL_STATE(94)] = 1464,
  [SMALL_STATE(95)] = 1470,
  [SMALL_STATE(96)] = 1476,
  [SMALL_STATE(97)] = 1484,
  [SMALL_STATE(98)] = 1490,
  [SMALL_STATE(99)] = 1496,
  [SMALL_STATE(100)] = 1504,
  [SMALL_STATE(101)] = 1514,
  [SMALL_STATE(102)] = 1520,
  [SMALL_STATE(103)] = 1527,
  [SMALL_STATE(104)] = 1534,
  [SMALL_STATE(105)] = 1541,
  [SMALL_STATE(106)] = 1548,
  [SMALL_STATE(107)] = 1553,
  [SMALL_STATE(108)] = 1558,
  [SMALL_STATE(109)] = 1563,
  [SMALL_STATE(110)] = 1567,
  [SMALL_STATE(111)] = 1571,
  [SMALL_STATE(112)] = 1575,
  [SMALL_STATE(113)] = 1579,
  [SMALL_STATE(114)] = 1583,
  [SMALL_STATE(115)] = 1587,
  [SMALL_STATE(116)] = 1591,
  [SMALL_STATE(117)] = 1595,
  [SMALL_STATE(118)] = 1599,
  [SMALL_STATE(119)] = 1603,
  [SMALL_STATE(120)] = 1607,
  [SMALL_STATE(121)] = 1611,
  [SMALL_STATE(122)] = 1615,
  [SMALL_STATE(123)] = 1619,
  [SMALL_STATE(124)] = 1623,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = false}}, SHIFT(122),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(104),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(36),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(124),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(80),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(103),
  [17] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(124),
  [20] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [22] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(103),
  [25] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(36),
  [28] = {.entry = {.count = 1, .reusable = false}}, SHIFT(78),
  [30] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [32] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(122),
  [35] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(104),
  [38] = {.entry = {.count = 1, .reusable = false}}, SHIFT(82),
  [40] = {.entry = {.count = 1, .reusable = false}}, SHIFT(77),
  [42] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [44] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [46] = {.entry = {.count = 1, .reusable = false}}, SHIFT(9),
  [48] = {.entry = {.count = 1, .reusable = false}}, SHIFT(27),
  [50] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [52] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [54] = {.entry = {.count = 1, .reusable = false}}, SHIFT(24),
  [56] = {.entry = {.count = 1, .reusable = false}}, SHIFT(25),
  [58] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [60] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [62] = {.entry = {.count = 1, .reusable = false}}, SHIFT(11),
  [64] = {.entry = {.count = 1, .reusable = false}}, SHIFT(60),
  [66] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [68] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_atomics, 1, 0, 0),
  [70] = {.entry = {.count = 1, .reusable = true}}, SHIFT(89),
  [72] = {.entry = {.count = 1, .reusable = true}}, SHIFT(107),
  [74] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_atomics, 1, 0, 0),
  [76] = {.entry = {.count = 1, .reusable = true}}, SHIFT(108),
  [78] = {.entry = {.count = 1, .reusable = true}}, SHIFT(99),
  [80] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_atomics_repeat1, 2, 0, 0),
  [82] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_atomics_repeat1, 2, 0, 0),
  [84] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_atomics_repeat1, 2, 0, 0), SHIFT_REPEAT(108),
  [87] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_atomics, 2, 0, 0),
  [89] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_atomics, 2, 0, 0),
  [91] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_atomics_repeat1, 2, 0, 0), SHIFT_REPEAT(107),
  [94] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_identifiers_repeat1, 2, 0, 0),
  [96] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_identifiers_repeat1, 2, 0, 0),
  [98] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_identifiers_repeat1, 2, 0, 0), SHIFT_REPEAT(112),
  [101] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_identifiers_repeat1, 2, 0, 0), SHIFT_REPEAT(111),
  [104] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_identifiers, 1, 0, 0),
  [106] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_identifiers, 1, 0, 0),
  [108] = {.entry = {.count = 1, .reusable = true}}, SHIFT(111),
  [110] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_identifiers, 2, 0, 0),
  [112] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_identifiers, 2, 0, 0),
  [114] = {.entry = {.count = 1, .reusable = true}}, SHIFT(112),
  [116] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_definition, 4, 0, 0),
  [118] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_definition, 4, 0, 0),
  [120] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expression, 1, 0, 0),
  [122] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_assignment, 3, 0, 0),
  [124] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_assignment, 3, 0, 0),
  [126] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expression_component, 4, 0, 4),
  [128] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression_not, 2, 0, 1),
  [130] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expression_not, 2, 0, 1),
  [132] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expression_and, 3, 0, 3),
  [134] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expression_or, 3, 0, 2),
  [136] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression, 3, 0, 0),
  [138] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expression, 3, 0, 0),
  [140] = {.entry = {.count = 1, .reusable = false}}, SHIFT(18),
  [142] = {.entry = {.count = 1, .reusable = false}}, SHIFT(16),
  [144] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression_or, 3, 0, 2),
  [146] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression_and, 3, 0, 3),
  [148] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression_component, 4, 0, 4),
  [150] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression, 1, 0, 0),
  [152] = {.entry = {.count = 1, .reusable = true}}, SHIFT(96),
  [154] = {.entry = {.count = 1, .reusable = true}}, SHIFT(106),
  [156] = {.entry = {.count = 1, .reusable = false}}, SHIFT(10),
  [158] = {.entry = {.count = 1, .reusable = false}}, SHIFT(23),
  [160] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_atomics_repeat1, 2, 0, 0), SHIFT_REPEAT(106),
  [163] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_declaration, 2, 0, 0),
  [165] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [167] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_declaration, 2, 0, 0),
  [169] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [171] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_component, 8, 0, 5),
  [173] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_component, 9, 0, 5),
  [175] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_component, 9, 0, 5),
  [177] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_statement, 1, 0, 0),
  [179] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_statement, 1, 0, 0),
  [181] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_component, 8, 0, 5),
  [183] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [185] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [187] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [189] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [191] = {.entry = {.count = 1, .reusable = true}}, SHIFT(86),
  [193] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [195] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [197] = {.entry = {.count = 1, .reusable = true}}, SHIFT(83),
  [199] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [201] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [203] = {.entry = {.count = 1, .reusable = true}}, SHIFT(85),
  [205] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [207] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [209] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [211] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [213] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [215] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [217] = {.entry = {.count = 1, .reusable = true}}, SHIFT(102),
  [219] = {.entry = {.count = 1, .reusable = true}}, SHIFT(95),
  [221] = {.entry = {.count = 1, .reusable = true}}, SHIFT(116),
  [223] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [225] = {.entry = {.count = 1, .reusable = true}}, SHIFT(105),
  [227] = {.entry = {.count = 1, .reusable = true}}, SHIFT(120),
  [229] = {.entry = {.count = 1, .reusable = true}}, SHIFT(109),
  [231] = {.entry = {.count = 1, .reusable = true}}, SHIFT(87),
  [233] = {.entry = {.count = 1, .reusable = true}}, SHIFT(123),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_YOUR_LANGUAGE_NAME(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
